### ISSUE TITLE
Why can't we send data the other way as well?

### ISSUE THREAD

**Issue by ConservationMetrics** [Azure/azure-storage-azcopy#746] opened 2019-11-15 07:50 UTC
### Which version of the AzCopy was used? 
10.3.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
copy [from Azure Container to AWS S3]

### What problem was encountered?
Error = "the inferred source/destination combination is currently not supported. "

### How can we reproduce the problem in the simplest way?

Allow data to flow in either direction.  If this is an economically related decision (i.e. data only flows into Azure), I'd argue the logic is flawed.  I actually have a workflow in Azure that generates a large number of output files.  I need to transfer those to an external client working in AWS.  If I cant find a solution, I'll likely just move my workflow to AWS ;)

### Have you found a mitigation/solution?
Nope

Thank you!

**Comment by zezha-msft** [comment] 2019-11-15 08:21
Hi @ConservationMetrics, thanks for reaching out!

I'm closing this issue as it's a duplicate of #348, where we are already tracking this feature request.  😃

**Closed by zezha-msft** 2019-11-15 08:21 UTC
