### ISSUE TITLE
error listing the files inside the given source url

### ISSUE THREAD

**Issue by guderkar** [Azure/azure-storage-azcopy#497] opened 2019-07-12 08:52 UTC
I have two Data lake gen2 storage accounts and I need to transfer about 250GB of data from one to another recursively (the whole file system structure). The file system structure contains lot of files (tens of thousands).

I've tried:
  1. Downloading Data with AzCopy CLI.
  2. Downloading Data with Azure storage explorer (AzCopy underneath).
  3. Transfering Data using Azure Data Factory (I believe AzCopy underneath also).

All resulting same problem - timeout.

Here is the error:

Transfer of 'dev/PROJECT/' to 'Z:\XXX' failed: 120000 items transferred, 
error: failed to perform copy command due to error: cannot start job due 
to error: error listing the files inside the given source url XXX.
...
RESPONSE ERROR (ServiceCode=OperationTimedOut) =====\\nDescription=500
Operation could not be completed within the specified time., Details: (none)\\n

So I think, that it's because there is so much files in filesystem.

--UPDATE--

I've started manually downloading folders one by one using storage explorer and most of them were downloaded sucesfully.

But I ran into one folder which has several MBs and I can't download it what so ever. Download is stucked at "Starting transfer of 'dev/XXX/NB054/' to 'C:\XXX' (using name and key)". But when I download files inside the folder it's OK.

Permissions are same as other folder permissions.

**Comment by adreed-msft** [comment] 2019-07-12 16:01
Out of curiosity, how large is the largest file here? I have a sneaking suspicion that a file is taking over 15 minutes to download and is causing AzCopy to time out.

**Comment by adreed-msft** [comment] 2019-07-12 16:03
Actually wait, scratch that

**Comment by adreed-msft** [comment] 2019-07-12 16:04
I recall we had an issue in the past where AzCopy would just never finish listing files on ADLSG2. I suspect it's somewhat related to this.

**Comment by guderkar** [comment] 2019-07-12 16:15
I also tried Databricks and dbutils.fs.cp to copy the data. Also after while it got stucked. Don't know how DBX implements the copy operation.

**Comment by adreed-msft** [comment] 2019-07-12 17:02
So, judging from your output, it's timing out during enumeration. This was _not_ the same issue as before, where an empty folder's transfer count would go unchecked.

ADLS List queries can only return up to 5000 results at a time, alongside a continuation marker. We use this continuation marker to make the next request until a continuation marker is not present.

Out of curiosity, how long is your average path in this filesystem? I could see 5000 excessively long filepaths timing out AzCopy.

Something is taking too long and AzCopy is timing out. @JohnRusk and @zezha-msft should we allow specifying custom time-out lengths?

**Comment by zezha-msft** [comment] 2019-07-12 19:30
@adreed-msft This looks like a service issue. It appears that we are already limiting list operations to 1000 items [here](https://github.com/Azure/azure-storage-azcopy/blob/master/azbfs/url_directory.go#L115).

Hi @guderkar, sorry for the inconvenience. Could you please provide us the full error message? We need the request ID in order to start the investigation on the service side.

**Comment by guderkar** [comment] 2019-07-13 12:46
This is full error from Data Factory:
```
{
    "errorCode": "2200",
    "message": "Failure happened on 'Source' side. ErrorCode=UserErrorFailedBlobFSOperation,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=BlobFS operation failed for: Operation returned an invalid status code &apos;InternalServerError&apos;. Account: &apos;XXX&apos;. FileSystem: &apos;dev&apos;. Path: &apos;SYSTEM&apos;. ErrorCode: &apos;OperationTimedOut&apos;. Message: &apos;Operation could not be completed within the specified time.&apos;. RequestId: &apos;30068771-b01f-003a-4e40-38e7ca000000&apos;.,Source=Microsoft.DataTransfer.ClientLibrary,''Type=Microsoft.Azure.Storage.Data.Models.ErrorSchemaException,Message=Operation returned an invalid status code &apos;InternalServerError&apos;,Source=Microsoft.DataTransfer.ClientLibrary,'",
    "failureType": "UserError",
    "target": "Copy Data1"
}
```

This is full error from Storage Explorer:
```
Transfer of 'dev/PROJECT/' to 'Z:\' failed: 130000 items transferred, error: failed to perform copy command due to error: cannot start job due to error: error listing the files inside the given source url https://XXX.dfs.core.windows.net/dev/PROJECT/: -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:154 HTTP request failed Get https://XXX.dfs.core.windows.net/dev?continuation=ODgwMTI2ODUzMDA0MTQzNzIxMiAwIC9tYWxsZGF0YWxha2UBMDFENEM3NzdFMEE5N0NGRi9kZXYBMDFENEM3NzgyRDRDN0ZEOC9QUk9KRUNUL21hbGwtYmV0dGVyLXByb2R1Y3QvVFJBTlNGT1JNRUQvTkIwMDEvcGFydC0wMDA5Ny10aWQtNjM3NzIwODkxODgyNzcyNjQzMS02OGJkYTUwMS1hOTUxLTQzOTktYWE5Mi0zMjY5MDA2ODE2ZjktMTAzNjM1OC1jMDAwLnBhcnF1ZXQ%3D&directory=PROJECT%2F&maxResults=1000&recursive=true&resource=filesystem&timeout=901: read tcp IP:63133->IP:443: wsarecv: An existing connection was forcibly closed by the remote host. . (used name and key, discovery not completed)
```

**Comment by JohnRusk** [comment] 2019-09-23 03:06
We will need to try and reproduce this.

**Comment by guderkar** [comment] 2019-09-23 08:21
The problem typically appears when I try to download streaming checkpoint folder created by databricks. More accurately commit folder, e.g. StreamingCheckpoints/query_eventhub/commits (The stream is not active).

**Comment by adreed-msft** [comment] 2019-10-15 19:21
Hi there, could you re-test this scenario on the latest release of azcopy? We've made plenty of changes to the overall enumeration architecture in AzCopy, and it may have resolved your issue.

**Comment by guderkar** [comment] 2019-11-11 09:22
I managed to download streaming checkpoint folder with storage explorer version 1.10.1 and azcopy version 10.2.1. Maybe something changed at service side? But the listing of files is very slow. Listing of 2779 took like one minute. We had to switch to classic blob storage because storing checkpoints to gen2 made huge delays in our streaming solution.

**Comment by zezha-msft** [comment] 2019-11-12 00:11
@guderkar glad to hear it's working now. Btw the latest version of Storage Explorer is 1.11, which includes AzCopy 10.3.1. 

To clarify, do you mean the entire transfer took 1 minute? If not, how were you measuring the listing time?

**Comment by guderkar** [comment] 2019-11-12 15:41
In storage explorer it takes more than one minute until message "(using name and key, discovery completed)" - I guess this is the listing part.
Then it shows progress and downloads all the files in like 30 seconds.

**Comment by Icybiubiubiu** [comment] 2020-03-05 07:00
Hi Experts, 
we hit same kind of issue when using azcopy to upload files to azure container. 
===error===
![image](https://user-images.githubusercontent.com/61815812/75955646-466e8980-5ef1-11ea-8482-3b5ac9be47ea.png)

==========
we see from the log:each request has a default timeout=901s, and our error is did not complete in 901s. Here we want to make clear with you:
1. the sum limitation of files when we use azccopy copy or list? I see @zezha-msft has pointed 1000 times. Does this mean we can have at most 1000 files under a folder to list or to copy?
2. what we can do if we want to use azcopy to transfer a great numbers of  files under a same folder to azure?

**Comment by JohnRusk** [comment] 2020-03-09 00:51
There was never a 1000 limit.  I think you are missing a few zeros there. There was a 100,000 limit for sync, but even that limit has been removed.  In practice, the current versions of AzCopy are good up to a few 10's of millions of files,  and at some stage we'll do some more tuning focused on even higher file counts.

Do you see _any_ data get transferred at all?  If you see none.... that sounds like a connectivity issue to me.

**Comment by zezha-msft** [comment] 2021-04-20 08:53
Closing due to age of issue. The service and the tool have both evolved quite a bit. Please let us know if you still experience this.

**Closed by zezha-msft** 2021-04-20 08:53 UTC
Labels: to-reproduce
