### ISSUE TITLE
Invalid json output from jobs list --output-type json argument when newer version available

### ISSUE THREAD

**Issue by JoshHambright** [Azure/azure-storage-azcopy#2639] opened 2024-04-04 12:25 UTC
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```shell
azcopy jobs list --output-type json
```

### What problem was encountered?

Output of command is invalid json. Message is pre-pended with an additional json object that prevents deserialization of the expected object in the command output.

```shell
{"TimeStamp":"2024-04-04T12:19:16.468967774Z","MessageType":"Info","MessageContent":"INFO: azcopy 10.23.0: A newer version 10.24.0 is available to download\n","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
{"TimeStamp":"2024-04-04T12:19:16.469505977Z","MessageType":"EndOfJob","MessageContent":"{\"ErrorMessage\":\"\",\"JobIDDetails\":[{\"JobId\":\"********",\"CommandString\":\"*************\",\"StartTime\":1711032177708701607,\"JobStatus\":\"Completed\"}]}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
```

Error: Parse error on line 1:
..."PromptTarget":""}}{"TimeStamp":"2024-0
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'

### How can we reproduce the problem in the simplest way?
Install version 10.23 (or any out dated version) and run the command noted above.

### Have you found a mitigation/solution?

Upgrading to 10.24 removes the message but output of the `--output-type json` argument should be outputting valid json in my opinon.

**Comment by gapra-msft** [comment] 2024-04-04 21:25
Hi @JoshHambright 

For json output, the way AzCopy was designed was to send a message per new line. So each line is valid JSON. 

We chose to design AzCopy this way since 
1. AzCopy does not always have all the output at once, it updates the console as updates exist. 
2. Some AzCopy commands support prompting, so we can't always wait until the end of the command to display the entire output. 

My recommendation is to JSON decode after splitting on new line.

**Comment by JoshHambright** [comment] 2024-04-05 12:40
Is that behavior documented anywhere I could only find 

> Format of the command's output. The choices include: text, json. The default value is 'text'. (default "text")

and

>--output-type (string) Format of the command's output. The choices include: text, json. The default value is 'text'. (default "text")

To me if something is specifying the output type as json that output itself should be valid json, we have only observed multiple messages sent this way when there is an upgrade warning so we were caught off guard when this behavior broke a production system.

**Comment by gapra-msft** [comment] 2024-04-11 00:57
Hi @JoshHambright 

JSON output type was primarily implemented for an internal integration and as such, there exists little documentation on it. 

Outputting multiple JSON strings delimited by a new line is standard to how all other AzCopy commands (copy, sync, list, etc) behave.

**Comment by gapra-msft** [comment] 2024-04-23 15:25
Closing as this is not an issue.

**Closed by gapra-msft** 2024-04-23 15:25 UTC
Labels: not-an-issue
