### ISSUE TITLE
azcopy sync re-upload existing files

### ISSUE THREAD

**Issue by StellaZhou64** [Azure/azure-storage-azcopy#1211] opened 2020-10-16 03:47 UTC
### Which version of the AzCopy was used? 
AzCopy/10.6.0 Azure-Storage/0.10 (go1.13; Windows_NT)

### Which platform are you using? (ex: Windows, Mac, Linux)
windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
C:\azcopy.exe sync "$Sources" "https://$StorageAccount.blob.core.chinacloudapi.cn/$Containers$SAS" --recursive=true --delete-destination=true --put-md5 --s2s-preserve-access-tier=false --log-level=ERROR

### What problem was encountered?
It seems azcopy resync / upload existing files on source to target storage account even though no change for the name and timestamp. We picked a file to analyze and found it was firstly deleted, then uploaded. However, we have no clue why that happen.

-- the file was deleted at 2020-10-13T01:17:00：

[root@centos8 0100]# grep "Txxx.PDF" *
000006.log:1.0;2020-10-13T01:17:00.1641906Z;DeleteBlob;SASSuccess;202;4;4;sas;;storage account;blob;"https://storage account.blob.core.chinacloudapi.cn/reportxxx/Final/Cxxx/Txxx0/Txxx.PDF?se=2040-09-02T14:55:13Z&amp;sig=XXXXX&amp;sp=rwdlacup&amp;spr=https&amp;srt=sco&amp;ss=bfqt&amp;st=2020-09-02T06:55:13Z&amp;sv=2019-10-10&amp;timeout=901";"/storage account/reportxxx/Final/Cxxx/Txxx0/Txxx.PDF";84d0c8e1-401e-007b-33fe-a03f5e000000;0;10.168.129.38:51701;2019-12-12;551;0;205;0;0;;;;;;"AzCopy/10.6.0 Azure-Storage/0.10 (go1.13; Windows_NT)";;"9c9eb422-35f8-4123-6e31-235253922274"
 
-- but the same file was uploaded at 2020-10-13T19:01:19：

[root@centos8 azcopy]# grep "Txxx.PDF" 1*/*
1900/000000.log:1.0;2020-10-13T19:01:19.3044105Z;PutBlob;SASSuccess;201;10;10;sas;;storage account;blob;"https://storage account.blob.core.chinacloudapi.cn/reportxxx/Final/Cxxx/Txxx0/Txxx.PDF?se=2040-09-02T14:55:13Z&amp;sig=XXXXX&amp;sp=rwdlacup&amp;spr=https&amp;srt=sco&amp;ss=bfqt&amp;st=2020-09-02T06:55:13Z&amp;sv=2019-10-10&amp;timeout=901";"/storage account/reportxxx/Final/Cxxx/Txxx0/Txxx.PDF";87f6e9bf-801e-0006-1d93-a14e7d000000;0;10.168.129.38:58046;2019-12-12;749;349298;337;0;349298;"jR9VW7PeYEcFJzgWdi2DSQ==";"jR9VW7PeYEcFJzgWdi2DSQ==";"&quot;0x8D86FAA5E7A5272&quot;";Tuesday, 13-Oct-20 19:01:19 GMT;;"AzCopy/10.6.0 Azure-Storage/0.10 (go1.13; Windows_NT)";;"52a97f96-0b90-42d0-69a3-a05625e7166e"

And this is how this file looks on source, name and timestamp never change.
![image](https://user-images.githubusercontent.com/40158671/96211240-592c5f00-0fa6-11eb-8258-19ec1879e86f.png)

### How can we reproduce the problem in the simplest way?
No. We tested small numbers of files sync but cannot reproduce. Not sure whether it may happen for large number of files.
May I know what is the logic for azcopy sync? And how it works with --delete-destination=true? 
Can issue happen like when it traverse files on source then wrongly delete the files on target storage account? Many thanks.

### Have you found a mitigation/solution?
No

**Comment by ricolaten** [comment] 2020-10-26 12:05
Might be related to one issue I just raised: https://github.com/Azure/azure-storage-azcopy/issues/1226

**Comment by zezha-msft** [comment] 2020-11-04 05:47
Upon offline investigation, it was discovered that this issue was caused by the List Blob API misbehaving. This is being fixed by a config rollout on the service side.

**Closed by zezha-msft** 2020-11-04 05:47 UTC
