### ISSUE TITLE
Receiving runtime error: invalid memory address or nil pointer dereference when using azcopy copy on blob container

### ISSUE THREAD

**Issue by tsuggs1** [Azure/azure-storage-azcopy#801] opened 2019-12-20 17:31 UTC

**Comment by tsuggs1** [comment] 2019-12-20 17:32
![Screen Shot 2019-11-22 at 11 59 54 AM](https://user-images.githubusercontent.com/59095744/71278127-b4f56f80-2324-11ea-9c1c-4e87427a192c.png)
<img width="1006" alt="Screen Shot 2019-11-25 at 9 19 53 PM" src="https://user-images.githubusercontent.com/59095744/71278131-ba52ba00-2324-11ea-8eb3-1b37307d768f.png">


Screenshots for reference.

**Comment by tsuggs1** [comment] 2019-12-20 17:32
<img width="641" alt="Screen Shot 2019-12-20 at 12 27 55 PM" src="https://user-images.githubusercontent.com/59095744/71278170-cfc7e400-2324-11ea-9185-42833cb82428.png">
<img width="636" alt="Screen Shot 2019-12-20 at 12 27 32 PM" src="https://user-images.githubusercontent.com/59095744/71278174-d3f40180-2324-11ea-847a-3fede7e4ccf8.png">

**Comment by tsuggs1** [comment] 2019-12-20 17:34
Lastly, I have attempted 3 times and each time it has copied a different number of files before throwing that same error. THe first time it was about 74,000 files, then 64,000 then 43,000.

Thanks!

**Comment by adreed-msft** [comment] 2019-12-20 20:03
Hi there, could you show the full stack trace that azcopy dumped when it crashed? Thanks!

**Comment by tsuggs1** [comment] 2019-12-20 20:58
Hi,

So I am actually running it again to replicate the issue and so far so good.. I will update shortly if it ends up getting all the way through.

In the meantime, is it normal for there to be a number for 'Failed' and what it that means? I also think we have over 2 million blob items in this blob container, would there be any issue why it wouldn't be able to copy all of this?

Thanks for the help!

**Comment by tsuggs1** [comment] 2019-12-20 21:47
Unfortunately the same error came up:
<img width="643" alt="Screen Shot 2019-12-20 at 4 39 02 PM" src="https://user-images.githubusercontent.com/59095744/71294737-5ee5f380-2347-11ea-96ee-4f94982b19c6.png">


Not sure where to locate that full stack trace, I did find a file in the logs but it's ~400 MB so it won't allow me to attach it here. Let me know if that's what you're looking for.

**Comment by xuetao8997** [comment] 2019-12-21 06:15
#### Yes, i really got the same error, the detail as follows:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9b2e52]

goroutine 135 [running]:
github.com/Azure/azure-storage-azcopy/ste.ErrorEx.ErrorCodeAndString(0x0, 0x0, 0x0, 0xc085d22600, 0x17e, 0xc000a45a28, 0x9cb80d)
/home/vsts/work/1/s/ste/ErrorExt.go:25 +0x42
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).failActiveTransfer(0xc001ac1800, 0xbb101a, 0xc, 0xbb2b04, 0xf, 0x0, 0x0, 0xffffffff)
/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:626 +0x9b
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).FailActiveUpload(...)
/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:559
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).FailActiveSend(0xc001ac1800, 0xbb2b04, 0xf, 0x0, 0x0)
/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:596 +0xfe
github.com/Azure/azure-storage-azcopy/ste.scheduleSendChunks.func1()
/home/vsts/work/1/s/ste/xfer-anyToRemote.go:264 +0x63
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x13)
/home/vsts/work/1/s/ste/sender.go:165 +0x1ae
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc00005e000, 0x13)
/home/vsts/work/1/s/ste/JobsAdmin.go:427 +0xe6
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
/home/vsts/work/1/s/ste/JobsAdmin.go:356 +0x682

**Comment by JohnRusk** [comment] 2019-12-23 22:30
@adreed-msft please assign this to yourself if you'll take it from here, else assign it to me.

**Comment by JohnRusk** [comment] 2019-12-23 22:35
@xuetao8997 based on the call stacks, I think you're getting the same error from a _different_ part of the code.  For that reason, I will leave your issue, #800 open too, since it's not exactly a duplicate of this one.

**Comment by tsuggs1** [comment] 2019-12-30 13:08
Hi guys,

Any updates on a resolution for this issue?

**Comment by adreed-msft** [comment] 2019-12-30 20:41
@tsuggs1, it seems as though your case is different than @xuetao8997's.

In @tsuggs1's case, when we get an error on os.Stat while doing a length check, we'll panic here. @tsuggs1, to mitigate your situation, please disable the length check flag on your copy (--check-length=false), and see if you get a further error on your transfer.

In @xuetao8997's case, it seems that we're trying to stringify a nil error-- This is _strange_ behavior to say the least, and it looks to be occurring during a prefetch error. Provided that in order to reach this line of code, prefetchErr must have been non-nil at some point, I believe that the way we're taking in prefetch errors (by reference) is causing us problems, as a future prefetch could return a nil value for error.

@xuetao8997 I haven't got a mitigation for your problem at the moment, but I'll be shooting out a PR soon to ensure that we properly handle prefetch errors so we can start to understand your issue in a little more depth.

**Comment by amthomas46** [comment] 2020-03-30 16:11
Hi, I'm not sure if this is the same issue, but I think it's related? I am using powershell in the Azure Cloud Shell, trying to move a file from one subscription storage account to another.  Here are the PowerShell commands:  

```powershell
$resourceGroup = Get-AzResourceGroup | Where ResourceGroupName -like learn* | Select-Object -Property ResourceGroupName | Select-Object -Index 0

$storageAccount = Get-AzStorageAccount -ResourceGroupName $resourceGroup.ResourceGroupName

$storageAccount.StorageAccountName

$storageAccount.PrimaryLocation

$container = New-AzureRmStorageContainer -StorageAccount $storageAccount -ContainerName "vhdcontainer" -PublicAccess Container

$ctx = New-AzStorageContext -StorageAccountName $storageAccount.StorageAccountName

$token = New-AzStorageContainerSASToken -Name "vhdcontainer" -Context $ctx -Permission rwdlac

$token = New-AzureStorageBlobSASToken -Container "vhdcontainer" -Blob $storageAccount.StorageAccountName -Permission rwd

$storageAccountFQDN = "https://"+$storageAccount.StorageAccountName+".blob.core.windows.net/vhdco
ntainer"+$token

azcopy copy "https://customwinimagesa.blob.core.windows.net/vhdcontainer/customwinimage?REDACTED" $storageAccountFQDN --recursive=true --check-length=false
```

And here is the resulting error
```
13Z&se=2023-03-28T07:15:13Z&spr=https&sv=2019-02-02&sr=b&sig=%2FFtTxGhSbrI%2F0HTicQCht9me19il2uc7Mg%2F2ZvPM7eY%3D" $storageAccountFQDN --recursive=true --check-length=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d26aa]

goroutine 1 [running]:
net/url.(*URL).String(0x0, 0x156, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/url/url.go:775 +0x4a
github.com/Azure/azure-storage-azcopy/cmd.copyHandlerUtil.ConstructCommandStringFromArgs(0xc0000a6730, 0xb896eb)
        /home/vsts/work/1/s/cmd/copyUtil.go:118 +0x47c
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001f9180, 0xc000076d80, 0x2, 0x4)
        /home/vsts/work/1/s/cmd/copy.go:1347 +0x161
github.com/spf13/cobra.(*Command).execute(0xc0001f9180, 0xc000076d00, 0x4, 0x4, 0xc0001f9180, 0xc000076d00)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x11723e0, 0xc00014fdd8, 0x0, 0x0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0000a0920, 0x12, 0xc0000a0920, 0x12, 0xc0000a0980, 0x18, 0xfffff)
        /home/vsts/work/1/s/cmd/root.go:110 +0xcf
main.main()
        /home/vsts/work/1/s/main.go:82 +0x3dd
```

The file I'm trying to copy is 128GB, so I'm not sure if that plays in here. Feel free to ping me - alias: antho

Thank you!

**Comment by JohnRusk** [comment] 2020-03-30 21:09
@amthomas46 Your case of this issue looks like it simply can't parse your command line. Id suggest you add "echo" to the start of your AzCopy command line (so all the params will get echoed out to the screen), then try to manually run the command that your script is constructing. Also, manually, visually sanity check it.  If you're lucky, it's a simple error in the command line . (And yes, AzCopy should handle the error more robustly than it did!)

**Comment by adreed-msft** [comment] 2020-07-16 22:42
@xuetao8997 @tsuggs1 could you see if your cases are resolved?

**Comment by ConstantineK** [comment] 2020-10-14 21:04
@adreed-msft if the goal is to reduce customer confusion, ya'll probably still need some work to report useful error messages. 
I just hit upon this same issue because what I assume is the azcopy command unable to tell me it couldnt interpret things. 
Thankfully this thread exists so I could hope that messing about with the command would help, but it's useless and kind of scary as error messages go

**Closed** 2021-09-08 18:58 UTC
Labels: waiting for customer
