### ISSUE TITLE
Copying between storage accounts with IP restricted SAS doesn't work

### ISSUE THREAD

**Issue by lukerosser** [Azure/azure-storage-azcopy#1373] opened 2021-03-19 09:51 UTC
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac and Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```
 azcopy cp "https://account1.blob.core.windows.net/container?${source_sas_token}" "https://account2.blob.core.windows.net/container?${dest_sas_token}" --recursive
```
SAS token creation:
```
az storage account generate-sas --expiry $sas_end --permissions acuwlr --resource-types sco --services b --account-name account1 --ip <my_ip> --https-only
```
### What problem was encountered?
```
RESPONSE Status: 403 This request is not authorized to perform this operation.
```
Removing the IP restriction from the SAS token allows the copy to work, so it's not a firewall issue or anything to do with permissions.

### How can we reproduce the problem in the simplest way?

Generate an IP restricted SAS token and attempt to copy files between storage accounts.

### Have you found a mitigation/solution?

Do not use IP restrictions in the SAS token

**Comment by Siegfried0** [comment] 2022-07-03 10:31
Is there any progress regarding this issue?
I have a similar problem that might be related to this case.

I have a storage account with network ACLs set up.
Generally it is not allowed to be accessed from public.
I work around this in my pipelines by releasing the agent public IP for the duration of the task on the storage account.
In the following example the SAS generation always works on the first try. The azcopy fails however in estimated 90% of the cases with all 10 attempts. (Whether I wait 50 seconds before or not, does not matter).

Yaml pipeline snippet:
```
# generate SAS Token
- task: AzureCLI@2
  displayName: Generate SAS Token for Container
  inputs:
    azureSubscription: '$(varServiceConnection)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      ipAddress=`curl ipinfo.io/ip`
      az storage account network-rule add -n $(varStorageAccountName) -g $(varStorageAccountRgName) --ip-address $ipAddress
      echo "added ip address to storage account ACL: $ipAddress"
      for i in {1..10}
      do
        echo "Attempt Nr. $i"
        start=`date -u -d "-15 minutes" '+%Y-%m-%dT%H:%M:%SZ'`
        end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%M:%SZ'`
        echo "Start: $start"
        echo "End: $end"
        sasToken=`az storage account generate-sas --permissions rcwlduap --account-name $(varStorageAccountName) --services bfqt --resource-types sco --start $start --expiry $end -o tsv` && echo "sas token generated" && break
        sleep 10
      done
      echo "##vso[task.setvariable variable=containerUrlWithSAS;]https://$(varStorageAccountName).blob.core.windows.net/$(varStorageContainerName)?$sasToken"
      az storage account network-rule remove -n $(varStorageAccountName) -g $(varStorageAccountRgName) --ip-address $ipAddress
      echo "removed ip address from storage account ACL: $ipAddress"
  env:
    AZURE_STORAGE_KEY: $(varStorageKey)

# syncing storage account to work directory with azcopy
- task: AzureCLI@2
  displayName: Download Storage Account Content
  inputs:
    azureSubscription: '$(varServiceConnection)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      ipAddress=`curl ipinfo.io/ip`
      az storage account network-rule add -n $(varStorageAccountName) -g $(varStorageAccountRgName) --ip-address $ipAddress
      echo "added ip address to storage account ACL: $ipAddress"
      #echo "wait for network acl to take effect: 50 seconds"
      #sleep 50
      azcopySuccess=0
      for i in {1..10}
      do
        echo "Attempt Nr. $i"
        ./azcopy sync "$(containerUrlWithSAS)" "./agentLocal" && azcopySuccess=1 && echo "azcopy done" && break
        sleep 10
      done
      az storage account network-rule remove -n $(varStorageAccountName) -g $(varStorageAccountRgName) --ip-address $ipAddress
      echo "removed ip address from storage account ACL: $ipAddress"
      if [[ "$azcopySuccess" -eq "0" ]]
      then
        exit 1;
      fi
```

azcopy error:
```
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 73ce24ad-31c3-bf46-42ae-3ebd3565f785 has started
Log file is located at: /home/vsts/.azcopy/73ce24ad-31c3-bf46-42ae-3ebd3565f785.log


Cannot perform sync due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:b8f527e3-001e-005e-5765-8e495f000000
Time:2022-07-02T22:48:36.8107448Z, Details: 
   Code: AuthorizationFailure
   GET https://saletsencrypt0622.blob.core.windows.net/letsencrypt?comp=list&delimiter=%2F&include=metadata&restype=container&se=2022-07-02t23%3A16%3A09z&sig=-REDACTED-&sp=rwdlacup&srt=osc&ss=tfbq&st=2022-07-02t22%3A31%3A09z&sv=2021-06-08&timeout=901
   User-Agent: [AzCopy/10.15.0 Azure-Storage/0.15 (go1.17.9; linux)]
   X-Ms-Client-Request-Id: [6c34c9e8-2bcc-4840-7ad5-0dce540f3333]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Sat, 02 Jul 2022 22:48:35 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [6c34c9e8-2bcc-4840-7ad5-0dce540f3333]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [b8f527e3-001e-005e-5765-8e495f000000]
```

pseudo mitigation:
Set the storage account network acl to allow all public IP addresses to access the resource.
(But: In some cases you do not want to open the storage account to the public network due to higher security requirements.)

**Comment by gapra-msft** [comment] 2022-12-06 00:15
Hi @lukerosser I believe this is expected behavior for IP restricted SAS to fail for service-to-service copies. Since your SAS token has IP restrictions in it and it does not include the IP addresses of the Azure Storage Service from where the copy operation is being executed, the Azure Storage Service is not able to read the source blob.

To fix this issue, you will need to use a SAS token without IP restriction for copy operation.

**Comment by gapra-msft** [comment] 2022-12-06 00:16
@Siegfried0 could you please reopen a new issue with basic repro steps necessary so we can investigate?

**Comment by gapra-msft** [comment] 2022-12-06 00:17
Closing this issue as it is expected behavior

**Closed by gapra-msft** 2022-12-06 00:17 UTC
