### ISSUE TITLE
Command "azcopy jobs clean --with-status=completed" not cleaning log and plan files

### ISSUE THREAD

**Issue by 20shivangi** [Azure/azure-storage-azcopy#814] opened 2020-01-03 06:22 UTC
Hi,  I am unable to clean log and plan files with command 
"azcopy jobs clean --with-status=completed", it is giving error.

### Which version of the AzCopy was used?
10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux)
windows

### What command did you run?
azcopy jobs clean --with-status=completed

### What problem was encountered?
Error come up : Failed to remove log/plan files due to error: remove C:\*/e8244365-cc14-5a4b-4584-eca6d277ebe3--00000.steV10: Access is denied..

### How can we reproduce the problem in the simplest way?
Simply first run azcopy copy command, it will generate a log and a plan file, then run command
"azcopy jobs clean --with-status=completed", it will throw error.

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment] 2020-01-05 20:46
The "access denied" error suggests that maybe something had the file locked at the time. Was there another instance of AzCopy running by any chance?

**Comment by 20shivangi** [comment] 2020-01-13 08:34
@JohnRusk There was no other instance of AzCopy running at that time

**Comment by JohnRusk** [comment] 2020-01-13 21:53
Hmm, I see this in the error message:  "C:*/e824". That is very weird. Had you set AZCOPY_LOG_LOCATION to "C:\" or perhaps even to "C:\*"?  If so, can you try again to something that's not at the root of the drive, and make sure you do not include a *.

**Comment by 20shivangi** [comment] 2020-01-16 09:22
It is the default location where AzCopy logs are generated and for now, I don't want to change this default location. Is there any other way ?

**Comment by JohnRusk** [comment] 2020-01-16 20:20
You mean you left AzCopy logging to its default location?  That's C:/users/<userRunningAzCopy>/.azcopy.  But I don't see that in your error message. I see C:*

Any idea why that might be happening?

**Comment by JohnRusk** [comment] 2020-01-16 20:21
I'll await your reply before considering next steps.

**Comment by 20shivangi** [comment] 2020-01-17 08:43
Hi, this is the error :
Failed to remove log/plan files due to error: remove C:\Users\shmittal\.azcopy/plans/1b3ff2f6-7da8-7640-7f2c-cc21ffba7692--00000.steV10: Access is denied..

when I am running command : azcopy jobs clean --with-status=completed

**Comment by 20shivangi** [comment] 2020-01-17 09:12
I have changed log location using this command : set AZCOPY_LOG_LOCATION=<value>
and set it to D drive. Even then it is failing with error :
"Failed to remove log/plan files due to error: remove D:\aaaaa/483960f3-473b-774b-725e-c5c66b9e21a7--00000.steV10: Access is denied.."

**Comment by JohnRusk** [comment] 2020-01-20 20:32
Hmm. I don't know why that would fail. Maybe the login that you're running under doesn't have rights to delete from that location.  Can you test with a little Powershell command, running under the same credentials, to delete that file?

**Comment by 20shivangi** [comment] 2020-01-21 07:06
When I am running command:
azcopy jobs clean 
OR
azcopy jobs clean --with-status=failed,
they are running fine.

I think there is some problem in this command only: azcopy jobs clean --with-status=completed

**Comment by markstensgaard** [comment] 2020-01-21 14:38
I'm having this exact problem. 

**_C:\>azcopy jobs clean --with-status=Completed_

INFO: Removing files for job 74df64d1-0d1f-954a-76c9-b828aaa8e45a

Failed to remove log/plan files due to error: remove C:\Users\markjg\.azcopy/plans/74df64d1-0d1f-954a-76c9-b828aaa8e45a--00000.steV10: Access is denied..**

If I repeat the command, I still get the error, but it chooses a different job ID each time.

I also thought like 20shivangi that it seemed to work with statuses other than "Completed", but then I realized that azcopy jobs that end with status "CompletedWithErrors" were put into the .setV10 file as "Completed" rather than "Failed" (this would also seem to be something that could be improved, as I want to separate jobs with errors from those without errors), so the 'successful' clean jobs I tried were not actually finding any files with the given status. So I started a new job, and immediately manually cancelled it, and then tried to clean the "Cancelled" jobs, and got the following:

**_C:\>azcopy jobs clean --with-status=Cancelled_
INFO: Removing files for job 2fc74109-04cb-214b-4c56-f03c2c0fc4f3

Failed to remove log/plan files due to error: remove C:\Users\markjg\.azcopy/plans/2fc74109-04cb-214b-4c56-f03c2c0fc4f3--00000.steV10: Access is denied..**

**Comment by JohnRusk** [comment] 2020-01-21 21:50
I wonder if this has something to do with the fact that the files are accessed by AzCopy as memory-mapped files. I wonder if somehow the mapping is not being released. That sounds like something we could investigate.

**Comment by adreed-msft** [comment] 2020-01-21 22:02
Hey there! I've managed to reproduce this locally. I'll investigate what's causing this.

**Comment by adreed-msft** [comment] 2020-01-22 00:05
![image](https://user-images.githubusercontent.com/49764384/72853941-b4276480-3c67-11ea-9542-d34f25d8ef56.png)

I've got a diagnosis. AzCopy is opening a new job plan file as it's attempting to clean up. This is the first file that gets indexed, incidentally. AzCopy can't delete a file that it currently has open, so it fails, and thus, you can't clean up like that.

For a temporary workaround, you can remove files from the folder manually via explorer or the command line.

**Comment by 20shivangi** [comment] 2020-01-22 08:36
Can you please provide ETA when this command will be fixed?

**Comment by markstensgaard** [comment] 2020-01-22 08:50
Thank you for looking into it. I assume this will be fixed in 10.3.4? 

Also, is there anything that can be done about the jobs that finish with "CompletedWithErrors" from azcopy getting its own status when using this command and **azcopy jobs list** rather than being lumped in as "Completed" with jobs that were actually successful?

**Comment by JohnRusk** [comment] 2020-01-22 20:36
ETA and version number: we're still working on that. We should know the answer within 36 hours, so please ask here late tomorrrow if you have not heard from us before that.

@markstensgaard Can you please log new issue for the CompletedWithErrors question.  BTW, it's unlikely that that one will be fixed as quickly as the deletion issue.  When you log the new issue, please comment on whether using AzCopy's return code (aka error code) will be of any use as a workaround.

**Closed** 2020-01-23 19:39 UTC
