### ISSUE TITLE
AzCopy 10.1.2 - Azure recursive blob copy from container to another on same storage account fail

### ISSUE THREAD

**Issue by gpenin** [Azure/azure-storage-azcopy#404] opened 2019-05-22 12:25 UTC
### Which version of the AzCopy was used? 
AzCopy 10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Ubuntu 18.04 LTS

### What command did you run?
`azcopy copy "https://sadosnnp01appdok.blob.core.windows.net/registry-backup-20190522?${SAS}" "https://sadosnnp01appdok.blob.core.windows.net/registry-backup-20190523?${SAS}" --recursive=true`

### What problem was encountered?

```
Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=Could not verify the copy source within the specified time.
RequestId:f61067e2-701e-0031-3698-10ca4e000000
Time:2019-05-22T12:16:13.5828550Z, Details:
   Code: CannotVerifyCopySource
   PUT https://sadosnnp01appdok.blob.core.windows.net/registry-backup-20190523//docker/registry/v2/blobs/id/fd/fd3afccc-19a6-4bda-a255-580dae30ab16/data?comp=appendblock&se=2019-05-22t12%3A41%3A23z&sig=REDACTED&sp=rwdlacup&srt=sco&ss=b&st=2019-05-22t12%3A11%3A23z&sv=2018-03-28&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.1.2 Azure-Storage/0.6 (go1.10.8; linux)]
   X-Ms-Client-Request-Id: [ca9bc84e-554f-4c3b-4550-e418fd3c090a]
   X-Ms-Copy-Source: [https://sadosnnp01appdok.blob.core.windows.net/registry-backup-20190522//docker/registry/v2/blobs/id/fd/fd3afccc-19a6-4bda-a255-580dae30ab16/data?se=2019-05-22t12%3A41%3A23z&sig=REDACTED&sp=rwdlacup&srt=sco&ss=b&st=2019-05-22t12%3A11%3A23z&sv=2018-03-28]
   X-Ms-Source-Range: [bytes=0-4194303]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [251]
   Content-Type: [application/xml]
   Date: [Wed, 22 May 2019 12:16:13 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [f61067e2-701e-0031-3698-10ca4e000000]
   X-Ms-Version: [2018-11-09]
```

SAS authentication seems to be OK, as I am able to copy single files from the VM to the blob container on the storage account.

### Have you found a mitigation/solution?
Using AzCopy 7.3.0 for this operation.

**Comment by JohnRusk** [comment] 2019-05-22 21:14
That's an interesting one.  It is supposed to work. We will investigate.

**Comment by JohnRusk** [comment] 2019-07-10 22:12
I can't reproduce this failure.

Your example command line looks like you are using the same SAS for both source and destination.  I would expect that to work with certain types of SAS but not others. E.g. its very common to use a SAS that is specific to a particular container. I'd suggest that you try again, this time manually constructing the command line, and, for testing at least, constructing the SAS tokens with one of the standard tools (Portal or Azure Storage Explorer).

**Comment by JohnRusk** [comment] 2019-07-10 22:13
BTW, I've closed this issue in the belief that the root cause is probably something specific to SAS token you were using. Please comment if you think we should re-open the issue.

**Closed by JohnRusk** 2019-07-10 22:12 UTC

**Comment by mischa78** [comment] 2019-09-14 13:06
I have the same issue. Would be nice if I could skip the file that is failing, but the whole process just stops/crashes. I didn't use a SAS token, but used `azcopy login`. A whole bunch of files copy without issue and then halfway through I get this error and there doesn't seem to be a way to copy the other half.
