### ISSUE TITLE
Append blobs written to destination with no blob content

### ISSUE THREAD

**Issue by jusnitlive** [Azure/azure-storage-azcopy#696] opened 2019-10-17 04:17 UTC
### Which version of the AzCopy was used?
10.3.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows x64

### What command did you run?
.\azcopy copy $($sourceStorageContext.BlobEndPoint)$($container.Name)$($sourceSasToken)" "$($destinationStorageContext.BlobEndPoint)$($container.Name)" --recursive --blob-type AppendBlob

### What problem was encountered?
Append blobs were written to the destination storage account without blob contents (0 Bytes)

### How can we reproduce the problem in the simplest way?
Attempt to copy or sync append blobs from blob storage account to blob storage account

### Have you found a mitigation/solution?
Write blobs to destination storage account as block blobs.

**Comment by adreed-msft** [comment] 2019-10-17 19:30
I'm having some trouble reproducing this myself. What kind of permissions does your SAS token hold? What type of blobs are the source blobs?

**Comment by jusnitlive** [comment] 2019-10-18 00:49
Read,Write,Delete,List
I don’t think it has to do with permissions. I was able to write to the destination storage account with the same permissions after setting the blob type to block blobs.
Initially I did not set the blob type flag and they were detected as and written as append blobs.
The source blobs are append blobs.

________________________________

**Comment by JohnRusk** [comment] 2019-10-18 00:55
Just checking, were the append blobs at the destination zero length, or longer, but all zeros inside?

**Comment by jusnitlive** [comment] 2019-10-18 00:57
The append blobs at the destination were 0 length, and empty.
There were no characters – just an empty blob.

________________________________

**Comment by JohnRusk** [comment] 2019-10-18 00:58
Do you still have the log file?  If so, can you check sometime to see if "COPYFAILED" (without the quotes) appears in that file?

**Comment by jusnitlive** [comment] 2019-10-18 01:00
Sadly, I do not have the log file.
I will see if I can reproduce this problem tomorrow.

________________________________

**Comment by zezha-msft** [comment] 2019-11-15 00:58
@jusnitlive since we couldn't repro this on our end, I'm closing the issue for now. Please let us know if you manage to reproduce! Thanks.

**Comment by JasonYeMSFT** [comment] 2020-06-01 19:56
We have seen a similar issue to this. The issue actually occurs when you copy an append blob from a BlockBlobStorage account. See https://github.com/microsoft/AzureStorageExplorer/issues/2821.

**Comment by JohnRusk** [comment] 2020-06-01 20:39
@zezha-msft @adreed-msft @nakulkar-msft This is re-opened due to Jason's comment above.  Can someone take a look?

**Comment by jusnitlive** [comment] 2020-06-03 23:18
This may not be specific to BlockBlobStorage accounts. I experienced this issue with General-purpose v2 accounts. The source blobs were Append blobs, however, my use case was only for archiving so setting the destionation blob-type to BlockBlob suited my needs.

**Comment by gapra-msft** [comment] 2024-01-17 00:18
@JasonYeMSFT I just tried to repro this with latest AzCopy and even tried with storage explorer and I can't get this issue to repro. Could you confirm if this is still an issue?

**Comment by gapra-msft** [comment] 2024-02-13 02:33
Closing this for now as it is not reproducible.

**Closed by gapra-msft** 2024-02-13 02:33 UTC
Labels: waiting for customer
