### ISSUE TITLE
AzCopy doesn't allow explictly setting OAuth credential type

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#719] opened 2019-10-29 18:39 UTC
### Which version of the AzCopy was used? 
10.3.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
s2s copy
azcopy login
cp <src_uri&sas_token> <dst_uri>

### What problem was encountered?
The command above works fine. However, if you attempt to explicitly set the AZCOPY_CRED_TYPE as "OAuthToken", AzCopy fail with error saying that the src needs a sas token, even though a sas token is already there.

### How can we reproduce the problem in the simplest way?
set environment variable AZCOPY_CRED_TYPE to be "OAuthToken"
azcopy login
run the command
see the error message

**Comment by zezha-msft** [comment] 2019-10-29 18:52
@adreed-msft I remember you recently worked on something related to this scenario, could you please take a look when you have time?

**Comment by adreed-msft** [comment] 2019-11-08 00:16
OK, this is being caused by the src token type being overridden by the environment variable. We should prefer the explicit SAS token over the environment variable.

**Comment by adreed-msft** [comment] 2019-11-08 00:16
(In detail, this is a bug with getCredentialInfoForLocation.

**Comment by adreed-msft** [comment] 2019-11-08 00:19
@JasonYeMSFT OAuth is implicit for the destination in this case, just drop the environment variable and your scenario should pass, as temporary mitigation.

**Comment by JohnRusk** [comment] 2019-11-15 02:04
This was fixed in yesterdays 10.3.2 release.

**Closed by JohnRusk** 2019-11-15 02:04 UTC
