### ISSUE TITLE
Slow transfer rate VM to Storage account Azcopy

### ISSUE THREAD

**Issue by riluallah** [Azure/azure-storage-azcopy#538] opened 2019-08-08 19:35 UTC
### Which version of the AzCopy was used? 
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy cp "X:\doa\td" "https://xxxxx.file.core.windows.net/xxxx/yyyy/QQ/new?sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-08-11T00:12:10Z&st=2019-08-07T16:12:10Z&spr=https&sig=REDACTED" --recursive 
### What problem was encountered?
I have 40gb that has alot of sub-directories. The source is coming from an Azure VM HDD to storage account under the same Resource Group and getting this message "Disk maybe limiting speed" having 10 to 30 mbps average transfer rate. I've tested it on 6gb file size and i get 200mbps average.  Would you know whats causing my issue? If i use SSD would make a difference?

### How can we reproduce the problem in the simplest way?
I
### Have you found a mitigation/solution?
Not yet

**Comment by JohnRusk** [comment] 2019-08-08 20:56
So your source is on a VM disk, and there are lots and lots of files, so on average each file is quite small. And you are uploading the data to Azure Files? Is that right?

On the line where it says "disk may be limiting speed" does it also say "Scanning" (earlier on the line)?

I don't know exactly what size your files are, but lets assume they are only about 20 KB on average. 30  Mbps with files that small works out to around 180 files per second, if I've done the math right.  

Most probably, you're just getting too close to the VM's disk IOPS limit. In the current design, AzCopy will be making three IO Operations for every file: one to get its last modified date, one to read the data, and one to get the last modified date again to check the file didn't change while we read it.  I believe that Azure will count each of those towards the IOPS limit for the disk. So if we take 180 files per second, and multiply that by the 3 operations per file, we get 540 operations per second.  That's just above the 500 operations per second limit of most Standard disks. So that would explain why you can't go any faster.

If you look at disk types and sizes here, you can probably find a large premium disk type with a much higher IPOS limit: https://azure.microsoft.com/en-us/pricing/details/managed-disks/   If you used a disk like that, it would probably be faster.

The other possibility is that your VM just can't process any more files per second. (Due to CPU or other capacity constraints).  But that seems less likely than the IOPS limit.  I think the IOPS limit described above is probably the cause.

**Comment by riluallah** [comment] 2019-08-09 05:15
Lots of small file and yes it is uploading to Azure files. It does say scanning. Thanks for the help. I'll be purchasing SSD because i need to transfer TB of files.

**Comment by riluallah** [comment] 2019-08-09 05:38
Originally I got this issue also when i transfer files from on-premise to Azure file storage. So we came up on the workaround to zip the whole data upload to azure storage(400mbps when data is zip) then download it to VM, Unzip it then Azcopy again to Azure file storage. But it seems same thing happened. So I'm convince we must purchase SSD for the data migration. Do you have recommendation or other inputs. Thanks

**Comment by JohnRusk** [comment] 2019-08-09 05:51
There are two other things you might like to consider:

Firstly, if it says "scanning" then you may actually be being limited by the speed at which it can enumerate the files in the directory tree. (That's what it's doing when it says "scanning".)  In a normal AzCopy job, it says Scanning for a little while, then then, once it has identified all the files, that message disappears and the rest of the job consists of just transferring the data.  In your case, the fact that scanning seems to stay displayed for a long time _might_ be part of your problem.  Specifically, if "pending files" is zero and "scanning" is displayed, then it is indeed the scanning that is holding you up.  But, if pending files is well above 10,000 all the time, then the scanning is probably not a problem.

What can you do if scanning is a problem?  You can try SSD, but I'm not absolutely sure it will help, it will probably help a bit.   Also, if scanning is indeed a problem, please let us know.

Secondly, if you go to SSD, and if the "disk may be limiting speed" message goes away, you may find that throughput is still lower than you would like.  In that case, you might like to try Azure Premium Files, which is a faster version of Azure Files. https://azure.microsoft.com/en-au/blog/premium-files-pushes-azure-files-limits-by-100x/ 

Oh, and one more thing, working with really small files is always difficult - it just has a lot more overhead per file, and it is the hardest case when it comes to performance.  Hopefully, SSD and maybe Premium Files will give you what you need. 

Make sure that you look at the IOPS figures for the different _sizes_ of SSD.  You should probably get an SSD that is much too big for what you actually need, just to get the higher IOPS that come with the larger size.

Good luck, and please let us know here if there's anything else we can help with.

**Comment by riluallah** [comment] 2019-08-10 02:19
Thanks a lot for your inputs. Would you mind if i ask is it azcopy the best way to migrate 12 TB of data? Regards to cost/time? Thanks again

**Comment by JohnRusk** [comment] 2019-08-10 02:46
It's hard to give a general purpose answer about "best", for three reasons:
(a) in some cases its better to use a shippable device or a hybrid device (on-premise network endpoint).  To see all the options, open the Azure Portal at a Storage Account in your target region, and choose "Data transfer" to bring up a calculator that will show you the best options for your scenario.
(b) Small files are often a special case.  For instance, if you just put 12 TB into the calculator I mentioned above, it will show you some estimated completion times that are fine for normal-sized files, but not realistic for very small ones.  Having said that, I don't believe any other options shown by that calculator will be better for your workload.
(c) We still have more optimization work to do for AzCopy for small files.  (Some of that work should ship next month, but not all of it).

I only know of one other option that's known to be particularly good for small files, and that's the experimental [Fast Data Transfer](https://www.microsoft.com/en-us/garage/profiles/fast-data-transfer/)  tool that we released through the Microsoft Garage.  However, we are trying to phase it out in most cases, to replace it with AzCopy v10.  I did a lot of work with customers with small files using that tool.  But for customers targeting Azure Files or Blob Storage, I'd always suggest trying AzCopy first now.

In your case, I'm pretty sure that when uploading from a cloud VM you are constrained by the IOPS limit on the disk.  No tool can get around that limit, I'm sorry.  I'm not sure how resizing disks works, or changing disk type. (Specifically, is it fast even when the disk contains small files.  I think it probably IS fast).  As discussed above, if you can increase the disk size and/or change the type to SSD, you should get better performance.

When you were uploading from on-premise, I'm not sure what made that slow. It could have been your on-premise disk; it could have been AzCopy's default concurrency value being too low for small files over your network; or it could even have been Azure Files throughput limits.

In conclusion, for small files your throughput will almost certainly be determined by your disk IOPS limit or the Azure Files IOPS limit (whichever is lowest).  You can look those limits up.  As long as the tool you are using hits one of those limits (whichever is lowest) then no other tool will do it faster(*).  

(*) As noted above, AzCopy currently does 3 IO operations for each small file.  That's inefficient.  A future version of AzCopy might therefore be 3 times faster for small files if it did that differently.  And/or some other tool that only does 1 operation per file might be faster.  But I don't know of any such tool that's optimized for small files. Even Fast Data Transfer does 3 operations per file, for the same reason that AzCopy does.

So what can you do? You can use big fast disks.  You can use Azure Premium Files, if necessary, and there's one more trick you can do if you're desperate and don't mind more complexity. It goes like this:

1. Make copies of the VHD that you are reading from. E.g. make 3 copies of it, so you have 4 disk images in total. (I can't remember how to clone managed disks in Azure, but a quick web search should tell you that).  It's "only" 12 TB, so it shouldn't take too long to duplicate. E.g. a small number of hours.  As noted above, I don't think the size of the files affects the time taken to clone the disk.
2. Mount each copy in a separate VM.
3. Now, in each VM, select only part of the data to upload. E.g. if your file system has 40 directories to upload, and you have 4 VMs, you would do 10 directories from each VM.  Take care do to each directory exactly once. E.g. if you do directory "aaa" from VM1, don't do it from any other VMs. This is why I said you should only do this if you are desperate and careful :-)  If you do this, it's at your own risk and you need to take care not to mess it up ;-)

An approach like that should get you 4x the current speed that you are seeing (or more, if you use more VMs or if you also upgrade the disk type or disk size)  If you try it, watch out for Azure Files IOPS limits and upgrade to Premium Files if needed.

I don't know any option that would be faster for you. Sorry.  Small files are difficult.

**Comment by JohnRusk** [comment] 2019-08-10 03:01
PS [UltraSSD](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-types#ultra-ssd-preview) (currently in preview) is the Azure disk type that will offer the highest IOPS of all.  So one day, once that's out of preview, it might be a great solution for upgrading disk performance for your production workload. (And you can test on it while its in preview).

**Comment by JohnRusk** [comment] 2019-08-10 03:08
I'm also asking around the Azure Storage team to see if there's any way to improve on or simplify the "cloning" suggestion that I made.  If any answers come back, they'll probably do so early next week, and I'll update this thread.

**Comment by riluallah** [comment] 2019-08-12 12:52
Hello,
It works, zipping file and transferring has a lot of improvement. Thanks again, I would like to ask also how would i copy a certain file without the parent folder on azcopy 10. azcopy cp "G:\new1\*" seems not working on this version

**Comment by JohnRusk** [comment] 2019-08-12 20:30
AzCopy cp g:\folder\* http://targeturl --recursive 

Note the \* at the end

**Comment by JohnRusk** [comment] 2019-08-12 20:31
Oops thats for a whole folder. To do one file, just do it's full path, no wildcards

**Comment by JohnRusk** [comment] 2019-09-19 09:07
>I'm also asking around the Azure Storage team to see if there's any way to improve on or simplify the "cloning" suggestion that I made

Unfortunately, there are no easy ways to implement that particular suggestion.

**Comment by JohnRusk** [comment] 2019-09-19 09:08
I'm going to close this now, since I think we've provided all relevant information in the thread. Please let us know if you need it reoponed.

**Closed by JohnRusk** 2019-09-19 09:08 UTC
