### ISSUE TITLE
Sync doesn't work when using colon ':' in path

### ISSUE THREAD

**Issue by wagnerock** [Azure/azure-storage-azcopy#820] opened 2020-01-08 17:09 UTC
### Which version of the AzCopy was used? 
10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 

### What command did you run?

azcopy sync --log-level "ERROR" $source https://[storageaccount].blob.core.windows.net/logarchive/$source 

where $source = 'C:\services\logs'

### What problem was encountered?

The sync command doesn't scan the destination, copies every file every time

### How can we reproduce the problem in the simplest way?
Set up a sync operation using a colon in the destination path

### Have you found a mitigation/solution?
Removing the colon from the destination path

**Comment by JohnRusk** [comment] 2020-01-08 20:11
Oh, that doesn't look good. We'll see if we can reproduce it here.

**Comment by JohnRusk** [comment] 2020-05-29 06:29
I'm guessing this _might_ be fixed now, due to work done on enumeration in recent releases.

**Comment by adreed-msft** [comment] 2020-07-16 22:36
Considering that : is an invalid item in a Windows path, I'm not surprised that this doesn't work. I'd suggest trying to use include-path and exclude-path.

**Comment by adreed-msft** [comment] 2020-07-16 22:38
I'm going to close this issue, since this wouldn't work due to platform limitations. Feel free to re-open it if you feel it's more serious.

**Closed by adreed-msft** 2020-07-16 22:38 UTC

**Comment by wagnerock** [comment] 2020-07-17 13:58
The problem I had was with the : in the destination, not the source. Once I removed the colon from the destination path in Azure storage, the sync worked. I believe the colon character works in destinations when using the copy command, but not sync.
