### ISSUE TITLE
`--include-after` Does Not Appear to Work As Expected

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-storage-azcopy#2610] opened 2024-03-14 15:08 UTC
### Which version of the AzCopy was used? 
10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`azcopy copy $from $to --recursive --include-after $Starting`

### What problem was encountered?`
I am running the above command and it's copying every file in the container, seemingly ignoring the `--include-after` flag.  According to the documentation this field is for modified files, but what about files that have not been modified?  This is not clear.  I would like to be able to copy only files created after the provided date.

### How can we reproduce the problem in the simplest way?
Hopefully by running the above with your own variables set.

### Have you found a mitigation/solution?
Not yet, reporting here to seek options.

**Comment by vibhansa-msft** [comment] 2024-03-14 17:29
Your expectation is correct here, include-after flag shall only copy files which are created or modified after the given date. 
Can you share logs to debug further on why its not working in your case.
What does '$Starting' represent here.

**Comment by Mike-E-angelo** [comment] 2024-03-14 17:34
Thank you for your assistance @vibhansa-msft and for the confirmation.  I emit `$Starting` and it is such:
`2023-09-14T03:10:49.7346728-04:00`

Does that look like the right format?

As for logs, I do have them.  What is the best way of getting this to you?

**Comment by vibhansa-msft** [comment] 2024-03-15 05:13
If the log file is small you can share it here (just REDACT the account name and container names or keys if any). If its larger may be you can upload it some storage account and share me the link with read permission only. 
To validate the date format, open AzCopy logs and go through first few lines. It will print a message that says if you wish to run azcopy again for files modified after this job was started use this particular date/time. Just copy paste the date time and flags from there (to avoid any human errors).

**Comment by Mike-E-angelo** [comment] 2024-03-15 07:34
Logs are 58MB zipped, I would rather send them to a secure channel if possible.

Here is what I see:

```
2024/03/14 07:10:55 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2024-03-14T07:10:50Z or --include-after=2024-03-14T07:10:50Z
```

That looks a little different from mine, which is what I get when I call PowerShell's `Get-Date -Format "o"`:
https://stackoverflow.com/a/45689892

However, I see there's a lesser voted answer that makes use of a different format which seems to be what we're looking for:
https://stackoverflow.com/a/45691144

**Comment by Mike-E-angelo** [comment] 2024-03-15 07:40
This seems to emit the expected format as provided in the logs: 

`(Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssK")`

**Comment by vibhansa-msft** [comment] 2024-03-15 10:01
Use flag and value format shown in the logs, others may produce uncertain outputs. With this format if you are able to run it correctly kindly close this bug report.

**Comment by Mike-E-angelo** [comment] 2024-03-15 10:09
Unfortunately, I will not be able to run it for some time as deployments have already occurred, but am willing to close this issue until I run a deployment.  However, as I understand it, I am providing what the documentation says to provide:

```
--include-after (string) Include only those files modified on or after the given date/time. The value should be in ISO8601 format.
```

If `2023-09-14T03:10:49.7346728-04:00` is an ISO8601 formatted date value but is not being processed/parsed on your end, isn't that a bug?

Additionally, if there is a specific format of ISO8601 that the API expects, this should be reflected in the documentation.

**Comment by Mike-E-angelo** [comment] 2024-03-16 10:23
I did another deployment and I think I found the problem here.  The instructions are calling for an `=` as such from the log files:
```
2024/03/15 17:06:03 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2024-03-15T17:05:58Z or --include-after=2024-03-15T17:05:58Z
```

The documentation does not give a precise example so it'd difficult to know.  I have added an `=` to my PowerShell and will advise upon my next deployment.

**Comment by vibhansa-msft** [comment] 2024-03-18 04:51
You mean something like "--include-after=<date time>" we need to provide?

**Comment by Mike-E-angelo** [comment] 2024-03-18 07:33
Correct @vibhansa-msft that is the theory I am currently operating under. :)

**Comment by gapra-msft** [comment] 2024-03-18 16:21
> I did another deployment and I think I found the problem here. The instructions are calling for an `=` as such from the log files:
> 
> ```
> 2024/03/15 17:06:03 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2024-03-15T17:05:58Z or --include-after=2024-03-15T17:05:58Z
> ```
> 
> The documentation does not give a precise example so it'd difficult to know. I have added an `=` to my PowerShell and will advise upon my next deployment.

@siminsavani-msft could you look into this as well and validate if this is the behavior? If so, we should properly document this and make it clear for the user.

**Comment by siminsavani-msft** [comment] 2024-03-18 20:41
Hi @Mike-E-angelo ! You shouldn't need the '=' to allow parsing of the ISO8601 formatted date and time in AzCopy and the formatted time you shared looks correct and I was able to test it out as well. I had a few clarifying questions for you:
1. Are you performing Blob to Blob?
2. If you are able to, can you reproduce this at a smaller scale? No worries if this is not possible!
3. I've tried to replicate your scenario and I'm unable to see the issue you are running into. Do you have any suggestions on what else I could test out? For reference, here are a few things, I've tried in order to reproduce your scenario.

- Save ISO8601 formatted time that is similar to yours in $starting and respective source and destination URLs in the respective variables in Powershell. 
```
> $starting="2024-03-14T03:10:49.7346728-04:00"
> azcopy copy $sourceblobcontainerurlwithsas $destinationblobcontainerwithsas --recursive --include-after $starting 
```

-  No equal sign, no quotes
```
> azcopy copy "source.url.here" "dest.url.here" --recursive --include-after 2024-03-14T03:10:49.7346728-04:00
```

-  Equal sign, no quotes
```
> azcopy copy "source.url.here" "dest.url.here" --recursive --include-after=2024-03-14T03:10:49.7346728-04:00
```

- No equal sign, quotes
```
> azcopy copy "source.url.here" "dest.url.here" --recursive --include-after "2024-03-14T03:10:49.7346728-04:00"
```

4. In our AzCopy code, here are the list of supported ISO8601 formats for your reference (again, I tested your format and it is acceptedm matches with line 437): https://github.com/Azure/azure-storage-azcopy/blob/d6d5c766b46e3a385cecf2cc62d6323e94a72c4e/cmd/zc_filter.go#L435-L441

https://github.com/Azure/azure-storage-azcopy/blob/d6d5c766b46e3a385cecf2cc62d6323e94a72c4e/cmd/zc_filter.go#L34

**Comment by Mike-E-angelo** [comment] 2024-03-19 07:33
Hi @siminsavani-msft thank you for your efforts and investigation.

1. In this case I am copying container to container, I believe.
2. I can probably look into this for you.  However, I do still have the logs from the last attempt and can get them to you if you provide a secure channel to do so.
3. Unfortunately I am unclear of what else could be contributing to this issue. :(
4. This all looks good.  I wonder what the issue could be. 🤔

I will see if can carve out some time to further investigate on my side, but I think getting the logs over to you would be a good first step.

**Comment by siminsavani-msft** [comment] 2024-03-19 16:11
@Mike-E-angelo thanks for getting back to me!

Would it be possible for you to upload the logs into a storage account and share the link with read permission? Or you can send it at siminsavani AT microsoft .com.

**Comment by Mike-E-angelo** [comment] 2024-03-20 08:02
Hi @siminsavani-msft I have sent you a link to download at the provided address.  Please let me know if there is any further information I can provide and I will assist you.

**Comment by siminsavani-msft** [comment] 2024-03-20 14:42
Hi @Mike-E-angelo ! I took a look at the logs and noticed that the timestamp you are using for --include-after is actually 2023-09-16T07:26:44Z (which in UTC would be Sep 16, 2023, 7:26:44 AM) and the timestamp you shared with me is 2023-09-14T03:10:49.7346728-04:00 (UTC: Sep 14, 2023, 7:10:49 AM). Is this intentional?

**Comment by siminsavani-msft** [comment] 2024-03-20 15:03
@Mike-E-angelo Thanks for letting me know! And you were seeing all the files upload with this other attempt as well (include-after being ignored)?

**Comment by Mike-E-angelo** [comment] 2024-03-20 15:07
Correct @siminsavani-msft both attempts resulted in all files being transferred, not just the ones after the provided date as expected.

**Comment by siminsavani-msft** [comment] 2024-03-20 16:25
Gotcha, if you could try adding the '=' to see if it makes any difference, that would be awesome! I wonder if the shell might not be supporting w/o '=', I've experienced Powershell being picky about syntax in the past so I'm wondering if this may be a similar case. 

From the logs, I wasn't able to gauge much for the file's original LMT but I did try using the different format in your copy command and it worked for me.

**Comment by Mike-E-angelo** [comment] 2024-03-22 13:25
Hi @siminsavani-msft I tried a deployment this morning and unfortunately the `=` did not work. 

For further context, here is the code that executes:

```
param (
    [Parameter(HelpMessage="The name of the resource group where the source database is in")]
    [string]$SourceDataResourceGroup = '...',
    [Parameter(HelpMessage="The name of the server where the source database is in")]
    [string]$SourceDataServer = '...',
    [Parameter(HelpMessage="The name of the source database")]
    [string]$SourceDatabase = '...',
    #
    [Parameter(Mandatory=$true,HelpMessage="Name of the resource group to make the deployment")]
    [string]$ResourceGroupName,
    [Parameter(Mandatory=$true, HelpMessage="The name of the destination server to copy the database to")]
    [string]$DestinationServer,
    [Parameter(HelpMessage="The name of the created database")]
    [string]$DatabaseName = '...',
    #
    [Parameter(HelpMessage="The name of the storage to copy from")]
    [string]$SourceStorage = '...',
    [Parameter(Mandatory=$true, HelpMessage="The name of the storage to copy from")]
    [string]$DestinationStorage,
    [Parameter(HelpMessage="The starting time of files to copy")]
    [string]$Starting = "2022-06-01T00:00:00.0000000"
)
$tomorrow = (Get-Date).AddDays(1).ToString("yyyy-MM-dd")
foreach ($name in @("assets", "productions", "storefront"))
{
    $container = "$($name)container"
    $sourceSAS = az storage container generate-sas --account-name $SourceStorage --name $container --permissions lr --expiry $tomorrow -o tsv
    $destinationSAS = az storage container generate-sas --account-name $DestinationStorage --name $container --permissions clrw --expiry $tomorrow -o tsv
    $from = "https://$SourceStorage.blob.core.windows.net/$($container)?$sourceSAS"
    $to = "https://$DestinationStorage.blob.core.windows.net/$($container)?$destinationSAS"
    "$SourceStorage::$container -> $DestinationStorage::$container $Starting"
    azcopy copy $from $to --recursive --include-after=$Starting
}

```

Output example:
```
source::assetscontainer -> destination::assetscontainer 2023-09-22T12:08:17Z
```

Wondering if you can spot anything in there that may be contributing to this issue.

Additionally, it is surprising that the logs do not relay much information.  Are values being passed in correctly?

**Comment by siminsavani-msft** [comment] 2024-04-04 21:04
Hi @Mike-E-angelo ! Sorry for the delay! That's a bummer! 

Nothing strikes out to me as odd in the sample you shared. I'm operating under the assumption that the different timestamps shared in the sample (`$Starting = "2022-06-01T00:00:00.0000000"`) and output `(2023-09-22T12:08:17Z`) are different runs and this is intentional. 

Would you be willing to run the actual command on Powershell instead of using a script? Maybe a smaller execution?

I saw in the logs you shared that there was one run which was Local to Blob but it did not have a timestamp appended to the command. The other three runs for storefrontcontainer, productionscontainer, and assetscontainer all have the correct format (`--include-after 2023-09-16T07:26:44Z` )

**Comment by Mike-E-angelo** [comment] 2024-04-05 07:44
Thank you for your continued investigation @siminsavani-msft 🙏

> The other three runs for storefrontcontainer, productionscontainer, and assetscontainer all have the correct format (--include-after 2023-09-16T07:26:44Z )

Alright, so if I understand correctly, the logs are showing `--include-after 2023-09-16T07:26:44Z` but the actual files processed and copied are all the files from the source container?

> Would you be willing to run the actual command on Powershell instead of using a script? Maybe a smaller execution?

Sure, but let's make sure I understand the above first. 😁

**Comment by Mike-E-angelo** [comment] 2024-04-05 17:13
No worries, it was a bit unclear.  What I meant from the source container is that it seems that *all* files from the containers were copied, not just the ones from after the date as requested.  Is this correct?

**Comment by Mike-E-angelo** [comment] 2024-04-05 19:03
> I wasn't able to determine this from the logs as I don't have any information about last modified time on the source files, unfortunately

It is interesting to learn that this key metric is not validated/verified in the generated logs 🤔

> Ideally, only the files after the date should've been uploaded to the destination (based on the last modified time)

I thought it might be based on last modified, too, but according to [this comment](https://github.com/Azure/azure-storage-azcopy/issues/2610#issuecomment-1997977379) it is _also_ based on created time.

1. Can I please get confirmation that it is created time along with modified time?
2. Is there a way to easily print out older files from Azure Storage so that I can correlate the created/modified times and validate which files should have been (or not) copied?

**Comment by Mike-E-angelo** [comment] 2024-04-09 13:10
I figured out my issue here @siminsavani-msft and it's making me do a total 🤦‍♂️🤦‍♂️🤦‍♂️

The files I currently have were previously copied from another production Azure Storage account, which was the previous account used for my production environment.  I used the same script and process, and I recall everything working as expected.

As I copied the previous storage environment into the new one, I am now just realizing that all the files have their created date set to when I copied them and not their original created dates from the previous storage account. 😞

So, this is why it's not working for me anymore.  I really wish I had noticed this earlier!  Apologies for the disruption and friction encountered here in assisting me to get to this point.

However, I do have two thoughts:

1. The logs should definitely emit the created/modified time when `--include-after` is specified (or maybe every time)
2. There should be a way to preserve created/modified times from the source.  If there is a way to do so already that would be great to know, otherwise, we should create a feature request as this is an important quality in my case.

Thank you for any consideration!

**Comment by siminsavani-msft** [comment] 2024-04-09 14:58
Hi @Mike-E-angelo ! No worries at all! I'm really glad to hear your problem was resolved! 

1. I'll share this thought with the team to see if there is anything we can do to make the created/modified time easily accessible on the log side, but we usually try to keep the logs as condensed as possible.
2. It would be tricky to "preserve" the create/modified time when transferring to an Azure location because "any operation that modifies the blob, including an update of the blob's metadata or properties, changes the last modified time of the blob." 

I will close the issue and share our findings with the team. If there are any updates, I will update this issue accordingly!

**Closed by siminsavani-msft** 2024-04-09 14:58 UTC
Labels: documentation update
