### ISSUE TITLE
Performance copying (cloning) files inside a Storage Account.

### ISSUE THREAD

**Issue by Lumute** [Azure/azure-storage-azcopy#1070] opened 2020-06-25 14:35 UTC
### Which version of the AzCopy was used?
10.4.3 (x64)

### Which platform are you using? 
Windows

### What command did you run?
azcopy copy https://[storageaccount].blob.core.windows.net/[container]/[path/to/blob]?snapshot&[SAS] https://[storageaccount].blob.core.windows.net/[container]/[path/to/newblob]?[SAS]

### What problem was encountered?
I have Large databases with MDF and LDF files stored directly into Azure Storage Accounts. I often need to create a new database out of a previous snapshot of an existing database. When issuing the restore with move command in SQL if the new database's files are set to use the same storage account, the restore takes 2 to 3 sec vs a couple of min if using different Storage Accounts. Azure Storage subsystem is effectively cloning a 40 GB file in under 3 sec. I have always assumed the storage subsystem is just creating pointers to the same underlying data thus this is super fast.

If I use powershell Start-AzStorageBlobCopy then the copy completes successfully in 2 to 3 sec as well so the AZ powershell module is also taking advantage of the fact the source and destination are on the same storage account. I know the Start-AzStorageBlobCopy is asynchronous so I am using Get-AzStorageBlobCopyState to time until the copy is completed.

When I try to copy with AZCopy (command Above) doing the same takes about 1.8 min, so it seems AZCopy is actually duplicating all the data.

Why is AZCopy not able to do this in a similar way? or am I using the wrong command / missing a flag to enable this somehow? I tried using --from-to BlobBlob (no clue if this is an option as I could not file a list of accepted options) and it didn't complain about it but took the same time...

### How can we reproduce the problem in the simplest way?

Copy a page blob snapshot from a 40GB file into a new page blob inside the same storage account.

### Have you found a mitigation/solution?

Using Powershell Start-AzStorageBlobCopy

**Comment by adreed-msft** [comment] 2020-06-26 17:06
You're right-- AzCopy is indeed duplicating the data with the PutUnitFromURL commands.

This seems like a potentially useful upgrade. @zezha-msft @nakulkar-msft what are your thoughts on potentially including something like this (especially since it's so performance-oriented)?

It's a slight hack against our original code, but it would be speedy.

**Comment by vibhansa-msft** [comment] 2023-12-27 04:50
Can you try with the latest version of azcopy and confirm the issue persists? We have migrated to a newer version of SDK and this should have been taken care of automatically I believe.

**Comment by gapra-msft** [comment] 2024-01-17 00:05
Hi @Lumute AzCopy uses server side sync copy APIs and it returns when the copy has completed, whereas I believe Start-AzStorageBlobCopy uses server side async copies and the copy is not guaranteed to finish within a certain timeframe. Please read [this ](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id#remarks)for further info. 

This is expected behavior. Closing this issue as a result.

**Closed by gapra-msft** 2024-01-17 00:05 UTC
Labels: performance, can-be-closed
