### ISSUE TITLE
AzCopy can't handle UTF8-BOM file passed to --list-of-files 

### ISSUE THREAD

**Issue by oerpli** [Azure/azure-storage-azcopy#366] opened 2019-05-03 09:11 UTC
### Which version of the AzCopy was used?
10.1.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10, 1709
### What command did you run?
```
>> [...]> $ulFile
>> azcopy copy "[...]\*" $url
    --overwrite=false 
    --follow-symlinks
    --recursive
    --from-to=LocalBlob
    --blob-type=BlockBlob
    --list-of-files $ulFile
```
(formatted for legibility)
### What problem was encountered?
```
failed to parse user input due to error: 
    error invalid character 'ï' looking for beginning of value
    unmarshalling the contents of bla.json file passed with the list-of-file flag
```
### How can we reproduce the problem in the simplest way?
* Set output encoding of PS to UTF8 (`$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'`)
* Use Powershell to save json to some file (`... > files.json`)
* Pass it with `--list-of-files files.json` to azcopy

### Have you found a mitigation/solution?
Converting the file to UTF8 (without BOM) solves the issue.

I recommend Microsoft should either support UTF8 (i.e. UTF8 without BOM) as output encoding (without weird workarounds) in PowerShell (and everywhere else) or add support for UTF8-BOM in their tooling (I recommend the former).

I tried some things to get UTF8 as the default encoding, which resulted in the following warning and a fallback to UTF16 LE:
```
The argument <encoding> does not belong to the set
"unknown,string,unicode,bigendianunicode,utf8,utf7,utf32,ascii,default,oem" specified by the ValidateSet attribute.
 Supply an argument that is in the set and then try the command again.
```

**Comment by JohnRusk** [comment] 2019-06-07 00:55
Thanks @oerpli.  We've logged this for investigation.

**Comment by JohnRusk** [comment] 2019-08-06 06:28
@oerpli Version 10.3 is moving away from JSON format for this file, and using a simple list with one file per line and no other formatting.  That may automatically solve the problem.  I'll try to find time to test to make sure.

**Comment by adreed-msft** [comment] 2019-09-25 22:22
This has an issue in the refactor, but is actually mostly fixed. I've added a trimmer in the list-of-files preparer. @JohnRusk I'll add it in the refactor/final-bits branch.

**Comment by JohnRusk** [comment] 2019-10-11 00:45
Fixed in version 10.3, which has just been released.  Note that the list-of-files format has changed to a simple list in this release (no longer JSON). See https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer

**Closed by JohnRusk** 2019-10-11 00:45 UTC
Labels: fixed/pending release

**Comment by kva888** [comment] 2020-04-19 00:00
When I use the -list-of-files option, I get an error "failed to parse user input due to error: cannot open 'c:\blobs.txt; file passed with the list-of-file flag. I am using the latest AzCopy 10.4
**Example cmd used:** **AzCopy copy "https://****.blob.core.windows.net/<containername>**<SASTOKEN>" "C:\BlobsDownload" --list-of-files 'C:\blobs.txt'

**Comment by JohnRusk** [comment] 2020-04-19 21:11
@kva888  Do you know whether your issue is the same as the one listed here?  I.e. is yours caused by the presence of a UTF 8  byte order mark at the start of the file?  If yours is not caused by that, please log a new issue.

To test, use a text editor such as Notepad++ and set the file encoding to "UTF-8" not "UTF-8-BOM". If that makes it work, then you do have the BOM issue.  If that doesn't make it work, then you have a different issue.
