### ISSUE TITLE
IOPS throttling of AZCopy

### ISSUE THREAD

**Issue by EvertEt** [Azure/azure-storage-azcopy#774] opened 2019-12-06 13:54 UTC
### Which version of the AzCopy was used? 
10.3.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Ubuntu on a Azure VM with standard HDD
### What command did you run?
`azcopy sync PATH BLOBPATH_WITH_SAS --delete-destination=true --put-md5`
### What problem was encountered?
The Azure VM was shut down because the osdisk IOPS limit was reached. The azcopy executable is on the osdisk and the data on the datadisk. 

Values received from azure support:

We also see the IOPS limit both on the OS and Data disk is been throttled during the mentioned time . 

> Below are the values for your reference :
>  
> OS disk :
> Read IOPS: 730 (!!!)
> Write IOPS : 82
>  
> Data disk :
> Read IOPS: 530
> Write IOPS : 350

The weird thing is that it is the osdisk that got the VM shut down. Can this be related to the logs (would be weird since it was read IOPS that was the highest). Are there any other read operations that could cause this?
Is there a way we could throttle the IOPS to stay below the limit?

### How can we reproduce the problem in the simplest way?
Check IOPS when running azcopy sync.

### Have you found a mitigation/solution?
Not yet. We used blobxfer to do the copy.

Thanks a lot for your help and insights

**Comment by zezha-msft** [comment] 2019-12-06 22:20
Hi @EvertEt, thanks for reaching out!

Could you please tell us a bit more about the VM that you are using? Which SKU is it? And what kind of disk?

Could you please also elaborate on the data size that you are transferring? How many files were there?

AzCopy does keep track of transfers with a set of job plan files stored under $HOME/.azcopy by default, but 730 IOPS is excessively high, so I'm not sure what caused the high disk usage. Btw was anything else running at the same time? Was AzCopy the only tool that was accessing the OS disk?

**Comment by EvertEt** [comment] 2019-12-06 23:21
The VM was a NC6 with a 60 GiB Standard HDD OSDisk and a 500 GiB Standard HDD datadisk.
The folder copied contains `40,211 blobs; 89,135,360,201 bytes`. It contains some large files (Up to 9GB and smaller ones of a few KBs)

I do believe AZCopy was the only process running. As the VM restarted, our job also restarted, so it kept happening as well.

**Comment by JohnRusk** [comment] 2019-12-08 20:01
@EvertEt  I asked around in the High Performance Compute team (where VMs like the NC6 are often used). No-one seems to have heard of us ever shutting down any VM due to high IOPS.   What indications do you have that that was the reason why your VM shut down?

BTW, even if the shutdown was caused by something else, we still have the mystery of why the 730 read IOPS were happening.  But it would be good to understand more about why the shutdown is believed to relate to the IOPS.

**Comment by EvertEt** [comment] 2019-12-08 20:08
Thanks for the effort you are putting into this!

> What indications do you have that that was the reason why your VM shut down?

Since in our live logs we can see it shuts down during AZCopy transfer.

>  But it would be good to understand more about why the shutdown is believed to relate to the IOPS.

This is what azure support told me, and we can see the following health event:

> We're sorry, your virtual machine is unavailable because of connectivity loss to the remote disk. An unexpected problem is preventing us from automatically recovering your virtual machine.

Where the diagnostics returned the following (like support confirmed):

> This unexpected occurrence was caused by an Azure initiated VM shutdown triggered by detection of temporary IO transaction timeouts between the physical host node where your VM was running, and the Azure Storage services where your Virtual Hard Disks (VHDs) reside.

**Comment by JohnRusk** [comment] 2019-12-08 20:16
Hmm. Interesting.  Technically, "timeouts" don't sound exactly the same as "we shut it down because of high IOPS", but I guess the assumption is that the high IOPS were the cause of the timeout. Ze and I might have to look into that a bit more.

I've been unable to figure out why AzCopy would have that many read IOPS. How sure are out that no other app was generating read IOPS at the time?

Finally, the problem is reproducible, right?  If so, you can do an experiment if you want: set the environment variables AZCOPY_LOG_LOCATION and AZCOPY_JOB_PLAN_LOCATION to point to a different drive, then run it again, and see if this time that high IOPS are reported on the new drive.

One last question: which version of Ubuntu were you using?

**Comment by JohnRusk** [comment] 2019-12-08 20:19
Update: yes, the shutdown from high IOPS situation is documented

>VMs might be temporarily shut down when I/O requests are consistently throttled because the volume of I/O operations per second (IOPS) exceeds the I/O limits for the disk. (Standard disk storage is limited to 500 IOPS.) 

https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/understand-vm-reboot

This is the first time we've ever seen it affect AzCopy, and there's been a lot of AzCopy usage!  Which makes we wonder, again, if something else caused those IOPS.

**Comment by EvertEt** [comment] 2019-12-08 20:20
99% percent sure. We have a single python script running that calls AZCopy at the end. Only something from the machine or ubuntu itself would be running at the same time.

The experiment sounds like a good plan, but sadly we don't have time to reproduce at the moment since we are quite busy.

Ubuntu version is 18.04-LTS.

**Comment by EvertEt** [comment] 2019-12-08 20:23
>This is the first time we've ever seen it affect AzCopy, and there's been a lot of AzCopy usage! Which makes we wonder, again, if something else caused those IOPS.

We have also been using AZCopy for lots of different payloads so it might be very case specific indeed. We assume it is the first time but since the VM just restarts silently we are not actually sure

**Comment by JohnRusk** [comment] 2019-12-08 20:26
Thanks for the info.  I'm not exactly sure where we should go from here on this issue. I'll discuss with @zezha-msft tomorrow.

**Comment by zezha-msft** [comment] 2019-12-10 23:05
I propose to wait to hear more feedbacks (perhaps keep this issue open and see if anyone else encounters it), and decide on the action to take. It's important to confirm that it wasn't a fluke.

**Closed** 2023-12-20 16:21 UTC
Labels: feature request
