### ISSUE TITLE
Failed to download a file with 'Final Job Status: Failed'

### ISSUE THREAD

**Issue by gmson** [Azure/azure-storage-azcopy#733] opened 2019-11-10 15:58 UTC
### Which version of the AzCopy was used?
AzCopy 10.3.1

### Which platform are you using?
Linux

### What command did you run?
`./azcopy copy 'https://<my-storage-account-name>.blob.core.windows.net/mag-2019-10-03/advanced/PaperFieldsOfStudy.txt?<SAS>' './mag-2019-10-03/advanced/PaperFieldsOfStudy.txt'`

### What problem was encountered?
```
0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,
...
15.1 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,
100.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total,
100.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 
100.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total,
100.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 

Job 654c0ac6-f6a5-0741-579f-ae191d2b617d summary
Elapsed Time (Minutes): 15.7033
Total Number Of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

```

Despite the fail message, 'PaperFieldsOfStudy.txt' was downloaded.
But I found the file is not normal.
(When I opened the file with pandas, the number of elements is much lower than what I expected.)

The size of 'PaperFieldsOfStudy.txt' is 37.8GB.
When I tried the same command with other files whose size are much smaller than this, they are downloaded successfully.

### How can we reproduce the problem in the simplest way?
- Try to download a large-scale file.

### Have you found a mitigation/solution?
- No

**Comment by JohnRusk** [comment] 2019-11-10 19:13
Hi @gmson .  The reason for the failure should be in the log.  You can find it by using the instructions here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#troubleshoot-issues 

Maybe that log entry will be enough info to allow you to solve the problem. if not, please share the log entry here.  

In fact, I'd be interested to see the whole log since there are actually two errors here.  One is that it failed to download the whole file, and the other is that it should have then deleted the partially downloaded file (but it didn't).  I'm interested to see if the log sheds any light no the second issue. 
 So, if you like, you're welcome to email me the log and I'll take a look.  Please zip or gzip it. My email address is on my profile page.

**Comment by JohnRusk** [comment] 2019-11-11 06:41
Thanks for sending the log, @gmson.  There are a lot of connection refused errors, and other network errors.  We have seen a few cases where, if AzCopy is run on a powerful machine it will default to using lots of connections - and some networks don't like that.  I'd suggest that you set the environment variable AZCOPY_CONCURRENCY_VALUE to AUTO.  On Linux, you can do it like this:

```
AZCOPY_CONCURRENCY_VALUE="AUTO" ./azcopy copy ...
```
(the rest of the parameters go where I wrote ...)

Please let me know if that solves the problem for you. (We are thinking about maybe making this setting, or something like it, into the default in a future release).

**Comment by JohnRusk** [comment] 2019-11-11 06:41
BTW, when using AUTO like that, you'll see a few extra messages on screen, as it tells you how many connection it is using, while it seeks to find the optimal number.

**Comment by JohnRusk** [comment] 2019-11-11 06:43
Oh, I don't yet know why it failed to delete the destination file after the failure. As I mentioned, it should have done that, but it didn't.  I'll investigate that and see if I can find a reason.

**Comment by JohnRusk** [comment] 2019-11-11 08:14
@gmson Did you open the file before AzCopy failed?  That might explain why it didn't delete it (because something else had it open).

**Comment by gmson** [comment] 2019-11-11 13:16
Thanks, I succesfully downloaded it.

> @gmson Did you open the file before AzCopy failed? That might explain why it didn't delete it (because something else had it open).

I didn't.
I have downloaded many files with some failures and I don't know which file is a 'failed file'
So how can I distinguish the failed files to redownload?
And will I be charged for redownloading the failed files?

**Comment by JohnRusk** [comment] 2019-11-11 19:22
>I have downloaded many files with some failures and I don't know which file is a 'failed file'

AIl the runs of AzCopy save logs to $HOME$\.azcopy .  You can find all failures by searching those logs for DOWNLOADFAILED.  It should be possible to do a Grep search of the whole log directory in just one command.

Notes on searching for failures are here: 
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#troubleshoot-issues

>And will I be charged for redownloading the failed files?
You will be, I'm sorry.  Hopefully it won't be much.  You can estimate it by looking up the egress cost per GB and multiplying it by the number of GB you estimate that you downloaded.

I'm sorry for the problems you've had.  If there are any more questions, please ask.

**Comment by JohnRusk** [comment] 2019-11-12 03:10
Regarding the issue of the file not being deleted, here are a few notes for future reference within the dev team:

* I've tried various ways to reproduce the issue. (E.g. simulating errors in a variety of ways).  None reproduced the issue.  One thing I wasn't able to simulate was dial failures inside the the RetryReader's reconnect method, and that's something that I do see in the logs.  But I can't see how that could cause the deletion to fail.
* The logs record that the transfer was done with ` TransfersDone=1 of 1`.  That implies that the download epilogue ran to completion (because that's the only place that could be marking the transfer as done).
* That in turn implies that the portion of the epilogue that does cleanup ran, at least to the the start of this block:
```
if jptm.IsDeadInflight() && jptm.HoldsDestinationLock() {
			// the file created locally should be deleted
			tryDeleteFile(info, jptm)
}
```
* If either element of that boolean was false, then it would not attempt the deletion. But having looked into it, I can't see any way that either could have been false. [But maybe I'm wrong. That's one possible explanation]
* That implies that deletion was called.
* But no deletion error was returned (otherwise that too would have been logged)
* So the the deletion call must have returned no error. This can happen if there are other handles open to the file.  (The file eventually vanishes when the last handle is closed). However, @gmson has indicated above that no other apps had the file open.

So we have no good explanation of why the deletion failed.  Version 10.3.2 will include a little extra logging in the epilogue code.  So if the issue is reported again with that version, we'll be able to narrow in more closely on what's happening.  We can't see any other actions to take right now.  Just need to see if the problem is reported again with 10.3.2 once that version is out.

**Comment by JohnRusk** [comment] 2019-11-12 03:13
As for the other issue - the repeated network failures - we'll consider that resolved by the use of AUTO concurrency level.

**Comment by nakulkar-msft** [comment] 2022-02-22 08:24
Closing this for we've not been able to repro this. Please reopen this or file a new issue if you see this again.

**Closed by nakulkar-msft** 2022-02-22 08:24 UTC
Labels: needs-reproduction-in-new-version
