### ISSUE TITLE
azcopy copy symlink

### ISSUE THREAD

**Issue by hieuhoang** [Azure/azure-storage-azcopy#1279] opened 2020-12-13 19:57 UTC
### Which version of the AzCopy was used? 
azcopy 10.7.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 20.04

### What command did you run?
azcopy cp  "https://hieustorage2.blob.core.windows.net/hieublob2/"    "https://hieustoreeu.blob.core.windows.net/hieublob2/" --recursive

### What problem was encountered?
Symlinks are created as a text file containing the link

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment] 2020-12-23 10:16
Hi @hieuhoang, thanks for reaching out!

The blob service does not support symbolic links, so I'm inferring that you are storing symbolic links as blobs that contain only the link?

**Comment by hieuhoang** [comment] 2020-12-23 19:29
Yes, that's how blobfuse (v. 1.3.6) create symlinks

**Comment by hieuhoang** [comment] 2020-12-26 08:01
fyi, here's a minimal example to reproduce the problem:
$ mkdir temp
$ echo content of file > temp/file
$ ln -s file temp/link
$ cat temp/file temp/link
content of file
content of file
$ azcopy sync "https://hieustorage2.blob.core.windows.net/hieublob2/hieu/temp"  "https://hieustorage2.blob.core.windows.net/hieublob2/hieu/temp.bak"
$ cat temp.bak/file temp.bak/link
content of file
file

**Comment by zezha-msft** [comment] 2021-01-20 01:50
Hi @hieuhoang, thanks for the info!

Could you please clarify the desired behavior? It sounds like you want blobfuse to recreate the symbolic link?

**Comment by hieuhoang** [comment] 2021-01-20 03:21
yep, azcopy is not creating a faithful copy at the moment.

**Comment by zezha-msft** [comment] 2021-01-20 21:50
Ok I see. I've reached out to my colleague who works on Blobfuse to help determine where the problem is.

**Comment by hieuhoang** [comment] 2021-01-20 22:48
thanks, let me know if I can help in some way. I'm also MSFT

**Comment by NaraVen** [comment] 2021-01-21 04:55
Thanks @zezha-msft  for bringing this to my attention.
@hieuhoang ,this is a feature. The reason blobfuse only copies the link is our users want the symlink preserved. When you upload a symlink through Azure portal it uploads the contents of the linked file and does not preserve the link. Blobfuse is a virtual file driver and our users use symlinks so that the contents of the file can change they want the contents dynamic, in short, it is not a storage unit so it needs to preserve the link. If you want to show the linked file you need to mount the copied storage account again in blobfuse and make sure the link path exists. It may be better to use relative paths so that even if you copy to another storage account the linked path works.

**Comment by hieuhoang** [comment] 2021-01-21 07:09
Hi Nara, 

Thanks for getting back to me.

I think you've misunderstood the issue. I am not using the Azure portal to upload a link.

I am using azcopy to try to copy the symlink but it creates a text file, not the symlink.

Yes, the symlink is a relative path, as you can see from the example. And yes, the link path does exist

**Comment by hieuhoang** [comment] 2021-01-21 08:43
ie. the link is not copied, it is converted into a text file

**Comment by NaraVen** [comment] 2021-01-21 09:30
@hieuhoang , I understood that you did not use Azure portal., and are using AZCopy . I was just using that as an example to say Blobfuse treats symlinks as a symlink file and will not copy the contents of the file. The symlink file created by blobfuse will be considered a symlink file only by Blobfuse. Any other tool will interpret it as a file whose contents is the link. So you cannot create a symlink and upload it using Blbofuse and expect it to work as an link if you don't remount it as a Blobfuse file system.

**Comment by zezha-msft** [comment] 2021-01-21 09:34
In other words, will the copied link (currently just a file whose content is the linked file's location) start working as a symbolic link once the file system is remounted?

**Comment by NaraVen** [comment] 2021-01-21 09:37
yes when you mount it in blobfuse, it will be a symlink again.

**Comment by hieuhoang** [comment] 2021-01-21 09:38
thanks guys for your reply. I've just tried umounting and remounting. It does NOT recognize the symlink.

You should try to verify it yourself

**Comment by hieuhoang** [comment] 2021-01-21 09:39
I'm using blobfuse 1.3.6 if that helps

**Comment by NaraVen** [comment] 2021-01-21 09:50
@hieuhoang could you goto storage explorer or whichever tool you are using and verify if the metadata ( some tools call it user_property) contains is_symlink=true?  If it does not then AZCopy is not copying metadata and @zezha-msft should be able to help. I tested with my tiny copy utility to another storage account and it works. I specifically copy the metadata though.

**Comment by hieuhoang** [comment] 2021-01-21 10:13
good point. I've check the metadata for the source and target symlink files, they both have is_symlink=true.

I've also tried remounting the blobfuse file system but the problem persists.

If you are using your own utility to copy then it be doing something that azcopy isn't doing. Can you please try with azcopy to confirm

**Comment by NaraVen** [comment] 2021-01-21 10:28
sure, I will try with AZCopy but not immediately. It will take some time. After you mount the target in blobfuse what does ls -al in the directory containing the target symlink file show? Does it start with an 'l' like this below example of symlink copy?
 **lrwxrwx---** 1 nara nara     57 Jan 21 01:46 'symlinkfile (1).yml' -> /home/nara/NaraVen/azure-storage-fuse/azure-pipelines.yml

or does it start with a - **"-rwxrwx---"**

**Comment by hieuhoang** [comment] 2021-01-21 10:30
$ ls -l link
-rwxrwxrwx 1 hihoan hihoan 4 Jan 21 01:59 link

**Comment by hieuhoang** [comment] 2021-01-21 10:54
i think i've spotted the problem. The key for the original file is 
  is_symlink
the key for the target file is
   Is_symlink
That seems to be an azcopy bug in copying the metadata.

**Comment by hieuhoang** [comment] 2021-01-21 10:56
only found it using the properties page on the azure website, doesn't show when using Storage Explorer

**Comment by zezha-msft** [comment] 2021-01-21 22:50
Thanks @hieuhoang for the insightful observation!

@NaraVen we can't do anything about the casing unfortunately. The Golang http client changes the casing of headers before we could intercept the raw values. The solution may be for blobfuse to check the metadata value in a case insensitive way. Please let me know if that makes sense.

**Comment by hieuhoang** [comment] 2021-01-22 03:33
hmm ok. I'll wait for you or @NaraVen to escalate it with the blobfuse team. At the moment, azcopy does not faithfully copy

**Comment by hieuhoang** [comment] 2021-01-22 04:07
ah, you were talking to Nara. I'll get out of your way. Please let me know when you have a solution

**Comment by zezha-msft** [comment] 2021-01-22 07:50
No worries! 

We've talked to the Go language team about this problem in the past, but unfortunately we didn't get a lot of traction on them providing a mechanism for us to fix this. So we have to live with this limitation for now.

**Comment by NaraVen** [comment] 2021-01-22 08:29
We will change it in the blobfuse source code by the end of this week. However we will be releasing 1.3.7 only next month.

**Comment by zezha-msft** [comment] 2021-01-22 08:31
@NaraVen Awesome! I'll close this issue then.

@hieuhoang please watch the upcoming blobfuse.

**Closed by zezha-msft** 2021-01-22 08:31 UTC
Labels: need more info

**Comment by hieuhoang** [comment] 2021-01-22 21:28
great thanks

**Comment by hieuhoang** [comment] 2021-01-22 21:45
@zezha-msft my 2 cent - the http header field names are case-insensitive, and some of them have special meanings:
    https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
If you're using them to send metadata then perhaps it would be better to format it like
   Bobfuse-Header: is_symlink=true
 rather than
     is_symlink: true
 which i assume that's what you're doing

**Comment by zezha-msft** [comment] 2021-01-22 21:56
@hieuhoang that's a good idea, and our plan for the future of metadata is along the same line: use the header value to store both the metadata key and value. However, this is an implementation that we hope the service could standardize so that all the tools out there could use. They are aware of this problem and should have plans for it.

I like your idea, but I think there may be a backward compatibility issue for blobfuse, namely the existing clients all have their links stored with is_symlink: true. It's up to @NaraVen but I think we should avoid breaking existing users and have blobfuse be more tolerant on the casing.

**Comment by NaraVen** [comment] 2021-01-23 00:58
for now we will leave it at is_symlink itself for the reason that @zezha-msft has mentioned above. Symlink maybe added to storage in future we will go back and comb our headers then.

**Comment by hieuhoang** [comment] 2021-05-05 01:18
just upgraded to 1.3.7 and looks like it's working. Thanks all
