### ISSUE TITLE
Basic telemetry needed - data transferred / progress / %-complete.

### ISSUE THREAD

**Issue by cloudguy23** [Azure/azure-storage-azcopy#124] opened 2018-11-15 17:03 UTC
### Which version of the AzCopy was used? 
10.0.4 preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux - CentOS 7.5

### What command did you run?
./azcopy cp "${SOURCE}" "${TARGET}"

### What problem was encountered?
No status / telemetry beyond in progress 2-sec average of throughput.   Would be great to have a progress % for sync operation or even data transferred (MB/GB/TB/etc).   

### How can we reproduce the problem in the simplest way?
Run as is.

### Have you found a mitigation/solution?
No.

**Comment by zezha-msft** [comment] 2018-12-12 20:11
Hi @cloudguy23, thanks for reaching out!

I've logged your suggestion and will discuss with the Team on how to improve progress status.

**Comment by artemuwka** [comment] 2019-04-02 04:47
Thank you for taking the time to share your product and documentation feedback with us. Your input is valued and helps us create the right documentation for our customers. Due to the volume of issues in our queue, our policy is to close issues that have been inactive for the last 90 days. We hope to continue hearing from you. Thank you.

**Comment by artemuwka** [comment] 2019-04-02 04:47
#please-close

**Comment by IzuruSenokuchi** [comment] 2019-05-08 02:16
I also want similar features.
I want to get the current progress of any jobID with the jobs show command.

**Comment by JohnRusk** [comment] 2019-05-08 04:38
@IzuruSenokuchi Which would be most useful to you
1. Something like percentage complete (i.e. percentage of the total data volume that has been transferred) OR
2. Something exactly like the end-of-job summary, which shows progress as the number of files that have been transferred.  (As you requested in #371 )

**Comment by IzuruSenokuchi** [comment] 2019-05-08 06:56
Hi @JohnRusk Thank you for confirmation.
What I want to use is the second solution you presented.
It is very useful if the return value of "summary" can be confirmed by calling ("ex. TotalTransfers, TransfersCompleted, etc ...") by calling ". \ Azcopy jobs show <job-id>".

**Comment by JohnRusk** [comment] 2019-05-08 08:18
@IzuruSenokuchi  Thanks. That's a good idea and I can see how it would be useful. We'll track that under #371.

**Comment by JohnRusk** [comment] 2019-05-08 08:21
@cloudguy23 This issue remains on our backlog to be done.  It didn't make the cut for our recent GA release, but we agree that it's important and we haven't forgotten about it!

**Comment by JohnRusk** [comment] 2019-07-23 01:14
Note: #371 covers getting the progress of other running jobs, using `AzCopy jobs show`.

This issue covers a % complete indicator.

**Comment by JohnRusk** [comment] 2019-07-31 03:25
This actually looks like a duplicate of #500 
In any case, the code is now review #525

**Comment by JohnRusk** [comment] 2019-10-11 00:24
Percent complete is now shown, in version 10.3 which is released now. If that's not enough to meet the needs described above, please comment and we'll re-open this issue.

**Closed by JohnRusk** 2019-10-11 00:24 UTC
Labels: feature request
