### ISSUE TITLE
AzCopy says AuthenticationFailed for valid SAS token

### ISSUE THREAD

**Issue by jmistx** [Azure/azure-storage-azcopy#384] opened 2019-05-16 14:00 UTC
##### Note: The version is visible when running AzCopy without any argument
```
azcopy version 10.1.1
```

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux in centos docker container
```
uname -a 
Linux e4c780d4c2d9 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### What command did you run?
```
azcopy cp 'https://mystorage.blob.core.windows.net/container/blob.tar.gz?st=2019-05-16T13%3A18%3A11Z&se=2019-05-17T21%3A18Z&sp=r&spr=https&sv=2018-03-28&sr=b&sig=YPkpmeP0JQFdqX41uMtK4pAARdpPIKWQ3frZCZGkiZ0%3D' /tmp/help7
```
I have replaced account name, container, blob and changed SAS token (but all special characters on theirs places).

### What problem was encountered?
```
INFO: Scanning...
INFO: source is not validated as a single file: AuthenticationFailed, please check if SAS or OAuth is used properly, or source is a public blob
INFO: trying to copy the source as container/directory/list of files

failed to perform copy command due to error: cannot start job due to error: the destination must be an existing directory in this download scenario.
```

but I was able to download file by url from browser without any troubles. 

### How can we reproduce the problem in the simplest way?

get SAS token without seconds in expiration date (--expiry): 
```
#AuthenticationFailed url:
az storage blob generate-sas \
    --output tsv \
    --full-uri \
    --container-name "containername" \
    --name "blob" \
    --permissions "r" \
    --start "2019-05-16T13:18:11Z" \
    --expiry "2019-05-17T21:18Z" \
    --https-only

#good url with SAS
az storage blob generate-sas \
    --output tsv \
    --full-uri \
    --container-name "containername" \
    --name "blob" \
    --permissions "r" \
    --start "2019-05-16T13:18:11Z" \
    --expiry "2019-05-17T21:18:33Z" \
    --https-only
```
I have played with seconds for a while, and always have got problems.

### Have you found a mitigation/solution?
Mitigaton: Set seconds in expiration date

**Comment by adreed-msft** [comment] 2019-05-16 16:25
Hi, jmistx. The SAS token signature is formed using the expiry (which contains the seconds). This may be a more pertinent issue to Azure CLI than AzCopy (though I still don't think they would want to make any changes about it.)

**Comment by jmistx** [comment] 2019-05-16 16:30
It is everything ok with SAS token itself. **I can access** to blob with such token when I am using a `web browser`. **I can download** blob with this SAS using `curl`. But **I cannot** do it using `azcopy`. It is definitely a problem of `azcopy`.

**Comment by JohnRusk** [comment] 2019-05-16 21:06
(Presumed) duplicate of #122

**Comment by zezha-msft** [comment] 2019-06-03 07:00
Indeed a duplicate of #122, will track the issue there instead.

**Closed by zezha-msft** 2019-06-03 07:00 UTC
