### ISSUE TITLE
Copy of a blob from a storage account to same storage account with a different(path_to/) filename fails.  [ panic: close of nil channel ]

### ISSUE THREAD

**Issue by SimonTiz** [Azure/azure-storage-azcopy#2336] opened 2023-08-14 13:14 UTC
azcopy version 10.20.0      & also 10.19.0 
different issue with 10.16.2

Windows 10
In Powershell 5.1

### What command did you run?	 Copy of blob to new name, same storage account.
. "....\AzCopy.exe" cp "https://[anaccount].blob.core.windows.net/test-any/dummy.filenameA?sv=2022-11-02&ss=b&srt=sco&sp=rwdlacyx&se=2024-07-17T10:00:00Z&st=2023-07-21T06:42:38Z&sip=2.56.196.16-2.56.196.28&spr=https&sig=REDACTED" "https://[anaccount].blob.core.windows.net/test-any/dummy.filenameB?sv=2022-11-02&ss=b&srt=sco&sp=rwdlacyx&se=2024-07-17T10:00:00Z&st=2023-07-21T06:42:38Z&sip=2.56.196.16-2.56.196.28&spr=https&sig=REDACTED"

### What problem was encountered?
10.20.0 & 10.19.0   Failed with>>   panic: close of nil channel

_10.16.2 		       Failed with>>   Authentication failed, it is either not correct, or expired, or does not have the correct permission
RESPONSE Status: 403 This request is not authorized to perform this operation_
& yet I have evidence that I did have it working with 10.16.2 a few weeks ago, will try to figure out what different.

### How can we reproduce the problem in the simplest way?
i.e. copy a blob from a storage account to itself with a different(path_to/) filename   , _(SAS authentication)_.

### Have you found a mitigation/solution? - go via intermediate _'location'_
E.g.
$SAS = "sv=2022-11-02&ss=b&srt=sco&sp=rwdlacyx&se=2024-07-17T10:00:00Z&st=2023-07-21T06:42:38Z&sip=2.56.196.16-2.56.196.28&spr=https&sig=REDACTED"
. "....\AzCopy.exe" cp "https://[anaccount].blob.core.windows.net/test-any/dummy.filenameA?$SAS" --from-to="BlobPipe" |
. "....\AzCopy.exe" cp "https://[anaccount].blob.core.windows.net/test-any/dummy.filenameB?$SAS" --from-to="PipeBlob" 

### Comment
The online documentation to wit.  https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json

claims:
[
Copy a single blob to another blob by using a SAS token.

azcopy cp "https://[srcaccount].blob.core.windows.net/[container]/[path/to/blob]?[SAS]" "https://[destaccount].blob.core.windows.net/[container]/[path/to/blob]?[SAS]"
]

and I've not found anywhere that states source and destination storage accounts have to be different.
With lack of Rename capability this issue is a nuisnance, albeit can be worked around but seemingly inefficiently.
If this is a limitation please could the documentation reflect this, else please address ; thanks.

**Comment by SimonTiz** [comment] 2023-08-14 14:20
Okay figured out what different when it was working under 10.16.2.
Then I did not have any  'Allowed IP Addresses'  property on the SAS I was using.
Since then have been using ones with our corporate outbound IP addresses therein, for the most part this have been fine.

However here the more restrictive SAS can be used with the destination, but to get it to work I need to go back to the un-ip-address restricted SAS with the source  (and remember both source and destination are the same storage account/container).  (_then it works on each mentioned AzCopy version_ ).

Is there liable to be an IP address range restriction on the source's SAS that'll work ?    If so how does one figure it out ?
But clearly the preference would be for it to work with the same SAS (with IP restriction) as works for the destination (which === source).

**Comment by gapra-msft** [comment] 2023-08-14 20:09
Hi @SimonTiz, since you are performing a service to service copy, the Azure storage service is fetching the source. Since the IP is not predictable, setting a signed IP will not work in this situation.

When you perform the workaroud, the signed IP field works since you are forcing your machine to fetch the source manually. 

Our recommendation is for you to drop use of signed IP when performing service to service copies. 

Closing this issue now since it is expected behavior. Feel free to follow up if necessary.

**Closed by gapra-msft** 2023-08-14 20:09 UTC
