### ISSUE TITLE
Cannot resume job due to overwrite prompt not accepting any input

### ISSUE THREAD

**Issue by nkarampi** [Azure/azure-storage-azcopy#1506] opened 2021-08-04 11:51 UTC
### Which version of the AzCopy was used? 
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
jobs resume [jobId]
(copy [a] [b] --overwrite=prompt --from-to=LocalBlob --blob-type Detect --follow-symlinks --put-md5 --follow-symlinks --recursive --trusted-microsoft-suffixes= --log-level=INFO)

### What problem was encountered?
When the overwrite prompt is presented  
( [...] Do you wish to overwrite? Please confirm with: [Y] Yes  [N] No  [A] Yes for all  [L] No for all )  
it does not accept any argument. Therefore it cannot resume the job,

### How can we reproduce the problem in the simplest way?
- Start a job
- Stop it
*be sure that some files have been uploaded and the overwrite prompt will be shown*
- Resume the job.

### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment] 2021-08-24 17:55
Howdy! We've got a reproduction. I'll add this to our backlog for next release.

**Comment by tiverma-msft** [comment] 2022-05-10 20:21
I think this is because we haven't enabled the input watcher for jobs resume command.

**Comment by tiverma-msft** [comment] 2022-06-08 20:00
closing this now.

**Comment by nakulkar-msft** [comment] 2022-07-25 00:34
Fixed in 10.16.0.

**Closed by nakulkar-msft** 2022-07-25 00:34 UTC
Labels: bug, fixed-in-dev
