### ISSUE TITLE
Support MSI Login under App Service (incl Kudu)

### ISSUE THREAD

**Issue by vtjon** [Azure/azure-storage-azcopy#831] opened 2020-01-14 16:35 UTC
### Which version of the AzCopy was used? 
V10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows (Azure Kudu via App Service)

### What command did you run?
./azcopy login --identity 

### What problem was encountered?
Failed to perform login command: 
please check whether MSI is enabled on this PC, to enable MSI please refer to https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm#enable-system-assigned-identity-on-an-existing-vm. (Error details: Get http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com: dial tcp 169.254.169.254:80: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.)

NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.

### How can we reproduce the problem in the simplest way?
Copy the EXE to a Windows App Service, go to the Powershell Diagnostic Console (Kudu) and run the command.

### Have you found a mitigation/solution?
It seems that the token IP address is hard coded. I think it needs to look for the MSI_ENDPOINT environment variable. I would be interested in a workaround though.

**Comment by JohnRusk** [comment] 2020-01-14 20:00
Thanks for logging this. Currently, the MSI login uses [a version of the API](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview#how-does-the-managed-identities-for-azure-resources-work) that's appropriate for code running in VMs.  The App Service version has a couple of differences in that it requires a client secret and, as you say , lookup of the endpoint through the environment variable. 

I can't currently think of a workaround for running in an App Service situation. So I've marked this as a feature request (and slightly changed the title, I hope you don't mind.)

**Comment by Uriil** [comment] 2021-05-29 08:59
In my case I want to backup Storage Account using Powershell based Function app and for authentication I want to use Managed Identity and error exactly the same.

I believe root cause is the same.

**Comment by Uriil** [comment] 2021-05-29 15:01
I found workaround, at least it's usable in my case.

You can generate SAS token using MSI, and than you can use SAS inside azcopy command

**Comment by Mike-E-angelo** [comment] 2022-01-14 22:13
This feature would indeed be super handy!  Thank you for any efforts you can make towards implementing it. 🙏

**Comment by yuna-s** [comment] 2022-08-15 02:21
Hi @JohnRusk Is there any update in this feature requests? Thanks

**Comment by JohnRusk** [comment] 2022-08-15 02:34
@yuna-s I have moved to a different team. Perhaps @adreed-msft  can help you.

**Comment by yuna-s** [comment] 2022-08-15 03:31
Hi @adreed-msft, Could you check this feature request? 
App Service has [a their own MSI endpoint](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#connect-to-azure-services-in-app-code), so changing this code in azcopy might help achive this feature.
https://github.com/Azure/azure-storage-azcopy/blob/13fecd4efee985bc1f2cf03fd130fe613ecec375/common/oauthTokenManager.go#L61

**Comment by yuna-s** [comment] 2022-08-17 03:55
@adreed-msft Hope you are doing well. Could you help us for our users? Thanks!

**Comment by adreed-msft** [comment] 2022-08-18 18:37
@zezha-msft feature request

**Comment by vibhansa-msft** [comment] 2023-12-20 16:00
AzCopy login is depricated now you can use "az login" (Az CLI based login) instead. Closing this as anything supported by az cli will be supported by azcopy as well in terms of authentication modes.

**Closed by vibhansa-msft** 2023-12-20 16:00 UTC
Labels: feature request
