### ISSUE TITLE
In linux, single file download with access token does not work

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/azure-storage-azcopy#386] opened 2019-05-17 07:10 UTC
azCopy v10.10

`
var inputFile = "https://xxx/abcde.pdf?sasToken"

//This is working
$@"azcopy copy '{inputFile}' \""$any_linux_folder/\"""

//This is not working
$@"azcopy copy '{inputFile}' \""$any_linux_folder/abcde.pdf\"""
//I got error, that there are multiple files download
//In windows version, it just works
`

**Comment by JohnRusk** [comment] 2019-05-17 07:13
Hmm. That's a surprise. I can't think of any relevant OS-specific code that may create such a difference.  We will investigate it.  Thanks for telling us about it.

**Comment by adreed-msft** [comment] 2019-07-12 15:56
I'm having some trouble reproducing this.

I've tried reproducing with the following source/dest combos:
- Blob -> Local
- File -> Local
- ADLSG2 -> Local

Furthermore, I've tried:
- The source as a variable
- The source as an escaped string
- The destination as a interpolated string
- The destination as a variable

Could you provide us a little more information about your setup to help us reproduce this?

**Comment by andrew-vdb** [comment] 2019-07-13 04:52
I'm not using azcopy anymore at this moment, but the setup, i run it via c# code, Process run, where the commandLine is $@"/bin/bash -c ""azcopy copy '{inputFile}' ""$any_linux_folder/abcde.pdf"""""
It could be also because i use wrong escaping where it should be $@"/bin/bash -c ""azcopy copy '{inputFile}' \""$any_linux_folder/abcde.pdf\"""""

**Comment by adreed-msft** [comment] 2019-09-17 18:34
_out of curiosity_, is there actually a $ in your folder name?

this is seriously low-hanging fruit but this does actually cause a failure on my end if I don't properly escape the $.

**Comment by andrew-vdb** [comment] 2019-09-18 04:25
The $ is environment variable, in this case its working directory of azure batch

https://docs.microsoft.com/en-us/azure/batch/batch-compute-node-environment-variables

![image](https://user-images.githubusercontent.com/12871379/65111107-049d6580-d9db-11e9-9d41-99bda7485dcf.png)

**Comment by adreed-msft** [comment] 2019-09-18 04:31
Is it possible your environment variable has a path separator on the end?

**Comment by adreed-msft** [comment] 2019-09-18 04:36
Actually, even better yet, do you have any logs from a reproduction?

**Comment by andrew-vdb** [comment] 2019-09-18 04:49
I don't use azcopy anymore, it has start performance issue... I think we can close this and wait someone else report it again, is that also ok for you?

**Comment by JohnRusk** [comment] 2019-09-23 03:41
Thanks @andrew-vdb . We'll close this issue now, as you suggest.

By the way, we'd be very interested to hear details of the performance issue that you mentioned.  If you'd like to share details, you can comment here or email me.

**Closed by JohnRusk** 2019-09-23 03:41 UTC

**Comment by andrew-vdb** [comment] 2019-09-23 07:02
https://github.com/Azure/azure-storage-azcopy/issues/414
Its by design (to be slow) according you lol

Not trying to be an ass here, but it seems, slow start in dot net culture is something that acceptable (for the sake of productivity in the past), i thought dot net core change that culture but it seems stick on every other product too (hello azure batch slow start task for example)

ps monday rant

**Comment by JohnRusk** [comment] 2019-09-23 07:25
Oh that ;-)  Where it takes 1.8 seconds instead of the 0.6 that would be expected based on the file size.  Yeah, that's not something that we've optimized for, since we're generally targeting payloads that are a bit bigger than that. (Or at least, bigger relative to the available network bandwidth).  E.g. 10's of seconds, up to 10s of hours (or more)).  We don't get a lot of demand for performance tuning for sub-second payloads.

It sounds like you've found another option there, and that makes sense for your use-case. E.g. one of the Azure SDKs, or even direct REST calls for payloads of that size.

Thanks for your reply @andrew-vdb. 

For anyone else finding this thread, and wondering about startup time for small payloads, using a lower concurrency setting may help (e.g. set the environment variable AZCOPY_CONCURRENCY_VALUE to 8 or less, or in the upcoming version 10.3, to "AUTO").  That can give faster startup on machines with high CPU count, since it won't waste time spinning up workers that it will never use. But, as noted above, sub-second jobs is not something we are currently targeting or optimizing for.
