### ISSUE TITLE
AzCopy v10.18.0 fails to resolve host when the URI contains a port specification

### ISSUE THREAD

**Issue by zigandazag** [Azure/azure-storage-azcopy#2140] opened 2023-04-01 22:35 UTC
### Which version of the AzCopy was used?  
10.18.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
cp $sourceBlob $localPath --recursive=true

### What problem was encountered?
Fails with  host not found if the blob uri includes a port specification like :443

failed to perform copy command due to error: failed to resolve source: lookup xyz.blob.core.windows.net:443: no such host

### How can we reproduce the problem in the simplest way?
try copying from a blob but include a value for a port in the host name eg.
e.g
azcopy  cp https://xyz.blob.core.windows.net:443/release?sv=.. c:\temp

### Have you found a mitigation/solution?
yes remove the port.

**Comment by siminsavani-msft** [comment] 2023-04-03 20:01
Hi @zigandazag , I'm curious to know if this was working in v10.17.0, if you can share that information!

**Comment by zigandazag** [comment] 2023-04-04 05:41
yes it was working in 10.17.0

**Comment by ljelonek** [comment] 2023-04-04 07:12
I can confirm that it was doing fine on 10.17.0. I am currently facing an issue where it is impossible to sync blobs for local storage (emulated one). As you probably imagine, it is hard to ditch ports when syncing on localhost :)

This is kinda blocker for me, thus I will appreciate fast resolution.
Here is a link to the previous version if someone is interested:
https://azcopyvnext.azureedge.net/release20230123/azcopy_windows_amd64_10.17.0.zip

`Cannot perform sync due to error: failed to resolve destination: lookup 127.0.0.1:10000: no such host`

**Comment by siminsavani-msft** [comment] 2023-04-04 20:29
Thanks all for confirming! A fix will be made and this thread will be updated accordingly.

**Comment by siminsavani-msft** [comment] 2023-04-28 19:35
Hi there! The issue has been resolved in the latest version of AzCopy (https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.18.1). Will be closing this issue, but please let us know if you are still experiencing issues!

**Closed by siminsavani-msft** 2023-04-28 19:35 UTC
Labels: bug
