### ISSUE TITLE
AzCopy include filter skips some files

### ISSUE THREAD

**Issue by rugheid** [Azure/azure-storage-azcopy#459] opened 2019-06-24 15:49 UTC
##### Note: The version is visible when running AzCopy without any argument
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy sync <local_folder> https://<storage_account>.blob.core.windows.net/<container>/.?<sas_token> --include="file005.bin;file004.bin;file006.bin;file007.bin;file003.bin;file002.bin;file001.bin;file009.bin;file008.bin" --delete-destination=true`

### What problem was encountered?
Two problems occurred:
1. It uploaded all files except `file005.bin` and `file008.bin`. We tried it several times, it always excluded these specific files. They are valid files on the file system. Trying to upload the files themselves also didn't work. Trying to upload the files to a different container also didn't work.
2. The `--delete-destination` didn't delete anything. Is this because it also takes the include filter into account?

### How can we reproduce the problem in the simplest way?

No idea whether it's easily reproducible. These are the files we tried to upload: [Archive.zip](https://github.com/Azure/azure-storage-azcopy/files/3321585/Archive.zip). They're just binary files with random data.

### Have you found a mitigation/solution?

We haven't found a solution.

**Comment by zezha-msft** [comment] 2019-06-24 22:13
Hi @rugheid, thanks for reaching out!

Unfortunately I wasn't able to reproduce this problem. Could you please double-check with another container?
![image](https://user-images.githubusercontent.com/26559128/60055342-2c0dbc00-9692-11e9-8e0a-ea5733042e43.png)

As for `--delete-destination=true`, it only deletes the extra files at the destination that are not present at the source. Here is a [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) on the sync command. Please don't hesitate if you have any other question.

**Comment by JohnRusk** [comment] 2019-06-24 23:16
Also, @rugheid, it's probably worthwhile for you to double check to see whether the files in question may have been symbolic links.  If that are, that would explain it.  (The copy command can follow links, but does not do so by default.  IIRC sync does not support symbolic links yet)

**Comment by rugheid** [comment] 2019-06-25 07:48
@zezha-msft Thank you for trying it out so quickly! Too bad it's not reproducible indeed, I will try to find a reproducible example. For my own debugging: is it possible to enable a lower logging level to get more insight into what AzCopy is doing?

@JohnRusk I double checked, but the files aren't symbolic links. Thanks for raising the symbolic link difference though, definitely useful information!

**Comment by JohnRusk** [comment] 2019-06-25 09:01
@rugheid One question, what did you mean by "Trying to upload the files themselves also didn't work."  Did you do a test where you put the full path of just one of the files as the source (with no `--include`)?  To help us (and you) figure out what's going on, could you (re)try that test please using `azcopy copy` (instead of sync). I.e. using copy to upload exactly one of the problem files to an empty container.

If that fails, (a) the log will be small and easy to read and (b) there's a reasonably chance that the log will tell you something useful.

**Comment by rugheid** [comment] 2019-06-25 10:22
@JohnRusk That's indeed what I tried. I'll test with `copy` and get back to you with the results! 😄

**Comment by rugheid** [comment] 2019-06-25 10:28
@JohnRusk I tried uploading the files directly without `--include`, but I got this error: `Cannot perform sync due to error: sync must happen between source and destination of the same type: either blob <-> file, or container/virtual directory <-> local directory`.
This was the command: `azcopy sync datatest/file005.bin "https://<storage_account>.blob.core.windows.net/<container>/file005.bin?<sas_token>"`

I then tried uploading that single file using a very simple `--include="file005.bin"`, so without a pattern that has to match a digit, but that didn't work either.

The `copy` you mentioned does work.

**Comment by rugheid** [comment] 2019-06-25 10:34
@JohnRusk What's very weird is that it's now working for me again. After I copied the files using `copy`, I deleted the files and tried the original `sync` command again, which worked. Is there any caching going on in AzCopy locally that might explain this behaviour? Also note that uploading the files manually using Microsoft Azure Storage Explorer did not solve it, so I think the problem is happening locally on my computer alone.

**Comment by JohnRusk** [comment] 2019-06-25 20:21
There is no caching.  To confirm your theory that its local to your computer, can you please look in Storage Explorer. Click on the "Preview" menu, to drop it down (but don't click anything else).  If there's a check mark next to 'Use AzCopy for improved blob upload and download' that means it was using AzCopy and your local machine theory is _not_ confirmed. But if there is no checkmark there, then that means it was not using AzCopy, and your local machine theory IS confirmed.

**Comment by OlivierKamers** [comment] 2019-07-02 08:56
We were able to find the cause of our problem by adding extra logs to azcopy's filter matching.
Something we forgot to mention was that we called this from a Python script using subprocess. The include filter we had in our argument list was `--include="file005.bin;file004.bin;file006.bin;file007.bin;file003.bin;file002.bin;file001.bin;file009.bin;file008.bin"`. 

The problem is then that subprocess will escape the quotes so they become part of the pattern which results in the following include patterns used by azcopy:
`"file005.bin`, `file004.bin`, ..., `file009.bin` and `file008.bin"`. This explains why it skipped file 5 and 8: they were the first and last files in the include string so their patterns included the opening and closing quotes. 

So as this is not a problem with azcopy, this issue can be closed. Thank you for the fast responses and helping us.

**Closed** 2019-07-02 19:05 UTC
