### ISSUE TITLE
Transfers not retried on 'unexpected EOF'

### ISSUE THREAD

**Issue by juve** [Azure/azure-storage-azcopy#436] opened 2019-06-11 17:27 UTC
### Which version of the AzCopy was used? 

10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

`azcopy cp --recursive https://myaccount.blob.core.windows.net/mycontainer ./`

### What problem was encountered?

There were a few dozen failed transfers out of a few thousand that were not retried. They all failed with "unexpected EOF".

### How can we reproduce the problem in the simplest way?

I am not aware of an easy way to reproduce this.

### Have you found a mitigation/solution?

We can get the missing files with `azcopy sync`.

It looks like azcopy only considers `net.Error` to be retryable. It would be nice if `io.ErrUnexpectedEOF` was retryable.

**Comment by adreed-msft** [comment] 2019-06-11 17:31
Hi, @juve. AzCopy failing to transfer to a relative directory destination is a currently known issue and is solved in PR #422. We're currently working on getting it into our next release.

**Comment by juve** [comment] 2019-06-11 17:38
@adreed-msft I don't actually know if the destination in our case was relative or not. Most of the transfers were successful, so it wasn't a complete failure. The error was 'unexpected EOF' in the log, which doesn't seem related to the relative path issue.

**Comment by adreed-msft** [comment] 2019-06-11 17:39
Oh? Interesting. I'll take a look here in a bit.

**Comment by JohnRusk** [comment] 2019-08-06 06:19
@adreed-msft Any update on this?  Is it logged in our backlog for investigation?

**Comment by JohnRusk** [comment] 2019-09-19 09:26
BTW, I've been corresponding, via MSFT internal channels, with staff supporting a customer where this has happened.  Seems to be something in the network path (e.g. a proxy) truncating _something_.  Still in dialogue to try to figure out what is being truncated (there are two or there possibilities).

**Comment by JohnRusk** [comment] 2019-11-15 02:35
The only thing I found in the other support case was that it was almost certainly caused by a proxy server.

@juve Are you still seeing this error with more recent versions of AzCopy?

**Comment by guri-s** [comment] 2019-11-25 01:12
I am getting this error with 
azcopy version 10.3.2

`2019/11/22 02:16:27 INFO: [P#11-T#5479] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: unexpected EOF.`

azcopy version 10.3.2

**Comment by JohnRusk** [comment] 2019-11-25 01:15
We've recently found that there's a bug, in which AzCopy should retry the operation, but for this specific type of failure, it does not.  I don't have a release date for any fix yet, but if you choose "watch" on this page https://github.com/Azure/azure-storage-azcopy/releases you'll be notified of all releases.

**Comment by JohnRusk** [comment] 2019-12-10 19:36
Had to move this out of release 10.3.3. and into 10.4.0, because the necessary change is bigger than expected, including changes to the blob and Azure Files SDKs in addition to AzCopy itself.

**Comment by sjuratov** [comment] 2020-07-01 09:07
Has this issue been resolved? I don't see it documented @ https://github.com/Azure/azure-storage-azcopy/releases

I am trying to copy big file (100GB) from Azure blob storage account to VM in Azure. There is a proxy in between. Copy starts but then it errors out after some time (always less then 20% completed). In log I can see following:

**2020/07/01 06:50:43 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: unexpected EOF. Offset: 20792950784  Count: 2408448 URL: https://<path to blob> 06:50:43 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: context canceled. Offset: 20112736256  Count: 3145728 URL: https://<path to blob> 06:50:43 ERR: [P#0-T#0] DOWNLOADFAILED: https://<path to blob> : 000 : unexpected EOF. When Enqueuing chunk. X-Ms-Request-Id: 

Dst: %5C%5C?\E:\temp\<file name>**

Command I am executing:
azcopy copy https://<path to blob> e:\temp

Azcopy version is azcopy_windows_amd64_10.4.3

**Comment by AtillaTv8** [comment] 2020-07-06 16:37
> Has this issue been resolved? I don't see it documented @ https://github.com/Azure/azure-storage-azcopy/releases
> 
> I am trying to copy big file (100GB) from Azure blob storage account to VM in Azure. There is a proxy in between. Copy starts but then it errors out after some time (always less then 20% completed). In log I can see following:
> 
> **2020/07/01 06:50:43 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: unexpected EOF. Offset: 20792950784 Count: 2408448 URL: https:// 06:50:43 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: context canceled. Offset: 20112736256 Count: 3145728 URL: https:// 06:50:43 ERR: [P#0-T#0] DOWNLOADFAILED: https:// : 000 : unexpected EOF. When Enqueuing chunk. X-Ms-Request-Id:
> 
> Dst: %5C%5C?\E:\temp<file name>**
> 
> Command I am executing:
> azcopy copy https:// e:\temp
> 
> Azcopy version is azcopy_windows_amd64_10.4.3

hello sjuratov, did you solve the problem? I encountered the same problem. 
I cannot download more than 20% for large files. Installed Storage explorer latest version 1.14.0 problem not solved. 
Best regards

**Comment by sjuratov** [comment] 2020-07-06 17:30
No, this is still an issue.

@adreed-msft , @JohnRusk can you comment on plans for this issue to be resolved? I see it's been pushed for 10.5.0. Is this target still valid?

**Comment by zezha-msft** [comment] 2020-07-07 00:01
Hi @sjuratov @AtillaTv8, this issue was fixed in #859, and will be released shortly in 10.5.

**Comment by AtillaTv8** [comment] 2020-07-07 08:18
> Hi @sjuratov @AtillaTv8, this issue was fixed in #859, and will be released shortly in 10.5.

Hi @zezha-msft 
Thank you for the information.

**Closed** 2020-12-02 05:24 UTC
