### ISSUE TITLE
AZCopy hangs under Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by barry-at-technome-io** [Azure/azure-storage-azcopy#599] opened 2019-09-19 08:17 UTC
##### Note: The version is visible when running AzCopy without any argument
azcopy_linux_amd64_10.0.8
### Which platform are you using? (ex: Windows, Mac, Linux)
Debian GNU/Linux 9 (stretch) under WSL 17134.950
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
copy https://container.blob.core.windows.net/path/L008_001.R1.fastq.gz?REDACTED ./downloads/path/L008_001.R1.fastq.gz

### What problem was encountered?
When specifying relative path "downloads" without a dot slash:  AZCopy prints Scanning and shows nothing, AZCopy consumes 30% more CPU and does nothing. After killing the process, CPU is returned and no files were started or queued

When specifying relative path "./downloads" with a dot slash as above:  AZCopy prints Scanning, creates a Job that does nothing, logs show pending job but does nothing, consumes 30% more CPU and does nothing. After killing the process, CPU is returned and no files were started or queued

### How can we reproduce the problem in the simplest way?
run the out-of-the-box copy operation under WSL environment (as specified in https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)

### Have you found a mitigation/solution?
run the same script and sequence of steps under Debian GNU/Linux 9 (stretch) in a Google cloud VM with no issues

run the same file request using AZCopy embedded in Azure Storage Explorer

**Comment by JohnRusk** [comment] 2019-09-19 08:40
Thanks for the bug report @barry-at-technome-io.  We are currently putting the finishing touches on a re-write of the directory handling logic, which should (in theory) fix up inconsistencies like the one you report where it acts slightly differently depending on how the path is specified.

As for the 30% CPU issue, we'll test that and see if we can reproduce it.   I'm hoping, since you're on quite and old version, that it will turn out to be something that we have already fixed.  But we won't know that until we test with the new release that's currently in development.  (If you want, you can test with version 10.2.1 , which contains a lot of improvements over 10.0.8.  But the up-coming 10.3 will have even more).

**Comment by JohnRusk** [comment] 2019-09-19 08:50
Actually, I think the issue is very probably a known issue. The fix is coming: https://github.com/Azure/azure-storage-azcopy/pull/519 

The fix to the known issue will be released in 10.3.  So I'd suggest you retest in 10.3 (once its released, in a small number of weeks from now), and then comment here to let us know if the problem is resolved.

**Comment by GezHenry** [comment] 2019-10-02 09:19
@JohnRusk Having same issue on Windows Server 2012 R2 (2 CPUs) on VMWare. Details as follows ...
   >SET AZCOPY_SPA_CLIENT_SECRET=
   >AZCOPY LOGIN --service-principal --application-id  --tenant-id=
**returns**
   >Failed to perform login command: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/e1nnnn-nnnnn-nnnn-nnnn-nnnnn/oauth2/token?api-version=1.0: dial tcp 40.126.1.166:443: i/o timeout'

**Windows Event Viewer ...** 
==> REQUEST/RESPONSE (Try=1/21.0252026s[SLOW >3s], OpTime=21.0272058s) -- REQUEST ERROR GET https://aka.ms/azcopyv10-version-metadata?timeout=901 User-Agent: [AzCopy/10.2.1 Azure-Storage/0.7 (go1.12; Windows_NT)] X-Ms-Client-Request-Id: [c7499e49-44c3-4766-7307-769f25b98352] X-Ms-Version:

**Comment by JohnRusk** [comment] 2019-10-11 00:07
@barry-at-technome-io Version 10.3 is now released. As noted above, I think if you retest on 10.3 the problems should be gone.  I'll close this thread on that assumption, but if they're not gone please comment and we'll reopen.

**Closed by JohnRusk** 2019-10-11 00:07 UTC
