### ISSUE TITLE
Azcopy 10.1.1 Resume issue

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-storage-azcopy#373] opened 2019-05-08 19:47 UTC
### Which version of the AzCopy was used?
10.1.1 
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
.\azcopy jobs resume $JobId

### What problem was encountered?
I am uploading my files Azure-Data Lake Store Gen2 under File Systems, When i run my job initially i have for example in Folder Src_Files i have another folder called REF - this is my File system Blob in Azure, job ran successfully and uploaded all the files to Azure Data Lake Store Gen2(File Systems). Then I have added two files outside of the REF folder then job failed as expected. After that i deleted two files that i have added and I tried resume job using the .\azcopy jobs resume $JobId(with proper JobId) it still fails with an error it could not find two files that i deleted.  I am not understanding what is the use of resume in this case.

Error Description:
could not check file existence. -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:159
validation failed: parameter=filesystem constraint=Pattern value="New Text Document_2.txt" details: value doesn't match pattern ^[$a-z0-9][-a-z0-9]{1,61}[a-z0-9]$
### How can we reproduce the problem in the simplest way?
It's easy to re-produce

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment] 2019-05-08 20:19
Hi @srini99mkl.  At first glance, the error message seems to relate to the fact that there is a space (two spaces actually) in the name of your file.  That's not a legal file name in blob storage and so, I presume, is also not legal in ADLS Gen 2.  I'll have a chat with the rest of the AzCopy v10 team about how we should handle files with spaces in their names.
Would you be able to repeat your test with files that don't have spaces in their names?

**Comment by srini99mkl** [comment] 2019-05-08 20:37
Hello John Thank you for quick reply.  I have changed file names i.e. removed spaces but it still give the same error. Let me clearly explain you what I am trying to do to test resume operation.  Here is my folder structure on the local machine when I ran my first upload to Gen2.
Src_Files/REF
 under REF folder I have bunch of other folders and files in it.

Step1: I created a Blob container under Data Lake Storage/ File Systems in Azure
Step2: I run      $SourceDirFile $Destination_Azure --recursive=true --overwrite=false                       command to upload, all the folders and files have been uploaded.
Step3: I have two files(New_Text_Document_1.txt and New_Text_Document_2.txt) under Src_Files folder in local machine.
Step3: I run  $SourceDirFile $Destination_Azure --recursive=true --overwrite=false      command again the it failed with        
could not check file existence. -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:159
 validation failed: parameter=filesystem constraint=Pattern value="New_Text_Document_1.txt" details: value doesn't match pattern ^[$a-z0-9][-a-z0-9]{1,61}[a-z0-9]$          
for both files

Step4: Then I deleted files New_Text_Document_1.txt and New_Text_Document_2.txt from Src_Files folder.

Step5: Then I resumed the Job \azcopy jobs resume $JobId   with JobId that has failed earlier, it is still failing with the same error.

**Comment by JohnRusk** [comment] 2019-05-08 20:54
Oh. It looks like our issue goes wider than spaces.  Contrary to my earlier comment (which I have now edited and corrected) blob names can contain any character.... but tools must follow [URL escaping rules](https://en.wikipedia.org/wiki/Percent-encoding) for those characters that are special.  I can't quite tell from your error message whether we have an issue with escaping, or just an issue with some auto-generated validation code that is validating the names against a regular expression that is not quite correct.  

I _think_ the issue you've logged probably only happens with overwrite=false, and only when using ADLS Gen 2.

I'll escalate the priority of the issue. Thanks for logging it with us.

**Comment by JohnRusk** [comment] 2019-05-10 00:44
@srini99mkl We've had a look at this.  Let me answer the issue in two parts:

Firstly, your original question about "what is the purpose of resume in this case". In AzCopy resume means "try again, to transfer all the files that failed last time".  It doesn't re-scan the file system, instead it just reads the job plan files from the previous run, and uses the file information there.  So it's normal that it would try to open a file like New_Text_Document_1.txt, because it was there on the earlier run, even though you have subsequently deleted it.

What should happen, is that that file will fail, but the job as a whole will still continue. Should you in the end-of-job summary display, you should have a failure count equal to the number of files that you deleted.  That's consistent with the design philosophy of AzCopy v10, which is that the job as a whole should continue, even if some files fail.

**Question 1:** Is that what you are seeing, or does the whole program stop running and show an error on-screen?

--

Secondly, the specific error that you reported with "could not check file existence". Two of us on the team here have tried to reproduce that, and we have not been able to. One possible explaination is that, by accident, you've running an older version of AzCopy than planned.  **Question 2: ** Can you run `azCopy --version` to check that it really is version 10.1.1 and lets up know that result?

**Comment by JohnRusk** [comment] 2019-05-12 23:08
@srini99mkl Just checking in with you about the question at the end of my previous comment.  That check of the version number seems like the logic next step. E.g. some older version was somehow on your path, and was getting run by mistake, that could possibly explain why we've been unable to reproduce file name issue.

**Comment by JohnRusk** [comment] 2019-05-13 02:07
@srini99mkl Never mind about checking the version number. I have up update for you, regarding the "could not check file existence error". My colleague @adreed-msft helped narrow it down to filesystem (container) names, we are able to reproduce your error with the sequence of events described below.  Would you be able to take a look please, specifically at how we're specifying filesystem (container) names, and let us know if this also matches what you did.  

My repro works with both blob (where the root level = container) and ADLS Gen 2 (where the root level is called "filesystem").  Here's what I did:

1. Manually created two file systems in my ADLS Gen 2 account.  In my repro, one is called `aardvark` and one is called `bison.`
2. Created a local folder called `D:\testdata\localroot`, with subfolders named `aardvark` and `bison` (same as the filesystem names).
3. Run a command like this: `azcopy cp "d:\testdata\localroot\*" "https:<account>.dfs.core.windows.net  --recursive --overwrite=false`
4. Note that the local path is specified ending with `\*`. 
4. Note also that there is no filesystem/container name in the destination URL. Instead, because the transfer is recursive, the first level of directory names under `localroot` map to the filesystem names.  E.g. files in `localroot\aardvark` are uploaded to `https:<account>.dfs.core.windows.net/aardvark`.  And that all works fine. 
5. But... if you put a _file_ into `localroot` it doesn't really make sense and, if that file has a name that is not a vaild filesystem name, then it gives the exact error message that you reported.

Does that sound like your situation?  If so, we know what was causing your error messages, and I'll see if we can make those messages clearer in the future.

**Comment by srini99mkl** [comment] 2019-05-13 18:57
Thank you, that helped me.  I am running into different issue now. 
Subject: I am trying to test Resume. Here are the steps I am doing.
Step1: Started running AZcopy Job
Step2: After a minute I killed the Job with - Ctrl+c
Step3: When i run the azcopy job show command, it stills shows the Job Status as: InProgress, Here is the message
Job 3dxxxx-xxxxxxxxxx-f345-4ed8-f06e353c1b17 summary
Total Number Of Transfers: 18
Number of Transfers Completed: 5
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
Final Job Status: InProgress

My Question is: This job should have been in Killed or Failed status, Why this is showing as InProgress

**Comment by JohnRusk** [comment] 2019-05-13 19:55
I think the way to think of it is like this:  If the process had been suddenly killed, e.g. you terminated it with Task Manager, we would _expect_ the status to say InProgress.  Why? Because when a process is killed like that, it has no chance to clean up and set any special status. It's just gone.  So in such cases, we need to interpret "InProgress" as meaning "Not finished yet".

Your CTRL-C case is acting the same way. I feel that is reasonable behaviour, since it's consistent with other types of early exit, such as those caused by process termination.

If you feel that we should instead have a special status for terminations due to CTRL-C, please log that as a separate issue. (I'm not sure whether we can, or should, make such a status. But you're welcome to log it for our considration.)

I'm going to close this issue now, since the name-related error is now understood; and the original resume question is answered.

**Closed by JohnRusk** 2019-05-13 19:55 UTC
