### ISSUE TITLE
azcopy fails to copy file with metadata more than 1000 characters

### ISSUE THREAD

**Issue by suvirgupta** [Azure/azure-storage-azcopy#1493] opened 2021-07-13 05:36 UTC
### What command did you run?
azcopy_v10 copy '/mnt/resource/repsxssbt_data/partitions//test/system_test/Z-14-JA-A-APISystem-4835-2021-07-01.tar' 'https://xyz.blob.core.windows.net/649f887b-181d-41fb-8ee6-c93f3a15cbd6/system/transformation/Z-14-JA-A-APISystem-4835-2021-07-01-05-01_.tar?sig=gashgashg' --overwrite=true --metadata='name=Z-14-JA-A-APISystem-4835-2021-07-01-05-01_execution-7755-2021-07-01-42-43_afdhgsafdhf.tar;description=;userDescription=hsxjahs data corresponding to the Output ID: 47beera9d-2c3f-422e-b27a-feadb217de27;catalogueId=3d1wqwb9f-c96c-431c-bcd7-f74122c4813d;typeName=pams_file;location=https://lal-es-wev.lower-abclebv.abcglb.com/api/dal/v1/fileaccess/download/649rdf87b-181d-41fb-8ee6-c93f3a15cbd6/raw/apiclient_zjaaapisystem_271879d41003/transformation/Z-14-JA-A-APISystem-4835-2021-07-01-05-01_execution-7755-2021-07-01-42-43_gkbl-ghardmdS.tar;correlationId=34e933c3-2377-480a-a85e-cf3a5026d21b;classifications={"ownership_type": "client", "xjajsxjhsxvhv": "xasbxsasx", "sxsxssxs": "Full"};territory=asxsax xasxs;registrationSourceSystem=oph;clientDisplayName=soph_testing;sxasxsaxas=USD;sxsaxsaxsaxsas=sxsx xsaxas;testfnadeYearEnd=2017-12-31 00:00:00.000000;testfnadeYearStart=2017-01-01 00:00:00.000000;generalkjdfadSystem=GENERIC-MYSQL;sxasxsxvfvv=4692;minimumghardmdValue=10.0;numberFormat=XXX,XXX.XX;parentEntityName=APIClient_3173_2021-07-01-04-58;periodviewedEnd=2018-12-31 00:00:00.000000;periodviewedStart=2018-01-01 00:00:00.000000;uuid=47b5ee9d-2d3f-429e-b27a-feedb217de27;responses=[{"method": "PUT", "type": "portal", "url": "https://portal-oph-ue-dev.abcinternal.com//api/Integration/ghardmds-execution/88998152-6516-4d73-9be1-9a310c81883a/61381957-9fda-eb11-a7ad-0050f26b281d"}];ophSystemId=271879d4-1003-4820-b2d3-8f9e38aaa87f;ophSystemName=warrsdgaggs|hhgahsgja|jsa;runId=23e2ccf7-22a2-4baf-86bc-8bcc1218c970'
### What problem was encountered?
metadata length cannot be more than 1000 characters
`panic: metadata string is too large:`

### How can we reproduce the problem in the simplest way?
keeping metadata more than 1000 characters

### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment] 2021-07-20 12:03
Hey @suvirgupta 

Thanks for reaching out!
It's because of [this code](https://github.com/Azure/azure-storage-azcopy/blob/87cba068b4cb797fb822163905cf6e92a4ec4db4/ste/JobPartPlan.go#L21)

```go
MetadataMaxBytes     = 1000
...

type JobPartPlanDstBlob struct {
...
Metadata       [MetadataMaxBytes]byte
...
}
```

**Comment by gapra-msft** [comment] 2022-11-21 15:09
Hi @suvirgupta We limit the size of metadata (and other properties) by design to limit the size of the job plan file. Are you able to use any other workaround to limit your metadata size?

**Comment by gapra-msft** [comment] 2022-11-22 17:25
Closing this for now since this is by design. Please feel free to re-open if needed.

**Closed by gapra-msft** 2022-11-22 17:25 UTC
