### ISSUE TITLE
Timezone example in az help text incorrect (for gen SAS tokens)

### ISSUE THREAD

**Issue by rnwolf** [Azure/azure-storage-azcopy#656] opened 2019-10-07 12:26 UTC
The help in az  seems to suggest the an approach to specifying timezones.

```
Examples
    Generate a sas token for blob container and use it to upload a blob.
        end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`

```
I am using the following az version.

```
az --version
azure-cli                         2.0.74
command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3
```

And using AzCopy   10.2.1 on WSL Ubuntu linux

### What command did you run?

I want to use azcopy to transfer files to a static website hosted in blob storage.
See see command in bash script.

### What problem was encountered?

```
1 Files Scanned at Source, 0 Files Scanned at Destination
Cannot perform sync due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:308ebc24-d01e-008d-0206-7d4f1a000000
Time:2019-10-07T11:56:22.4259076Z, Details:
   AuthenticationErrorDetail: se is mandatory. Cannot be empty
   Code: AuthenticationFailed
```

### How can we reproduce the problem in the simplest way?

Replace the XXXXX section in the bash script with values for your setup.
Create a sub folder, source, with a test file in it.

Run the bash file 

### Have you found a mitigation/solution?

It seems that the format used to specify the timezone in the applications or help needs to be aligned.
I have to specify the zone with :00Z  which I think is non-standard.

I found this because the GUI storageexplorer application can be used to generate SAS tokens. And examining the SAS string showed that timeszone info was different to az help text example.

```
#!/usr/bin/env bash
#Assume that you are logged in to az, and are in directory with latest version of linux azcopy
# azcopy version 10.2.1
# Key Azure parameters
RESOURCEGROUPNAME=XXXXX
STOREAGEACCOUNTNAME=XXXXXX   # inside the Storage Account you see "Manage Access Keys" button for Account Name and Keys(Primary and secondary)
CONTAINERNAME=XXXX

# Work out timeframe for token validity
NOW=`date +"%Y-%m-%dT%H:%M%Z"`  # In current timezone
#Ensure that sas token expires in 1 hour from now.
EXPIRY=`date -d "$NOW + 1 hour" +"%Y-%m-%dT%H:%M%Z"`
#Ensure that token was valid earlier in time. 15 min was recommended in docs. Use 1 hr.
NOW=`date -d "$NOW - 1 hour" +"%Y-%m-%dT%H:%M%Z"`
echo $NOW
echo $EXPIRY
#But the help text spec of azcopy says to use UTC = Z so display with letter Z. Spec example seems wrong.  use :00Z as per StorageExplorer
#NOW=`date -u -d "$NOW" +"%Y-%m-%dT%H:%MZ"`
#EXPIRY=`date -u -d "$EXPIRY" +"%Y-%m-%dT%H:%MZ"`
NOW=`date -u -d "$NOW" +"%Y-%m-%dT%H:%M:00Z"`
EXPIRY=`date -u -d "$EXPIRY" +"%Y-%m-%dT%H:%M:00Z"`
echo $NOW
echo $EXPIRY

#Create SAS approach one
echo "Generate SAS approach one"
##generate connection-string
StorageAccountConnectionString=`az storage account show-connection-string --name $STOREAGEACCOUNTNAME --resource-group $RESOURCEGROUPNAME --output tsv`
##generate sas
SAS1=`az storage container generate-sas --connection-string $StorageAccountConnectionString -n $CONTAINERNAME --permissions racwdl --start $NOW --expiry $EXPIRY --output tsv`
echo $SAS1
# Create SAS approach two
echo "Generate SAS approach two"
ACCOUNTKEY=`az storage account keys list -g $RESOURCEGROUPNAME -n $STOREAGEACCOUNTNAME --output tsv | cut -f3 |head -n 1`
SAS2=`az storage container generate-sas --name $CONTAINERNAME --start $NOW --expiry $EXPIRY --permissions racwdl --account-name $STOREAGEACCOUNTNAME --account-key $ACCOUNTKEY --output tsv`
echo $SAS2
# Create SAS approach three
# SAS generated via GUI in StorageExplorer
SAS3="st=2019-10-07T11%3A18%3A00Z&se=2019-10-07T12%3A18%3A00Z&sp=racwdl&sv=2018-03-28&sr=c&sig=XXXXXXXXXXXXXX"
echo $SAS3

## Check that we have some files in the source directory, that we want to sync to azure container
ls $(pwd)/source 

SOURCE=$(pwd)/source
DESTINATION=https://$STOREAGEACCOUNTNAME.blob.core.windows.net/$CONTAINERNAME?$SAS1
# Display variables
echo $SOURCE
echo $DESTINATION
# Sync files
./azcopy sync "$SOURCE" "$DESTINATION" --delete-destination=true

```

**Comment by JohnRusk** [comment] 2019-10-07 20:04
Thanks heaps for the detailed repro steps!  They may be very useful when we work on this.

BTW, I suspect the underyling issue is a duplicate of #122

**Comment by rnwolf** [comment] 2019-10-07 21:20
Yes, they seem to be about the same issue.  I hope the team make the decision to support regular time zone standards. The use of :00Z is not something I have come across beforehand. Documentation might be right and implementation could be extended to include functionality as described. That way the storageexplorer does not need to changed at the same time.On 7 Oct 2019 21:04, "John Rusk [MSFT]" <notifications@github.com> wrote:Thanks heaps for the detailed repro steps!  They may be very useful when we work on this.
BTW, I suspect the underyling issue is a duplicate of #122

**Closed** 2021-09-08 19:31 UTC
