### ISSUE TITLE
"File modified since transfer scheduled" when syncing symlinks

### ISSUE THREAD

**Issue by xuanruiqi** [Azure/azure-storage-azcopy#488] opened 2019-07-07 22:02 UTC
### Which version of the AzCopy was used? 
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Arch Linux

### What command did you run?
`sync /home/xuanrui/arch-repo https://archlinuxxuanruiqi.blob.core.windows.net/$web --recursive`

### What problem was encountered?
Some files failed to sync with the error: `UPLOADFAILED: /home/xuanrui/arch-repo/repo/xuanrui.db.sig : -REDACTED- : File modified since transfer scheduled`. Coincidentally, all of those files were symlinks. All other files synced without problems.

### How can we reproduce the problem in the simplest way?
Create a folder, add a file, make a symlink to it in the same directory, and sync it to a blob.

### Have you found a mitigation/solution?
None yet. I can force copy the files to the blob, but this is more of a non-solution.

**Comment by JohnRusk** [comment] 2019-07-07 22:49
May be related to other symlink issues, so assigned to Adele, so this one can be looked at with those.

**Comment by adreed-msft** [comment] 2019-07-08 16:20
Once I have my Linux environment entirely going, I'll be sure to check these out-- While I'm able to reproduce at least some of them on WSL, it certainly isn't optimal for debugging.

**Comment by adreed-msft** [comment] 2019-07-08 20:11
Strangely enough, I can't seem to reproduce this. I've tried the following arrangements:

Symlinking in the same directory as we're syncing
- `testDir/aaa`
- `testDir/bbb (bbb => aaa)`

Symlinking in a different directory than we're syncing
- `testDir2/ccc`
- `testDir/ddd (ddd => ccc)`

Symlinking to a subdirectory of the one we're syncing
- `testDir/myDir/eee`
- `testDir/fff (fff => myDir/eee)`

I could be misunderstanding your scenario, if so, could you clarify?

**Comment by xuanruiqi** [comment] 2019-07-09 04:24
Hmm, maybe try issuing the command repeatedly? It only began failing for me after a few times.

**Comment by xuanruiqi** [comment] 2019-07-11 07:02
Still failing for me after multiple attempts. `azcopy` is the only way to copy symlinks reliably as I know. BTW, my use case is the 1st: sym-linking in the same directory as we're syncing.

**Comment by xuanruiqi** [comment] 2019-07-11 07:09
I also find that `azcopy copy` isn't following symlinks properly...

**Comment by adreed-msft** [comment] 2019-07-11 15:55
Out of curiosity, for `azcopy copy`, are you using the flag `--follow-symlinks`?

**Comment by adreed-msft** [comment] 2019-07-11 16:18
Furthermore, it seems as though `cmd/sync:520` has a comment saying that we've disabled following symlinks at the moment.

**Comment by adreed-msft** [comment] 2019-07-11 22:53
So, I've been totally incapable of reproducing this, even on a Linux VM. Are you _sure_ there's not some other program using your files?

I may be incorrectly reading your scenario, but are you potentially trying to keep a backup of your dotfiles?

**Comment by adreed-msft** [comment] 2019-07-11 22:58
If so, other programs using the files may actually interfere with LMTs.

**Comment by xuanruiqi** [comment] 2019-07-12 01:27
My file system is Btrfs. Maybe this is actually a Btrfs problem.

**Comment by xuanruiqi** [comment] 2019-07-12 01:29
I am totally sure that no userspace program is using my files, yes.

I didn't know that the `--follow-symlinks` option existed. I'll give it a try. OTOH, is the fact that `azcopy sync` does not correctly copy symlinks probably related to the problem that `azcopy sync` cannot follow symlinks in the first place?

**Comment by xuanruiqi** [comment] 2019-07-12 01:31
I'm using Azure Blob Storage to host a package repository for Arch Linux (https://wiki.archlinux.org/index.php/Unofficial_user_repositories). I put my packages in the `$web` directory and run my repository as a public, static website.

**Comment by fhl13** [comment] 2019-08-06 17:27
I have this same issue. I am copying veeam backup files from a Buffalo Terastation to azure blob using azcopy 10.2.1.

Some files fail immediately every time with the error "File modified since transfer scheduled". The file has not actually been modified.

I am using azcopy on server 2016.

Running "azcopy sync" command.

**Comment by fhl13** [comment] 2019-08-06 18:46
Update:

I built a linux box to access the terastation via nfs.

Currently running azcopy and initially it seems to be working without the "File modified since transfer scheduled" error I was getting when running azcopy on my server 2016 box.

Will post again if this is successful.

**Comment by fhl13** [comment] 2019-08-08 12:19
Using a linux box seems to be a successful workaround at this time.

**Comment by adreed-msft** [comment] 2019-08-08 15:24
The original sync implementation doesn't support following folder symlinks and accidentally enumerates them as files.

Oddly enough, we record the LMT of the symlink itself and check against the LMT of the destination.

**Comment by adreed-msft** [comment] 2019-08-08 15:25
As a part of the copy refactor, I'll modify this enumerator to ignore symlinks outright if follow symlinks is off.

**Comment by JohnRusk** [comment] 2019-08-08 21:49
@adreed-msft 

>we record the LMT of the symlink itself

In cases where followSymlinks = true, will this be fixed by the refactoing too?

**Comment by adreed-msft** [comment] 2019-10-15 19:19
Yes, this has been fixed by the refactoring, and has been released. Enjoy!

**Closed by adreed-msft** 2019-10-15 19:19 UTC
