### ISSUE TITLE
Files with extension ".%22" upload in unexpected way

### ISSUE THREAD

**Issue by markstensgaard** [Azure/azure-storage-azcopy#916] opened 2020-03-19 09:19 UTC
### Which version of the AzCopy was used? 
10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`azcopy cp "C:\Temp\abc\abc.%22" "https://fortesting2.blob.core.windows.net/0000-public/azcopy_pct22_ext_issue/abc/?sv=<SAS>"`

### What problem was encountered?
Files with extension ".%22" are not named correctly when uploaded with AzCopy compared to any other ".%##" files.

### How can we reproduce the problem in the simplest way?
Create some dummy files with names like the following:
abc.%21
abc.%22
abc.%23

Use AzCopy to upload them to Azure blob storage. When using "azcopy list" or viewing them in Azure Storage Explorer, they will appear as:
abc.%21
abc."
abc.%23

The "full" filenames, as seen when using the "Copy URL" button in Storage Explorer, are:
abc.%2521
abc.%22
abc.%2523

This occurs when uploading the file directly or the entire folder with AzCopy. It also occurs when the file is part of a folder being uploaded through Azure Storage Explorer. However, it correctly names the file if the file itself is manually dragged-and-drop into Azure Storage Explorer (my current project has thousands of folders with ".%22" files, so this is not a viable solution).

### Have you found a mitigation/solution?
For my current project, I have renamed all of the ".%22" files to ".%z22", and they upload as expected, but it is very time-consuming for me to modify other input files to my analysis tool to account for the name modifications.

**Comment by JohnRusk** [comment] 2020-03-19 09:21
@adreed-msft Can you take a quick look in the morning please, see what's going on, and let us know?

**Comment by markstensgaard** [comment] 2020-03-30 12:50
Is there anything being done for this? We have received several more projects from our clients that they have uploaded for us using Azure blob storage, and all of the projects have this problem. We are using many hours working around this issue. We would greatly appreciate a fix as soon as possible.

**Comment by JohnRusk** [comment] 2020-03-31 00:15
It might be fixed as a result of changes already in progress for release 10.4. @adreed-msft  is checking

**Comment by markstensgaard** [comment] 2020-03-31 15:37
Hi John. Thank you for your help. We look forward to version 10.4.0. 

Do you know if Azure Storage Explorer will get an update to include AzCopy 10.4.0 when it is released? Most of our clients use Storage Explorer for uploading their data to blob storage.

**Comment by JohnRusk** [comment] 2020-03-31 20:51
>Do you know if Azure Storage Explorer will get an update to include AzCopy 10.4.0 when it is released? 

Probably.  It's not my decision what goes into Storage Explorer, but they usually stay fairly current in terms of the AzCopy version.

**Comment by adreed-msft** [comment] 2020-04-01 21:35
This is _partially_ fixed in 10.4.

However, due to the way we try to preserve the names of objects downloaded to windows, there's no real true fix here, aside from making our safe encoding rules a optional, but default command line flag.

Encoded characters like %2A, %20 are pretty benign, and there's no way to tell whether it was us doing that, or you.

Below is the map of unsafe characters on Windows that we encode to (or decode from) in 10.4

```
var reverseEncodedChars = map[string]rune{
	"%00": 0x00,
	"%3C": '<',
	"%3E": '>',
	"%5C": '\\',
	"%2F": '/',
	"%3A": ':',
	"%22": '"',
	"%7C": '|',
	"%3F": '?',
	"%2A": '*',
}
```

**Comment by adreed-msft** [comment] 2020-04-01 21:46
Correction, it's not actually partially fixed, somehow got it into my head that it was.

**Comment by JohnRusk** [comment] 2020-04-01 21:58
It's probably too late for us to consider a command line flag to control this for version 10.4, but we might be able to do so for 10.5 (release date not announced).  @adreed-msft Can you please add it to the 10.5 backlog.

@markstensgaard If waiting for a fix will cause considerable hardship, please email us. I can't promise anything, but let's discuss.  My email address is in my profile page and I'm guessing @adreed-msft 's is too.

**Comment by mohsha-msft** [comment] 2020-12-12 05:54
Reproduced the issue in v10.8.0

**Comment by susanandwang** [comment] 2021-07-07 14:38
Reproduced the issue in v10.11.0

**Comment by susanandwang** [comment] 2021-07-08 13:44
@JohnRusk . @adreed-msft , may I know whether there are plan to fix this issue? As we still can reproduce it in v10.11.0. Thanks.

**Comment by JohnRusk** [comment] 2021-07-08 20:01
@susanandwang I'm not working on AzCopy these days, but @adreed-msft or @zezha-msft will be able to answer your question.

**Comment by zezha-msft** [comment] 2021-07-09 22:10
@susanandwang please refer to the release note 10.11 here: https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.11.0

The auto decoding on Windows can be disabled with the flag --disable-auto-decoding.

**Closed by zezha-msft** 2021-07-09 22:10 UTC
Labels: bug
