### ISSUE TITLE
Move data to s3

### ISSUE THREAD

**Issue by jinamshah** [Azure/azure-storage-azcopy#1060] opened 2020-06-19 06:20 UTC
### Which version of the AzCopy was used? 
10.4.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
`azcopy copy "https://xxx.blob.core.windows.net/xxx?SASTOKEN" "https://yyyy.s3.amazonaws.com/yyyy/" --recursive=True`
### What problem was encountered?
INFO: Based on the parameters supplied, a valid source-destination combination could not automatically be found. Please check the parameters you supplied.  If they are correct, please specify an exact source and destination type using the --from-to switch. Valid values are two-word phases of the form BlobLocal, LocalBlob etc.  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is not supported yet, please log an issue on the AzCopy GitHub issues list.

when from-to is specified
failed to parse user input due to error: invalid --from-to value specified: "BlobS3". Valid values are two-word phases of the form BlobLocal, LocalBlob etc.  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is not supported yet, please log an issue on the AzCopy GitHub issues list.

### How can we reproduce the problem in the simplest way?
try to copy a container to s3 folder
### Have you found a mitigation/solution?
None

**Comment by adreed-msft** [comment] 2020-06-25 21:24
Hi there, we don't currently support Azure -> S3. Furthermore, this is a duplicate of #348, and I'll be closing the issue now.

**Closed by adreed-msft** 2020-06-25 21:24 UTC
