### ISSUE TITLE
A (genuine) panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SimonTiz** [Azure/azure-storage-azcopy#2317] opened 2023-07-27 06:59 UTC
AzCopy 10.16.2
Windows

in Powershell with relevant $variables.
$target = "https://_????????_.blob.core.windows.net/path/file"

. "$AzCopyExe" cp "$target$SAS" --from-to BlobPipe >"myfilepath"

AzCopy.exe : panic: runtime error: invalid memory address or nil pointer dereference . . .

Is a genuine error message as is caused by (accidental)  NewLine character in the $SAS, ( with the --from-to option), and so easy fix.
However, as I suspect you'd like any error message containing 'Panic', to be otherwise handled, thought I'd report it to you.
Apologies if I'm assuming too much.

p.s. same in 10.19.0

**Comment by siminsavani-msft** [comment] 2023-08-10 16:55
Thank you for reporting this! This is actually the expected behavior.

**Comment by gapra-msft** [comment] 2024-02-12 21:49
Hi @SimonTiz I believe this is no longer an issue since I cannot reproduce this in latest versions of AzCopy. Let us know in case I have closed this issue in error.

**Closed by gapra-msft** 2024-02-12 21:49 UTC
Labels: user experience, user error
