### ISSUE TITLE
100% complete 1 Pending

### ISSUE THREAD

**Issue by danobri** [Azure/azure-storage-azcopy#750] opened 2019-11-18 19:50 UTC
### Which version of the AzCopy was used? 
10.3.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10
### What command did you run?
 .\azcopy cp $source $destination --log-level=ERROR --overwrite=true --recursive=true
### What problem was encountered?
I am running this command on an Azure VM to copy blob containers from one storage account to another.  It works fine, but several times now it has gotten hung, with the progress output reading something like this:

100.0 %, 364456 Done, 0 Failed, 1 Pending, 0 Skipped, 364457 Total 

It seems to continue to retry infinitely, so eventually I kill the process and move on to the next container.  It has happened on multiple containers, and there's never more than one 1 file pending, and everything else is complete.  he message doesn't make sense - if it's 100% complete, how can there be 1 file pending?  

When I look at the associated log file, there appears to be a time out:

   RESPONSE Status: 500 Operation could not be completed within the specified time.
   Content-Length: [245]
   Content-Type: [application/xml]
   Date: [Mon, 18 Nov 2019 18:57:16 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [OperationTimedOut]
   X-Ms-Request-Id: [edc8d2b7-b01e-000d-3741-9e8e04000000]
   X-Ms-Version: [2018-03-28]
Response Details: ﻿<Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time. </Message>

### How can we reproduce the problem in the simplest way?
Not sure.
### Have you found a mitigation/solution?
No - I have just been killing the process and moving on to the next container.  I am keeping track of which containers did not complete, but I have not retried any of them yet.

**Comment by zezha-msft** [comment] 2019-11-18 20:14
Hi @danobri, thanks for reaching out!

There may be a service-side issue impacting this timeout. I'll reach out to the service folks for more information.

As for the progress percentage, it reached 100% because all the bytes have been sent, and it's waiting for the service to respond. 

Could you please also share the request part of the log entry?

**Comment by danobri** [comment] 2019-11-18 21:35
Here is the full log with the URL X'ed out.  What I don't understand is why is it always just 1 file pending?  I re-ran the last container again, and it did the same thing - copied the entire contents, said it was 100% complete, but infinitely pending 1 file...? 

2019/11/18 18:56:20 AzcopyVersion  10.3.2
2019/11/18 18:56:20 OS-Environment  windows
2019/11/18 18:56:20 OS-Architecture  amd64
2019/11/18 18:56:20 Log times are in UTC. Local time is 18 Nov 2019 12:56:20
2019/11/18 18:57:16 ==> REQUEST/RESPONSE (Try=1/6.3882ms, OpTime=7.3888ms) -- RESPONSE STATUS CODE ERROR
   PUT XXXXX
   Content-Length: [88]
   Content-Type: [application/xml]
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [application/octet-stream]
   X-Ms-Client-Request-Id: [0e6b1857-91c2-4454-6e74-9e18a1a0914f]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 500 Operation could not be completed within the specified time.
   Content-Length: [245]
   Content-Type: [application/xml]
   Date: [Mon, 18 Nov 2019 18:57:16 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [OperationTimedOut]
   X-Ms-Request-Id: [edc8d2b7-b01e-000d-3741-9e8e04000000]
   X-Ms-Version: [2018-03-28]
Response Details: ﻿<Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time. </Message>

2019/11/18 18:57:16 ==> REQUEST/RESPONSE (Try=1/10.6591ms, OpTime=10.6591ms) -- RESPONSE STATUS CODE ERROR
   PUT XXXX
   Content-Length: [88]
   Content-Type: [application/xml]
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [application/octet-stream]
   X-Ms-Client-Request-Id: [ec9bb873-73af-4b53-5a2d-a39d88824cf1]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 500 Operation could not be completed within the specified time.
   Content-Length: [245]
   Content-Type: [application/xml]
   Date: [Mon, 18 Nov 2019 18:57:16 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [OperationTimedOut]
   X-Ms-Request-Id: [0e2abac4-101e-003b-4341-9ea9bc000000]
   X-Ms-Version: [2018-03-28]
Response Details: ﻿<Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time. </Message>

**Comment by JohnRusk** [comment] 2019-11-18 23:58
I'm not sure if the errors shown above are actually the root cause.  They both say try=1.  AzCopy automatically retries failed operations up to 20 times. 

Can you run this command please:
`azcopy jobs show jobid --with-status Started`

Replacing jobid with the guid that identifies the job. Use one of the jobs where you had to kill it after it reached 100% with one pending file.  If you don't know the job ids, you can get a list of them with `azcopy jobs list`

The suggest command will, hopefully, show you the one file that didn't work.  

It would be helpful to us to see the log lines that are around the locations that mention that filename. Specifically the X-Ms-Request-Id's that are associated with that file.  If you could search the log, based on the filename, and find the relevant sections that could be very helpful. Alternatively, you can email us the whole zipped log file. My Microsoft email address is in my profile.

**Comment by danobri** [comment] 2019-11-19 20:17
Thanks!  The --with-status Started switch works great - it's allowing me to identify the one file that failed to copy in each job like you said.  I have not had any problems copying these failed files over once I identify them.  The issue is continuing to occur though, so I am babysitting the process, - occasionally killing and restarting on the next blob container.  When I look at the log file for one of these jobs, there is essentially nothing in it.  Here is an example of the latest one:

2019/11/19 18:14:49 AzcopyVersion  10.3.2
2019/11/19 18:14:49 OS-Environment  windows
2019/11/19 18:14:49 OS-Architecture  amd64
2019/11/19 18:14:49 Log times are in UTC. Local time is 19 Nov 2019 12:14:49
2019/11/19 20:09:09 AzcopyVersion  10.3.2
2019/11/19 20:09:09 OS-Environment  windows
2019/11/19 20:09:09 OS-Architecture  amd64
2019/11/19 20:09:09 Log times are in UTC. Local time is 19 Nov 2019 14:09:09

If there is nothing in the log file, where is the log of the failed file being stored (the one returned using the --with-status Started switch)?

**Comment by JohnRusk** [comment] 2019-11-19 20:26
The --with-status switch reads from the plan file, not the log file.  Plan files list all the work that AzCopy will do in a job.  They're not human-readable. By default they are stored in a "plans" subdirectory under the .azcopy directory.

BTW, given that this is still happening, it would be super-helpful if you could do one or two runs with `--log-level DEBUG` on the command line.  I hope that that will show us some of what we're missing, in terms of why these are failing.  You'll need to do that for the main job (the ones where failures sometimes happen). And, unfortunately, the log files will be very big.  So, before you do that, it's probably a good idea to to see if you have lots of space free on the drive where logs are currently being stored. I don't know off the top of my head how much you'll need, but 10's of GBs would be a good guess.   If you don't have that space on the drive where your logs are currently stored, you can move them to a different drive by setting the AZCOPY_LOG_LOCATION environment variable to the path where you'd like the logs to be saved.

And, if you don't have 10s of GBs free on any drive, that's OK.  We can possibly make progress on finding the root cause without debug logging... if you're able to provide some of the request ID's associated with the failed files, as per my question above.  The request IDs should appear on a log line immediately after (some of) the lines that have the name of the affected file.

**Comment by danobri** [comment] 2019-11-19 20:30
In order to get you request IDs though, I will need to set the log-level to DEBUG though, right?  The log contents I included in my last post are from one of the failed jobs, and there are no request IDs.

**Comment by JohnRusk** [comment] 2019-11-19 20:34
INFO level, which is the default, includes request IDs for completed operations.  The benefit of DEBUG is that it also logs at the start of each operation, so we can get IDs of operations that start but for some reason never complete (one possible explanation for the "stuck" files).

The log you posted above looks like it was done with log-level WARNING or ERROR, and as you say, those don't include any request ids for successful operations. They only have ids for operations that _complete_ with a _failed_ result.  Does that answer your question?

**Comment by danobri** [comment] 2019-11-19 20:38
Sorry - I am still confused by this comment:

> if you don't have 10s of GBs free on any drive, that's OK. We can possibly make progress on finding the root cause without debug logging... if you're able to provide some of the request ID's associated with the failed files, as per my question above.

Sounds to me like the only way to get request IDs for the failed files is with log-level of DEBUG, no?

**Comment by JohnRusk** [comment] 2019-11-19 20:45
Oh, I see why that comment wasn't clear!  AzCopy makes a series of calls for each file (not just one). We've had a similar problem reported by one other user, and in their case, the first two calls were succeeding and the third would fail.  I'm assuming that the same will be true in your case.  So... if i can get request IDs for the first two (that succeed) that will help me find the right spot in the logs to look for the third request - the one that we don't have any ID for.  But without the ID for the first two queries, it's hard to track down the third in the logs.

So INFO will let us get the request IDs for the successful ones that precede the failure; but only DEBUG can directly give us the actual IDS of any requests that start but don't complete.  I had mistakenly assumed you may have an INFO level log just lying around, but re-reading your original message I see that you've been using ERROR all along, and so won't have any INFO ones. In that case, doing a new run with DEBUG is indeed the best option.  Sorry about the confusion. Let's go with DEBUG if you have the disk space.

**Comment by danobri** [comment] 2019-11-19 20:48
Sounds good - I've got 64GB free on the OS volume where this is running, so I'll give it a shot, and just keep an eye on it.  Hopefully it fails before the log files get too large.  Thanks!

**Comment by JohnRusk** [comment] 2019-11-19 20:51
Thank _you_.  If you can catch this happening in a log file it will be super-useful!

**Comment by danobri** [comment] 2019-11-20 13:53
So I let the process run overnight, which resulted in a an 18GB log file, and can't figure out how to open and search a text file that big using software on an Azure Windows 10 VM.  Any recommendations?  I restarted on new containers this morning, but so far have not been able to reproduce the issue again.  If there is someway to search the 18GB file, I can provide you with the relevant request IDs.

**Comment by danobri** [comment] 2019-11-20 15:18
OK - managed to reproduce with a smaller log file.  It's still over 3GB, but when zipped it's only 233MB.  I will try to email it to you shortly, but let me know if there is some other way I should send it.  I know a lot of mail servers block files over 25MB.

**Comment by danobri** [comment] 2019-11-20 15:29
Email didn't work, so I shared a DropBox location with you, and sent an email with details.  Please let me know what you find - thanks!

**Comment by danobri** [comment] 2019-11-20 18:32
I have completed my migration, and would like to delete the source storage account.  Do you need me to keep it around for any reason?

**Comment by JohnRusk** [comment] 2019-11-20 18:43
Can I check the logs and get back to you on that?  (I don't think we'll need to keep the source, but it might pay to check the log first).

**Comment by danobri** [comment] 2019-11-20 18:53
Sure - I'll leave it in place for the time being.

**Comment by JohnRusk** [comment] 2019-11-26 00:38
I'm pretty sure I've found the root cause.  It's hanging in the lookup to see whether a proxy server should be used.  We'll add some caching of that, to reduce the number of lookups, and enforce timeouts more strictly on the lookup too.

**Comment by JohnRusk** [comment] 2019-12-12 23:07
Fixed in release 10.3.3.  Thanks heaps for bringing this to our attention @danobri

**Closed by JohnRusk** 2019-12-12 23:07 UTC

**Comment by JohnRusk** [comment] 2020-05-21 22:00
PR was https://github.com/Azure/azure-storage-azcopy/pull/757
