### ISSUE TITLE
Error when adjusting the bandwidth

### ISSUE THREAD

**Issue by kostasvl** [Azure/azure-storage-azcopy#2262] opened 2023-06-21 17:16 UTC
### Which version of the AzCopy was used?
10.19.0. Does not repro with 10.18.1.

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`copy https://<blah> C:\Users\<blah> --output-type=json --cancel-from-stdin --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --trusted-microsoft-suffixes=<blah> --log-level=INFO `

### What problem was encountered?

I adjusted the bandwidth cap (via AZ Storage Explorer, but see below). I set it to 50 in this example. The download ended abruptly, after a few secs. This is from the bottom of the log:

```
2023/06/21 16:54:41 ==> REQUEST/RESPONSE (Try=1/131.2742ms, OpTime=131.2742ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://<blah>?timeout=901
   X-Ms-Request-Id: [81b50341-601e-0021-3761-a466e9000000]

2023/06/21 16:54:41 ERR: [P#0-T#0] DOWNLOADFAILED: https://<blah> : 000 : request size greater than pacer target. When Enqueuing chunk. X-Ms-Request-Id: 

   Dst: \\?\C:\Users\<blah>
2023/06/21 16:54:41 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: context canceled. Offset: 2185232384  Count: 4194304 URL: https://<blah>
2023/06/21 16:54:41 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W: 622, F:  0, H:  2, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T: 624, GRs:  4
2023/06/21 16:54:41 10.2 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 621.8532
2023/06/21 16:54:41 INFO: [P#0-T#0] https://<blah> Deleting incomplete destination file Dst: \\?\C:\Users\<blah>
2023/06/21 16:54:42 JobID=9f1dc69c-516e-d749-5dc0-f84c244c0aad, Part#=0, TransfersDone=1 of 1
2023/06/21 16:54:42 all parts of entire Job 9f1dc69c-516e-d749-5dc0-f84c244c0aad successfully completed, cancelled or paused
2023/06/21 16:54:42 is part of Job which 1 total number of parts done 
2023/06/21 16:54:43 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  2, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  2, GRs:  4
2023/06/21 16:54:43 0.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 
```

### How can we reproduce the problem in the simplest way?

Use AZ Storage Explorer to download something large enough, and use the Adjust Bandwidth link while it's in progress. I think I only tried with values <100, and it's probably worth noting that we have a much higher download bandwidth here in the office (I've seen it hit 4500+).

It's not just AZ SE. I get the same issue in my own apps, with the method described here: https://github.com/Azure/azure-storage-azcopy/wiki/Adjust-throughput-of-a-transfer-in-progress. Not that it's a surprise, since I'm sure AZ SE uses this method internally.

Only downloads are affected by this issue. Uploads are fine.

### Have you found a mitigation/solution?
Downgrade to 10.18.1.

I'm using the method in the above link to offer a pause button in my apps, since azcopy is known to take over a machine while it's working... Pausing => set a limit of 1 mbps, resuming => set the limit to 0 (unlimited). I could work around this new issue by re-implementing how my pause button works, like they suggest here: https://github.com/Azure/azure-storage-azcopy/issues/1476. Only if I have to though, since what I have works reasonably well, if I stick with 10.18.1.

Thanks!

**Comment by vibhansa-msft** [comment] 2023-06-22 04:51
" 000 : request size greater than pacer target. When Enqueuing chunk." : This error points to an invalid config. You have set bandwidth limit that cannot be supported with the chunk size you have, because chunks are bigger and even one chunk cannot be queued to transfer with this combo. Default chunk size being 8MB you cannot set bandwidth limit lower then 64Mbps.

**Comment by kostasvl** [comment] 2023-06-23 13:51
Thanks for the explanation I'll change how my pause button works.

May I suggest a few related improvements?

1. Make azcopy not error out in this case. Printing a message like "received low value for cap-mbps, adjusting to min supported: X" would be better.
2. Assuming that 64 Mbps is a hard limit that would apply to every situation out there, change Azure Storage Explorer to enforce that limit. It currently allows anything >= 0, with no indication in that UI that there could be trouble. Btw, I know that that's technically a different product, but hopefully you'll be able to describe what's needed to them (and why), better than I could.
3. It would be nice if azcopy could work in a way that wouldn't take over a machine, such that we wouldn't need a pause button in our apps at all. After benchmarking finishes, maybe it's possible for azcopy to automatically limit the mbps to 95% of the max? This behaviour should be behind a flag at least, or configurable.
4. If the above isn't possible/practical, could we get explicit pausing functionality? Something like "pause/resume" messages through stdin? That would be much better than harshly killing the azcopy.exe process and hunting the job id in the logs, for later resumption (where it would have to re-do the benchmark).

Thanks!

**Comment by vibhansa-msft** [comment] 2023-06-28 04:43
Reason for AzCopy to consume all the resources available on the system is to get the maximum throughput in job. Most customer rely on AzCopy to perform their transfer jobs as fast as possible and hence there is no such limits. For cases where customer want to restrict the access to network the bandwidth limits are applied. For your request on min bandwidth limit, its actually coupled with the block size and many customers tune block size depending on their workload hence making any assumption on the min bandwidth limit is not apt for AzCopy. StgExp is not the only use case we cater so we can not take any assumption based on StgExp requirements. However, I get your point on dumping proper error so that its easy for user to understand what needs to be corrected. Will add that request to our backlog. For the job pause/resume there are commands available in AzCopy to do the same and you can fire those commands from a different terminal with the job id that AzCopy prints. StgExp pause functionality is also doing the same. Will close this item as there are no action item on AzCopy end as of now and your feedback about correcting the log will be added to our backlog.

**Comment by FH-Inway** [comment] 2023-07-28 11:21
Same issue here. Files I could previously download with a bandwith limit of 30 Mbps now error out. Increasing/removing the limit resolves the error, but makes doing any other work during the download unbearably slow. From my point of view, this is a regression of functionality.

**Comment by vibhansa-msft** [comment] 2024-01-02 06:48
As I mentioned in my previous comment, earlier there was a situation where AzCopy might have hung forever with certain config and to avoid those issue we have started throwing the error in certain config combinations where we foresee a potential to hit a hung situation. You feedback is taken and we will investigate if we can make the error more specific to certain cases only.

**Comment by vibhansa-msft** [comment] 2024-02-01 03:59
Closing this as there is no action item open on AzCopy. Feel free to reopen if you think otherwise or have any suggestions/concerns on this.

**Closed by vibhansa-msft** 2024-02-01 03:59 UTC
Labels: user experience
