### ISSUE TITLE
azcopy reports failure when copying files that are in use

### ISSUE THREAD

**Issue by avernigo** [Azure/azure-storage-azcopy#1923] opened 2022-10-07 18:43 UTC
### Which version of the AzCopy was used? 
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
linux

the azcopy running in a container. From time to time upload fails with the error `000 : source modified during transfer` which is fine, assuming the file was in use at that point. But this leads azcopy to report a non-zero exit code which leads a container to report failure. IMHO this should not be a failure, because such things are pretty much expected.

So the question is, what is the workaround? is it possible to skip files that are in use and let azcopy complete without reporting a failure?

**Comment by nakulkar-msft** [comment] 2022-10-10 04:53
Hi @avernigo, this is by design. It is required for the source to be unchanged while the file is being transferred, for consistency reasons. We do not have workaround currently on AzCopy, however if you can read from a read-only source (say a snapshot) you should do that.

We've taken this feedback, and we'll plan on skipping files modified during transfer.

**Closed by nakulkar-msft** 2022-10-10 04:53 UTC
