### ISSUE TITLE
Allow azcopy to transfer modified files without failure

### ISSUE THREAD

**Issue by timacles** [Azure/azure-storage-azcopy#1796] opened 2022-05-23 17:56 UTC
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.15.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
azcopy copy "/var/lib/folder" \
"https://account.blob.core.windows.net/container/target_folder" \
--exclude-path "mydir/" --recursive true --overwrite true --check-length false
### What problem was encountered?
Running azcopy copy or sync, any files changed during the process are failed, and not uploaded. Reading the documentation and other issues it seems like this is the intended behavior. Inquiring whether there is a flag I'm missing to bypass this or a feature could be implemented to allow this behavior.

I'm attempting to do an online backup of a semi-large Postgres database cluster (3TB). Postgres is setup in a such a way, that with WAL archiving, the continually changing database files on the active database cluster will not cause an issue as long as they are copied over during the process (the WAL files will bring them up to date). But azcopy prevents such an online backup from being done since it fails and omits any modified files causing missing files in the final data structure. 

Is there any way to allow the copying of these modified files?

### How can we reproduce the problem in the simplest way?
Run `azcopy copy directory` on an active database cluster

### Have you found a mitigation/solution?
Streaming a pg_basebackup into azcopy copy with pipe works fine, but does not allow for the massive performance gains from using azcopy directly on the database directory.

**Comment by nakulkar-msft** [comment] 2022-05-24 16:28
Duplicate of #1747

**Comment by mstenz** [comment] 2022-10-30 12:47
We have the same issue and i have overcome this with lvm snapshots. We are creating a new snapshot now from the folder, using azcopy for backup and then deleting the snapshot directly again.

**Comment by nakulkar-msft** [comment] 2022-11-22 03:07
Hi, we've reviewed this again, and decided to retain the current behaviour. Allowing this change would cause inconsistencies in most of the regular usecases that AzCopy cannot determine or reason about.

**Closed by nakulkar-msft** 2022-11-22 03:07 UTC
