### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-storage-azcopy#632] opened 2019-10-02 11:23 UTC
2019/10/01 22:53:04 AzcopyVersion  10.2.1
2019/10/01 22:53:04 OS-Environment  windows
2019/10/01 22:53:04 OS-Architecture  amd64
2019/10/01 22:53:04 Job-Command sync [path-to-folder] [blob-container-SAS] --put-md5 
2019/10/01 22:53:04 Number of CPUs: 16
2019/10/01 22:53:04 Max file buffer RAM 8.000 GB

I get the error constantly:

>> Put https://account.blob.core.windows.net/blah-blah-WITH-SAS: context deadline exceeded

I already tried 4 times to sync that folder which has only pictures and videos (no, it's not porn!).

**Comment by JohnRusk** [comment] 2019-10-02 21:43
Is your network bandwidth a few hundred Mbps, or below?  In that case, maybe AzCopy is trying to do too much in parallel. Try setting the environment variable AZCOPY_CONCURRENCY_VALUE to about 16, and the problem should go away. (Version 10.3 will allow you to set that environment variable to AUTO, which should be even better - at the cost of slightly slower startup in the first 15 seconds or so of a job).

**Comment by alvipeo** [comment] 2019-10-03 10:46
Thanks, I'll try. But AzCopy should handle it by itself.

**Comment by JohnRusk** [comment] 2019-10-03 18:49
We're moving in that direction (handling it by itself), but for reasons of backward compatibility and performance of short-duration jobs, it won't be the default even in release 10.3.

**Comment by JohnRusk** [comment] 2019-11-15 02:29
To make AcCopy handle it by itself you can now set the environment variable AZCOPY_CONCURRENCY_VALUE="AUTO".

I'm closing this issue now, but if the problem is not resolved you for you please let us know and we'll re-open it.

**Comment by JohnRusk** [comment] 2019-11-15 02:29
BTW, AUTO requires version 10.3 or later.

**Closed by JohnRusk** 2019-11-15 02:29 UTC
