### ISSUE TITLE
azcopy sync can't sync a a file if the file didn't exist on the blob.

### ISSUE THREAD

**Issue by limingu** [Azure/azure-storage-azcopy#328] opened 2019-04-10 20:06 UTC
### Which version of the AzCopy was used? 
azcopy_windows_amd64_10.0.9

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Azcopy command: c:\users\limgu\workspace\azure-cli-extensions\src\storage-preview\azext_storage_preview\azcopy\azcopy_windows_amd64_10.0.9\azcopy.exe sync C:\temp\dirout.txt https://limguaccount.blob.core.windows.net/mycontainer/dirout.txt --delete-destination true

Result: 
Cannot perform sync due to error: sync must happen between source and destination of the same type: either blob <-> file, or container/virtual directory <-> local directory

### What problem was encountered?
The local file C:\temp\dirout.txt exits. Before run the command, there is no dirout.txt existing in the blob yet.
I think if I use the sync even when there is no file on blob, it should upload the local file to the remote. Is it a bug or by design for the new file that can't be synced?

### Have you found a mitigation/solution?
I have to use  copy to upload the new file.

**Comment by zezha-msft** [comment] 2019-04-10 20:47
Hi @limingu, this behavior is by design. Please refer to the [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) for more info on Sync.

FYI the reason why it was designed this way, is because we couldn't really tell whether the blob truly doesn't exist or the user meant to point to a virtual directory (which doesn't exist physically). Please let me know if you have any other question.

**Comment by lesterw1** [comment] 2020-03-21 07:21
> Hi @limingu, this behavior is by design. Please refer to the [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) for more info on Sync.
> 
> FYI the reason why it was designed this way, is because we couldn't really tell whether the blob truly doesn't exist or the user meant to point to a virtual directory (which doesn't exist physically). Please let me know if you have any other question.

This is an age old problem with any copy/sync utility. Rather than simply failing, why not fix this issue and amend the [documentation](https://docs.microsoft.com/en-gb/azure/storage/common/storage-ref-azcopy-sync) to state that **for a single file**, you MUST specify the full path **or** use a wildcard. It is lame that it fails with the nonsensical error *"Cannot perform sync due to error: sync must happen between source and destination of the same type"*. I spent 10 minutes trying to figure out why the documented single file example doesn't work:

```
azcopy sync "/path/to/file.txt" "https://[account].blob.core.windows.net/[container]/[path/to/blob]"
```

Fix this issue and amend the documentation as follows:
[!NOTE] **The destination path/to/blob MUST include the target blob name.**

Meanwhile, I will put a change in the [documentation](https://docs.microsoft.com/en-gb/azure/storage/common/storage-ref-azcopy-sync) to add the following Note to the single file sync example:
[!NOTE] **The destination blob MUST exist. Use ```azcopy copy``` to copy a single file which does not exist in the destination.**

**Comment by lesterw1** [comment] 2020-03-21 08:25
Ideally, this issue can be fixed so that ```azcopy sync``` behaves like ```azcopy copy``` when the destination is ambiguous (i.e., doesn't exist, so did the user specify a blob or a blob path?). See around line 69 in [cmd/syncEnumerator.go](https://github.com/Azure/azure-storage-azcopy/blob/master/cmd/syncEnumerator.go) and compare the logic to the code around line 72 in [cmd/copyEnumeratorInit.go](https://github.com/Azure/azure-storage-azcopy/blob/master/cmd/copyEnumeratorInit.go). 

I am not a GO programmer, so this is a cursory attempt to find where to address this issue. :)

**Comment by JohnRusk** [comment] 2020-03-24 20:50
Reopening this issue

**Comment by urbanspike** [comment] 2021-02-23 13:20
hello,
i have the same problem. My code :
`$source = "\\myserver\e$"
$destination = "https://myblob.blob.core.windows.net/test/MYTEST/" + $token
C:\azcopy_windows_amd64_10.8.0\azcopy.exe sync $source $destination --recursive=true --delete-destination=true --exclude-pattern="*.bak"`

I have test with / or not, same problem.
Test that for source : "\\myserver\e$\*.*"

Can you help me ?

Regards,

**Comment by vibhansa-msft** [comment] 2023-12-20 16:09
This is fixed in the later verison of AzCopy. Also there is an overwrite flag if you wish to force upload the source file to container. Closing this for now. Feel free to create a new report if the issue persists even with latest version.

**Closed by vibhansa-msft** 2023-12-20 16:09 UTC
Labels: user experience
