### ISSUE TITLE
AZCopy Sync not setting correct content type on Blob Container to Blob Container data move.

### ISSUE THREAD

**Issue by MNashDev** [Azure/azure-storage-azcopy#729] opened 2019-11-08 11:55 UTC
### Which version of the AzCopy was used? 
AzCopy 10.3.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Powershell

### What command did you run?
$sourceStore = "<Source Store>"
$sourceSAS = "<Source SAS>"
$destStore = "<Destination Store>"
$destSAS = "<Destination SAS>"
$blob = "<container Name>"
$sourceURI = "https://"+"$sourceStore"+".blob.core.windows.net/"+"$blob"+"$sourceSAS"
$destURI = "https://"+"$destStore"+".blob.core.windows.net/"+"$blob"+"$destSAS"

azcopy sync "$sourceURI" "$destURI" --recursive

### What problem was encountered?
The Source Files are of varying file types (.jpg , .pdf ,.docx, .ppt, etc..)  and so have content types relevant to their file types e.g. 'image/jpeg' 
However  when they are sync'd to the destination store all the files are given the content type 'application/octet-stream'.

We are migrating this data from a classic storage account and Blob into an ARM based storage account and Blob

### How can we reproduce the problem in the simplest way?

You shold be able to run the powershell provided (Adding your own stores/blob and SAS details)

We are migrating from a classic Blob stor to an  ARM Store so this may be related

### Have you found a mitigation/solution?
-Not thus far.- 
You are able to manually change the file type through Storage explorer.. however we have 18k+ files in just one Store, and so we need an automated update route

**Comment by JohnRusk** [comment] 2019-11-08 19:50
@adreed-msft could you see if you can replicate this?

**Comment by adreed-msft** [comment] 2019-11-14 00:59
Sure thing!

**Comment by adreed-msft** [comment] 2019-11-14 01:07
Yup, got a repo on this. Not sure what causes it, but I'm investigating.

**Comment by adreed-msft** [comment] 2019-11-14 01:09
Caused by scheduleCopyTransfer in zc_processor.go. Most properties get copied, but not the extra properties!

**Comment by JohnRusk** [comment] 2019-12-12 23:08
Fixed in release 10.3.3, which we released today.

**Closed by JohnRusk** 2019-12-12 23:08 UTC
