### ISSUE TITLE
Not all files copied using sync

### ISSUE THREAD

**Issue by t0mmyt** [Azure/azure-storage-azcopy#351] opened 2019-04-23 14:13 UTC
### Which version of the AzCopy was used?
10.0.9 (attached log is from 10.0.8 but behavior is the same)

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (RHEL7)

### What command did you run?
```
 /usr/local/bin/azcopy sync /srv/repo/ https://${STORAGE_ACCOUNT}.blob.core.windows.net/repo/?$SAS

Job 0ae11201-d447-af4f-5afa-a5c72000f2db has started
Log file is located at: /tmp/0ae11201-d447-af4f-5afa-a5c72000f2db.log

59301 Files Scanned at Source, 48966 Files Scanned at Destination

Job 0ae11201-d447-af4f-5afa-a5c72000f2db Summary
Files Scanned at Source: 59301
Files Scanned at Destination: 59761
Elapsed Time (Minutes): 0.3668
Total Number Of Copy Transfers: 1
Number of Copy Transfers Completed: 1
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 0
Total Number of Bytes Enumerated: 0
Final Job Status: Completed
```

### What problem was encountered?
Not all files are copied, for example in a directory with 4989 files, only 4941 are seen at the destination.  I've attached a log (I needed to create a new file for the log to exist, is this by design?).
[0ae11201-d447-af4f-5afa-a5c72000f2db.log](https://github.com/Azure/azure-storage-azcopy/files/3107901/0ae11201-d447-af4f-5afa-a5c72000f2db.log)

### How can we reproduce the problem in the simplest way?
Not really sure, in my case, the source is a file container in a storage account and the destination is a blob container in the same account.  The issue might be the number of files?  One problem directory is ~5000 files

### Have you found a mitigation/solution?
Not yet

**Comment by zezha-msft** [comment] 2019-04-23 19:23
Hi @t0mmyt, thanks for reaching out!

I see in the summary:
```
Files Scanned at Source: 59301
Files Scanned at Destination: 59761
```

Could you please double check that files are actually missing at the destination? If yes, do the files have permission restrictions? Btw were you adding/editing files as the scanning was happening?

Sync scans the local directory first, and keeps an index map of what's at the source. It then scans the destination container and checks if we should transfer files from the source again. For every file at the source that doesn't exist at the destination, they will be transferred for sure (if the file was present at time of scanning). There's a [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) that has more info if you are interested.

Could you please clarify this? You mean a log is only created if an actual transfer happens?

> I needed to create a new file for the log to exist, is this by design?

**Comment by t0mmyt** [comment] 2019-04-24 09:02
Hi @zezha-msft 

Yes, there definitely were files missing at the destination, one particular directory that had 4989 files at the source only had 4941 at the destination.  The source is a CIFS mount of a file share with file/dir 0644/0755 applied across the whole share.  The files are fairly static.  There is a chance that there are some files already on the destination that are not on the source.

Yes, I meant that if the copy tool doesn't do anything it either deletes or never writes the log although tells you log file is located at x.

Is there a way to enable debugging to see the plan/decision per file?  It might be easier to find out whether the missing files were considered or not noticed or had something funky in the name.

**Comment by JohnRusk** [comment] 2019-04-24 09:39
The AzCopy job command can, I think, show the per file decisions. Run
AzCopy job - - help
for info.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zezha-msft** [comment] 2019-04-24 19:45
Hi @t0mmyt, thanks for the additional info!

If you are using 10.0.9 (btw 10.1.0 the first GA version is out), AzCopy should print "INFO: Accessing [file path] failed with error [error message]" if there's any problem with scanning the file.

To validate whether there are missing files, I'd suggest to download the contents of that particular directory to somewhere else on your local drive (`dir2`), and perform a comparison with `diff -qr dir1/ dir2/`, where `dir1` points to your original data.

We'd be eager to help if there are indeed missing files.

**Comment by t0mmyt** [comment] 2019-04-25 13:36
Hi @zezha-msft 

I've just tried 10.1.0 and the issue is the same and there are no errors emitted.

As I said, the source is a CIFS mount which has the same permissions masked over all files so I doubt read access issues.  I used blobfuse to mount the container, ran a sorted find over both and compared and there are about 100 files that are missing from 59300 (there are a few additional files on the destination that have been since deleted on the source hence the misleading output).

**Comment by zezha-msft** [comment] 2019-04-25 21:30
Hi @t0mmyt, thanks a lot for trying the latest version!

To help us come up with a repro, could you please confirm the following?

1. The source is a CIFS mount backed by an Azure File Share
2. AzCopy reported the right total number of files at the source, which is 59301 (including the test file you added)
    1. Please verify with `find DIR_NAME -type f | wc -l` if necessary
3. Not that I don't trust blobfuse, but could you please verify that the missing blob is indeed missing in an independent way? For example, paste its URL into the browser and see if download works.
4. Did you observe any pattern in the missing files? Do they have the same extension? Are they hidden files?
5. If you moved a missing file to another location, such as another sub folder, does it get picked up in the next sync job? (this one might be really helpful)

Thanks a bunch for your help!

**Comment by JohnRusk** [comment] 2019-05-24 01:03
@t0mmyt Here on the AzCopy team we're hoping to understand this issue better, in terms of root causes etc. It would be super-helpful if you were able to reply to some (or all) of Ze's 5 points above. Thanks heaps!

**Comment by zezha-msft** [comment] 2019-05-30 17:03
Hi @t0mmyt, I'm closing this issue for now due to lack of response. Please let us know if you could provide us more info to enable further investigation.

**Closed by zezha-msft** 2019-05-30 17:03 UTC

**Comment by JohnRusk** [comment] 2019-06-13 06:30
May possibly have been related to #431
