### ISSUE TITLE
Performance discrepancies betweem using blob vs dfs API in Azure Data Lake Storage

### ISSUE THREAD

**Issue by lukasz-krzykowski** [Azure/azure-storage-azcopy#2465] opened 2023-11-21 16:47 UTC
### Which version of the AzCopy was used? 

10.21.2 (latest stable at the moment)

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

I've ran two uploads of the same dataset, same machine, same network, to same destination (Azure Blob), the only difference was the URL (API used) - once with `blob` and once with `dfs`. The dataset consists of 1M small files (between 500 to 1500 bytes each). This is the real use case for my production system in which we intend to base the upload process with `azcopy` underneath.

Blob:
```
azcopy.exe copy C:\temp\dg\dg-files-1m-size-1gb-seed-1 "https://skynetadls.blob.core.windows.net/dev/onem?sv=2021-06-08&spr=https&st=2022-10-01T07%3A58%3A10Z&se=2023-12-31T16%3A58%3A10Z&si=testReadWritePolicy&sr=c&sig=REDACTED" --recursive --output-type json
```

Dfs:
```
azcopy.exe copy C:\temp\dg\dg-files-1m-size-1gb-seed-1 "https://skynetadls.dfs.core.windows.net/dev/onem?sv=2021-06-08&spr=https&st=2022-10-01T07%3A58%3A10Z&se=2023-12-31T16%3A58%3A10Z&si=testReadWritePolicy&sr=c&sig=REDACTED" --recursive --output-type json
```

Each upload was ran as the only significant process on that machine, both CPU and Network wise.

### What problem was encountered?

The `blob` upload ran perfectly fine, it utilized my computer and network capacity and I could also see normal usage of concurrent active connections in progress messages.
Sample progress message after 5 minutes of running the `blob` job:
```
{"TimeStamp":"2023-11-21T16:46:03.5430194+01:00","MessageType":"Progress","MessageContent":"{\"ErrorMsg\":\"\",\"JobID\":\"e7c038df-75fa-c749-572f-a2d968c25c8d\",\"ActiveConnections\":\"125\",\"CompleteJobOrdered\":true,\"JobStatus\":\"InProgress\",\"TotalTransfers\":\"1000000\",\"FileTransfers\":\"1000000\",\"FolderPropertyTransfers\":\"0\",\"SymlinkTransfers\":\"0\",\"FoldersCompleted\":\"0\",\"TransfersCompleted\":\"65716\",\"FoldersFailed\":\"0\",\"TransfersFailed\":\"0\",\"FoldersSkipped\":\"0\",\"TransfersSkipped\":\"0\",\"BytesOverWire\":\"70941424\",\"TotalBytesTransferred\":\"70681547\",\"TotalBytesEnumerated\":\"1072780398\",\"TotalBytesExpected\":\"1072780398\",\"PercentComplete\":\"6.588631\",\"AverageIOPS\":\"453\",\"AverageE2EMilliseconds\":\"549\",\"ServerBusyPercentage\":\"0\",\"NetworkErrorPercentage\":\"0.08960982\",\"FailedTransfers\":[],\"SkippedTransfers\":[],\"PerfConstraint\":0,\"PerformanceAdvice\":null,\"IsCleanupJob\":false}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
```

The `dfs` upload ran with very limited utilization my machine - while my upload capacity is at around 5 to 8 mbps - the process only utilized about 0.3 to 0.6 mbps of the bandwith.

The same AZCOPY_CONCURRENCY_VALUE parameters were used in both cases and **no throttling** were setup.

Sample progress message after 5 minutes of running the `dfs` job:
```
{"TimeStamp":"2023-11-21T16:51:16.4311061+01:00","MessageType":"Progress","MessageContent":"{\"ErrorMsg\":\"\",\"JobID\":\"7b96b3ca-7524-a24b-547d-f0b5a64c8aea\",\"ActiveConnections\":\"1\",\"CompleteJobOrdered\":true,\"JobStatus\":\"InProgress\",\"TotalTransfers\":\"1000001\",\"FileTransfers\":\"1000000\",\"FolderPropertyTransfers\":\"1\",\"SymlinkTransfers\":\"0\",\"FoldersCompleted\":\"0\",\"TransfersCompleted\":\"2214\",\"FoldersFailed\":\"0\",\"TransfersFailed\":\"0\",\"FoldersSkipped\":\"0\",\"TransfersSkipped\":\"0\",\"BytesOverWire\":\"2400041\",\"TotalBytesTransferred\":\"2398447\",\"TotalBytesEnumerated\":\"1072780398\",\"TotalBytesExpected\":\"1072780398\",\"PercentComplete\":\"0.22357297\",\"AverageIOPS\":\"40\",\"AverageE2EMilliseconds\":\"130\",\"ServerBusyPercentage\":\"0\",\"NetworkErrorPercentage\":\"0\",\"FailedTransfers\":[],\"SkippedTransfers\":[],\"PerfConstraint\":1,\"PerformanceAdvice\":null,\"IsCleanupJob\":false}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
```

You can notice few things that are way worse in dfs job in comparision to blob one:

- `TransfersCompleted` - 65716 (blob) vs 2214 (dfs)
- `ActiveConnections` - 125 (blob) vs 1 (dfs) - this value is keeping around 120 - 160 for blob and is always 1 for dfs,
- `PerfConstraint` - 0 (blob) vs 1 (dfs) - as far as I read the code - it indicates that the disk seems to be identified as the bottleneck in such case - but it seems very odd as the problem is 100% reproducible on my machine and my disk produces no issues as for `blob` transfers.

I am perfectly aware of the fact that pushing many small files is less convenient with DFS API as it requires at least 3 http requests to push a single small file compared to only 1 request on BLOB API, but still - the discrepancy on performance is way too big.

### How can we reproduce the problem in the simplest way?

Try to upload 1M of small files (single file has to be possible to be uploaded using a single chunk) into Azure Data Lake Storage using `blob` API and `dfs` API.

### Have you found a mitigation/solution?

No, as I need to use `dfs` API because I also want the empty directories to be created at the destination as this is also requirement in my business use case.

**Comment by vibhansa-msft** [comment] 2023-11-22 02:57
Performance difference between blob and dfs APIs are inherent and comes from the backend storage server. AzCopy has no role to play here for performance. It's by design hence closing this issue here.

**Closed by vibhansa-msft** 2023-11-22 02:57 UTC

**Comment by lukasz-krzykowski** [comment] 2023-11-22 07:01
I am totally aware of the difference at the API level, but that does not explain the facts above and the nearly 30x degradation in performance between using one API or the other.
It more likely looks like a bug in the current solution, because it looks like we are no able to handle concurrency in a efficient way (like in blob) - which could be very well done despite the chosen API.
Also the fact that disk is reported as a `PerfConstraint` is somehow red-flag / looks like a buggy behavior

**Comment by lukasz-krzykowski** [comment] 2023-11-22 14:51
>AzCopy has no role to play here for performance. It's by design hence closing this issue here.

I cannot confirm that - if I upload smaller part of this dataset - e.g. only 3000 files - the difference in performance between blob and dfs it's almost unmeasurable - both APIs perform very well.

**Comment by surlypants** [comment] 2024-02-16 20:32
to add to this...

azcopy (windows) current (as of 20240216)

azcopy sync account1.dfs.core.windows.net/container account2.dfs.core.windows.net/container

411411 Files Scanned at Source, 411950 Files Scanned at Destination
~120 minutes


azcopy sync account1.blob.core.windows.net/container account2.blob.core.windows.net/container
205737 Files Scanned at Source, 205975 Files Scanned at Destination

~24 minutes

_twice_ the amount of blobs via the dfs endpoint? strange indeed.
