### ISSUE TITLE
403 Server failed to authenticate the request , During Sync, No problem during CP

### ISSUE THREAD

**Issue by rdeheld** [Azure/azure-storage-azcopy#541] opened 2019-08-09 12:38 UTC
### Which version of the AzCopy was used? 
10.2.1 

##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 2012
### What command did you run?
./azcopy.exe sync "D:\ContainerStackLocations\" "https://rwgazurestorage001.blob.core.windows.net/containerstacklocations?st=2019-06-25T22%3A54%3A31Z&se=2020-06-26T22%3A54%3A00Z&sp=racwdl&sv=2018-03-28&sr=c&sig=" --put-md5 --delete-destination=True;

### What problem was encountered?
Sync seems to complete, but produces errors in eventlog, Problem only occurs during a sync. When ussing CP with same  url no error occurs

==> REQUEST/RESPONSE (Try=1/121.6088ms, OpTime=121.6088ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://rwgazurestorage001.blob.core.windows.net/containerstacklocations?se=2020-06-26t22%3A54%3A00z&sig=-REDACTED-&sp=racwdl&sr=c&st=2019-06-25t22%3A54%3A31z&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.2.1 Azure-Storage/0.7 (go1.12; Windows_NT)]
   X-Ms-Client-Request-Id: [79ceb471-f753-4d41-7547-642d79850b81]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Fri, 09 Aug 2019 12:31:20 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [26e65f46-801e-004d-2cae-4e962c000000]

### How can we reproduce the problem in the simplest way?
Sync files

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment] 2019-08-09 23:50
@adreed-msft I wonder if this might be due to it probing the container URL to test if its a directory. That's what the request looks like to me.  Copy (if no /* suffix on source) would not do that, because it puts everything one level down (into a virtual dir).  So I have two questions for you Adele:

1. Am I correct in recalling that, after the recent refactoring, it won't actually hit the blob resource for an "is directory" check?
2. Do you have time to test this scenario with both old and refactored code?  If not, let me know and I'll do it.  (But I'm assigning the issue to you in the meantime ;-)

**Comment by adreed-msft** [comment] 2019-08-13 20:53
Ehm... Hmm. The refactor doesn't touch sync code all that much, but I'll take a look into trying to reproduce this.

I *BELIEVE* that the sync code actually pings both the source and destination to check if it's a directory.

I also recall a bug that I haven't quite fixed up yet WRT sync, regarding a blob and virtual directory sharing the same name. IIRC, the / on the end is cleaned up prior to the actual directory check, which causes it to default to the single blob and fail when trying to sync a directory to the virtual directory. I'll add this to the comments PR.

**Comment by adreed-msft** [comment] 2019-08-13 21:38
Alright, so, for the source on the new copy enumerator:

We
- Check if it's syntactically a folder (if this passes, we treat the source as a folder without actually checking)
- If it's not syntactically a folder, we first check for blob properties. If that fails, we treat the source as a folder.

For the destination, we ONLY do the syntax check on blob, and everywhere else we start with a syntax check then do a folder properties check.

**Comment by adreed-msft** [comment] 2019-08-13 21:41
The behavior previously was the same.

**Comment by rdeheld** [comment] 2019-08-15 14:16
Is there any thing that i can do or test?

**Comment by JohnRusk** [comment] 2019-08-15 19:22
@Adele do you have time to run a small download sync using 10.2.1, using a container SAS, and just check to see if any such error appears in your log. Maybe it's normal on the blob properties check (the one that is expected to fail if source is not a single blob)

**Comment by forthroe** [comment] 2019-09-04 22:33
We have also seen an issue similar to this when downloading from an azure devops blob using a url with a sas token.  This was using version 10.2.1
2019/09/04 19:45:05 AzcopyVersion  10.2.1

RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

In our scenario, the whole blob tree gets created on the machine, with placeholder files that contain blank space to fill up the size of the file that matches the blob.

Any resolution to this?

**Comment by adreed-msft** [comment] 2019-09-06 20:13
@JohnRusk so I haven't been able to reproduce this in my own testing with similar permissions.

@rdeheld I notice the signature is cut off on your URL-- is this an intentional redaction?

@forthroe This one confuses me a bit and sounds like you have list permissions but not read permissions on your SAS token. It seems odd that it's an intermittent problem, though.

**Comment by adreed-msft** [comment] 2019-10-15 19:28
I believe this may have been resolved by our new directory check in 10.3.0. Could you take a look to see if your scenario works? In my testing, directing the sync at a container works.

**Comment by hakenr** [comment] 2020-01-27 08:51
...facing the same issue with azcopy_windows_amd64_10.3.4, the sync works like a charm, but in event-log, there is a new event recorded for every single run:
```
The description for Event ID 0 from source C:\Backup\azcopy.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

==> REQUEST/RESPONSE (Try=1/5.9985ms, OpTime=35.9755ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://havittransientbackups.blob.core.windows.net/money-data?se=2030-01-01t11%3A00%3A00z&sig=-REDACTED-&sp=racwdl&sr=c&st=2020-01-27t08%3A01%3A57z&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.3.4 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [1e3fb937-8020-47a9-782b-0c27f9116238]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Mon, 27 Jan 2020 08:18:44 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [a141b8a6-d01e-0049-0fea-d41436000000]
Response Details: 
```
backup.bat:
```
C:\Backup\azcopy.exe sync "C:\Money-Data" "https://havittransientbackups.blob.core.windows.net/-REDACTED-" --recursive --delete-destination=true
```

**Comment by JohnRusk** [comment] 2020-01-27 19:32
Looks like the HEAD call is on the container itself. I'm guessing its one of the tests we do to see what the type of the source and destination are, and that AzCopy expects and handles the error - but the low-level logging in the SDK still logs it.

@zezha-msft This is another reason why I'd like to get rid of that logging to the event log.

**Comment by zezha-msft** [comment] 2021-04-20 08:53
In 10.10, we added support to turn off eventlog completely.

**Closed by zezha-msft** 2021-04-20 08:53 UTC

**Comment by PavelPikat** [comment] 2021-04-22 07:35
> In 10.10, we added support to turn off eventlog completely.

10.10 release notes don't mention anything about eventlog or loggin in general. How do you turn evenlog off?

**Comment by mohsha-msft** [comment] 2021-04-22 07:40
Hey @PavelPikat ,

`AZCOPY_DISABLE_SYSLOG` environment variable can be used to disabled Syslog/Windows Event Logging.
