### ISSUE TITLE
Question/Feature - List all the folder prefixes within a container

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-storage-azcopy#818] opened 2020-01-07 01:03 UTC
### Which version of the AzCopy was used? 
AzCopy 10.3.3

Is it possible to do a list command but only list the folder prefix names in a given container?
Alternatively the ability do a list but only list in the top level or specified level of directory would also suffice.

If this is not possible I think it would be a useful feature to have.

**Comment by JohnRusk** [comment] 2020-01-07 01:06
It's not currently possible in AzCopy.  I agree it would be useful.

We'd need to think about how best to implement it. One (easy?) option _might_ be to support it only for accounts with multi-protocol access (i.e. Blob and ADLS Gen 2 endpoints on same account), since ADLS Gen2 has an explicit concept of folders (whereas folders are just virtual in the blob endpoint).

**Comment by nofunatall** [comment] 2020-01-07 01:08
File storage would be the same as ADLS where it has explicit shares and directories

**Comment by nofunatall** [comment] 2020-01-21 02:23
Another idea semi related to this would be to implement something like --max-depth=N
e.g Given the folder structure
```
container/folder1/folder2/blob3
container/folder1/blob2
container/blob1
```
If you ran:
`azcopy list --max-depth=2 https://container.blob.core.windows.net`

It would return:
```
container/folder1/folder2
container/folder1/blob2
```

**Comment by JohnRusk** [comment] 2020-03-10 22:26
Possible duplicate of/overlap with #858

**Comment by seanmcc-msft** [comment] 2024-08-02 18:20
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.

**Closed by seanmcc-msft** 2024-08-02 18:20 UTC
Labels: feature request
