### ISSUE TITLE
Azcopy v10 does not have provision to give storage account key as part of Azcommand line

### ISSUE THREAD

**Issue by gkkj** [Azure/azure-storage-azcopy#513] opened 2019-07-25 07:03 UTC
### Which version of the AzCopy was used? 

V10.2.1 
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
Below line source key storage account key and not SAS token

$srcURL="https://<sa>.blob.core.windows.net/sam/"
$sourcekey="******************
 $src = $srcURL + $sourcekey
$destFolder ="D:\temp"
#$result = ./AzCopy.exe /Source:$srcURL /SourceKey:$sourcekey  /Dest:$destFolder /s /xo /y /v:$verboseLogFile   /z:$journalLogFile  # v6
$result =.\azcopy  copy  $src  "D:\SAMTest\Data"  --log-level="ERROR" --recursive=true   # v10

### What problem was encountered?

In V6  we are ablee to passs the argument  /sourcekey  which is not allowing in v 10
### How can we reproduce the problem in the simplest way?
when we are appending source jey to the URl in v10 getting error "RESPONSE Status: 404 The specified resource does not exist."
### Have you found a mitigation/solution?
no as per the help we see  sas and oauth authentication can be done in  v10

**Comment by JohnRusk** [comment] 2019-07-25 07:57
Hi @gkkj 

The change, to disallow the use of the storage account key, is deliberate.  The new options, SAS and OAuth, are more secure. Note that there are 3 types of OAuth that are possible: Managed Service Identity (which is best if running on an Azure VM), Service Principal Authentication (which is good for unattended or scripted use on-premises) and "normal" OAuth which is good for interactive use.  If none of those suit, you should use SAS.

Because these new approaches are more secure, version 10 is not going to support the same key-based authentication that version 8 had.

Are you able to use OAuth or SAS in your scenario?

**Comment by gkkj** [comment] 2019-07-25 09:31
HI


If V 10 not suits for storage account key  then we may need to use SAS need to work on it

Thanks
Gopal

**Comment by JohnRusk** [comment] 2019-07-25 09:32
OK. I'll close this issue now, since the software is working as designed.

**Closed by JohnRusk** 2019-07-25 09:32 UTC
