### ISSUE TITLE
'azcopy list' does not list containers

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-storage-azcopy#154] opened 2019-01-07 03:14 UTC
### Which version of the AzCopy was used? 
```
$  azcopy --version
azcopy version 10.0.4-Preview
```
### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 16.04.5 LTS

### What command did you run?
```
$  azcopy list https://mystorageaccount.blob.core.windows.net/
List is using OAuth token for authentication.
```

### What problem was encountered?

I expect this command to list all the containers in the root directory.
Listing the blobs in a container works.

### Have you found a mitigation/solution?

Check the list of containers on the portal.

**Comment by zezha-msft** [comment] 2019-01-10 01:36
Duplicate of #153.

**Closed by zezha-msft** 2019-01-10 01:36 UTC
