### ISSUE TITLE
0panic: error getting the 0th part of Job

### ISSUE THREAD

**Issue by dmitrychastikov** [Azure/azure-storage-azcopy#869] opened 2020-02-18 09:41 UTC
AzCopy 10.3.4 was used
Windows 2016 Server
### What command did you run? Simultaneously 2 syncs (several seconds difference at start). Source container was previously synchronized into the second destination container. So the second sync should have resulted in comparison only and end up with no transfers.
$env:AZCOPY_CONCURRENCY_VALUE = "AUTO"
c:\tools\azcopy\azcopy sync "https://xxxx.blob.core.windows.net/bigdata$SAS" "https://xxxx.blob.core.windows.net/bigdata4/test1$SAS" --recursive=true
c:\tools\azcopy\azcopy sync "https://xxxx.blob.core.windows.net/bigdata$SAS" "https://xxxx.blob.core.windows.net/bigdata4/test2$SAS" --recursive=true

### What problem was encountered?
While the one sync was busy with copying,  the other instance crashed in the middle with this output:
INFO: SPN Auth via secret succeeded.

the container already exists

Job 51a9d68f-e3a9-cd4d-68b4-4c9a3a26cbf7 has started
Log file is located at: C:\Users\Berta\AzCopyBackupData\Log_ConcurAuto2\51a9d68f-e3a9-cd4d-68b4-4c9a3a26cbf7.log

995328 Files Scanned at Source, 995328 Files Scanned at Destination, 2-sec Throughput (Mb/s): 0panic: error getting the 0th part of Job 51a9d68f-e3a9-cd4d-68b4-4c9a3a26cbf7

goroutine 25 [running]:
github.com/Azure/azure-storage-azcopy/ste.GetJobSummary(0xcd4de3a951a9d68f, 0xf7cb263a9a4cb468, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vsts/work/1/s/ste/init.go:418 +0xa47
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xbb32ed, 0xe, 0xb09f80, 0xc000016510, 0xa91340, 0xc000b33560, 0x314c6a01, 0xc000b33560)
        /home/vsts/work/1/s/cmd/rpc.go:50 +0x69f
github.com/Azure/azure-storage-azcopy/cmd.glob..func4(0xbb32ed, 0xe, 0xb09f80, 0xc000016510, 0xa91340, 0xc000b33560)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x64
github.com/Azure/azure-storage-azcopy/cmd.(*cookedSyncCmdArgs).ReportProgressOrExit(0xc0000162c0, 0xd01020, 0xc000090500)
        /home/vsts/work/1/s/cmd/sync.go:391 +0x271
github.com/Azure/azure-storage-azcopy/common.(*lifecycleMgr).InitiateProgressReporting.func1(0xc000090500, 0xce80a0, 0xc0000162c0)
        /home/vsts/work/1/s/common/lifecyleMgr.go:453 +0x13d
created by github.com/Azure/azure-storage-azcopy/common.(*lifecycleMgr).InitiateProgressReporting
        /home/vsts/work/1/s/common/lifecyleMgr.go:443 +0x6d

### How can we reproduce the problem in the simplest way?
Not sure, it maybe a race conditions.

### Have you found a mitigation/solution?
Repeat the command after crash. Not really a good mitigation as the aim is to have everything working completely automated.

**Comment by JohnRusk** [comment] 2020-02-18 20:55
Ooh, that's not supposed to happen! (And never has, before.)

Any chance you could zip up the AzCopy log file from the failed run, and email it to me.  My email address is in my profile.    Log files contain filenames, but not authentication secrets.

**Comment by JohnRusk** [comment] 2020-02-19 21:19
Thanks for sending the log files and the details of the execution scenario @dmitrychastikov 

It sounds like we should do some testing here, starting an instance of AzCopy when the CPU is already under high load.

Can you tell us a bit about the machine you were running on?  How may cores?  VM or physical?  AMD or Intel (if you have that info).

Also, is this issue actively blocking your work or progress?  Does it happen often, or have you seen it just once.  If just once, I'd propose that we (the AzCopy team) don't look at this immediately, because we are busy in the build up to release 10.4.

**Comment by dmitrychastikov** [comment] 2020-02-20 06:58
@JohnRusk It was an Azure VM b2ms, 2 cpus, AFAIK must be Intel. 
Blocking? Well, in a way. Microsoft does not provide a solution for efficient copying and synchronization of data in Azure storage other than AzCopy. Before using it for production, we have to test the reliability of the software we are going to use. So far I was able to give it in total 20-30 runs on moderately sized accounts and containers (100K-1M blobs) and it crashed once. It means at the moment it does not look bulletproof and (if decided to be used) needs additional checks and retrying code around it. 
Obviously, I understand your team has their own planning and  priorities, so it's your call :-)

**Comment by JohnRusk** [comment] 2020-02-20 07:30
Thanks.  

Yes, we are very busy getting release 10.4 ready.  I think I'll have a quick look at this in a few days time. If it can be reproduced, then maybe we can fix it in that release.

If it can't be reproduced, then we'll have to wait until release 10.5 for a longer investigation.

Based on your callstack and the other info you've provided, I suspect that somehow its trying to report on progress for a sync job that had nothing to do --- which explains why it can't find the first job part (there aren't any).  Obviously there's supposed to be protection in the logic against that, otherwise all syncs with nothing to do would crash.  But somehow, under the conditions of CPU load etc that you reported, there's a bug in that logic.

We'll update this thread when we find more info.

**Comment by JohnRusk** [comment] 2020-05-29 06:32
@adreed-msft is this the thing you looked at?

**Comment by adreed-msft** [comment] 2022-11-07 19:00
Closing due to longevity. If this issue still persists, feel free to re-open.

**Closed by adreed-msft** 2022-11-07 19:00 UTC
