### ISSUE TITLE
hide progress

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-azcopy#1154] opened 2020-08-26 04:53 UTC
Hello, may i know is there any flag i can use to hide 
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total
and only show error on the console if there are 'failed' with error messages ?

**Comment by hho** [comment] 2020-12-21 18:17
Possible duplicate of #534 ?

**Comment by nakulkar-msft** [comment] 2022-02-28 06:04
Same as #534

**Closed by nakulkar-msft** 2022-02-28 06:04 UTC
Labels: enhancement
