### ISSUE TITLE
Feature request: Use IAM role from AWS_PROFILE or EC2 instance profile

### ISSUE THREAD

**Issue by wrschneider** [Azure/azure-storage-azcopy#1428] opened 2021-04-23 13:10 UTC
##### Note: The version is visible when running AzCopy without any argument

10.10

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux, and also Mac

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy cp https://[bucket].s3.amazonaws.com/....  [Azure destination]

### What problem was encountered?

Requires me to specify AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID, and AWS_SESSION_TOKEN vars explicitly.

### How can we reproduce the problem in the simplest way?

Set up AWS credentials in .aws/credentials file then try to use commands like "AWS_PROFILE=... aws s3 ..."
Then see that azcopy doesn't work with AWS_PROFILE var

Similar on EC2/ECS: assign a instance profile role that will support aws s3 cp commands, but azcopy won't work.

### Have you found a mitigation/solution?

Workaround: look up AWS credentials  from metadata endpoint explicitly and set env vars

**Comment by mohsha-msft** [comment] 2021-04-23 13:12
https://github.com/Azure/azure-storage-azcopy/issues/1341

**Comment by RajasGujarathi** [comment] 2022-04-22 14:11
The issue is reproducible with
```
AzcopyVersion  10.14.1
OS-Environment  linux
OS-Architecture  amd64
```

**Comment by gapra-msft** [comment] 2024-01-16 23:49
Closing this in favor of the issue linked above as this is a duplicate issue.

**Closed by gapra-msft** 2024-01-16 23:49 UTC
Labels: duplicate, aws-s3
