### ISSUE TITLE
support for s3 compliant storage such as minio

### ISSUE THREAD

**Issue by rbasore** [Azure/azure-storage-azcopy#1634] opened 2021-12-10 23:19 UTC
##### Note: The version is visible when running AzCopy without any argument
v10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy cp https://minio02.domain.com/td-nos-demo-master01/ https://stgaccount.blob.core.windows.net/12344-e097569f-1dd8-b308-fd24-ae6d596d9ddd/
### What problem was encountered?
Does not look like other s3 types of storage is supported
### Have you found a mitigation/solution?
Look

**Comment by nakulkar-msft** [comment] 2022-02-17 14:18
Duplicate of #832

**Closed by nakulkar-msft** 2022-02-17 14:18 UTC
Labels: duplicate, feature request, aws-s3
