### ISSUE TITLE
Better error message when using AzCopy Benchmark with Read only SAS token

### ISSUE THREAD

**Issue by ringoc** [Azure/azure-storage-azcopy#1518] opened 2021-08-16 11:44 UTC
##### Note: The version is visible when running AzCopy without any argument

➜  ~ azcopy
AzCopy 10.11.0
Project URL: github.com/Azure/azure-storage-azcopy

### Which platform are you using? (ex: Windows, Mac, Linux)

MacOS Apple Silcon 

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy bench "https://[account].blob.core.windows.net/[container]?<SAS>"

### What problem was encountered?

When SAS token contain only permission Read, run the above command will throw out not quite useful error message. 
```

INFO: Trying 4 concurrent connections (initial starting point)
unexpected fault address 0x1061d2acd
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x1061d2acd pc=0x10540fe58]

goroutine 53 [running]:
runtime.throw(0x1054a2e5f, 0x5)
	runtime/panic.go:1117 +0x54 fp=0x140006de360 sp=0x140006de330 pc=0x104d34a24
runtime.sigpanic()
	runtime/signal_unix.go:731 +0x284 fp=0x140006de3a0 sp=0x140006de360 pc=0x104d4c1a4
github.com/Azure/azure-storage-azcopy/v10/common.(*TransferStatus).AtomicLoad(...)
	github.com/Azure/azure-storage-azcopy/v10/common/fe-ste-models.go:676
github.com/Azure/azure-storage-azcopy/v10/ste.(*JobPartPlanTransfer).TransferStatus(...)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobPartPlan.go:358
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).ScheduleTransfers(0x140004a51e0, 0x10582c670, 0x140001d8340)
	github.com/Azure/azure-storage-azcopy/v10/ste/mgr-JobPartMgr.go:392 +0x428 fp=0x140006dff20 sp=0x140006de3b0 pc=0x10540fe58
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).scheduleJobParts(0x140004a4000)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:287 +0x44 fp=0x140006dffd0 sp=0x140006dff20 pc=0x105401f84
runtime.goexit()
	runtime/asm_arm64.s:1130 +0x4 fp=0x140006dffd0 sp=0x140006dffd0 pc=0x104d69f54
created by github.com/Azure/azure-storage-azcopy/v10/ste.initJobsAdmin
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:212 +0x584

goroutine 1 [select (no cases)]:
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).SurrenderControl(0x140003da0e0)
	github.com/Azure/azure-storage-azcopy/v10/common/lifecyleMgr.go:317 +0x20
github.com/Azure/azure-storage-azcopy/v10/cmd.init.0.func2(0x140004a6000, 0x1400046ee80, 0x1, 0x1)
	github.com/Azure/azure-storage-azcopy/v10/cmd/benchmark.go:332 +0x178
github.com/spf13/cobra.(*Command).execute(0x140004a6000, 0x1400046ee60, 0x1, 0x1, 0x140004a6000, 0x1400046ee60)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x105dacb20, 0xf29d885b7558b47f, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute(0x140001b86c0, 0x14, 0x140001b86c0, 0x14, 0x14000203040, 0x1a, 0x7fffffff)
	github.com/Azure/azure-storage-azcopy/v10/cmd/root.go:151 +0xfc
main.main()
	github.com/Azure/azure-storage-azcopy/v10/main.go:82 +0x2d8

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0x140001fa680)
	go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x98
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x70

<OMITTED>

goroutine 130 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:193 +0xc4
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0x140004a4000, 0x1)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:439 +0x104
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:362 +0x4b4

goroutine 131 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:193 +0xc4
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0x140004a4000, 0x2)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:439 +0x104
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:362 +0x4b4

goroutine 132 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:193 +0xc4
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0x140004a4000, 0x3)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:439 +0x104
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:362 +0x4b4

goroutine 133 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:193 +0xc4
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0x140004a4000, 0x4)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:439 +0x104
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
	github.com/Azure/azure-storage-azcopy/v10/ste/JobsAdmin.go:362 +0x4b4

goroutine 146 [runnable]:
os/signal.loop()
	os/signal/signal_unix.go:21
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x44

```

### How can we reproduce the problem in the simplest way?
In MacOS 11.5.1, use brew to install azcopy
brew install azcopy
azcopy login
Generate SAS token for a container within a Storage Account with ONLY Read permission
azcopy bench "https://[account].blob.core.windows.net/[container]?<SAS>"

### Have you found a mitigation/solution?
Using azcopy bench --mode="Download" will at least tell you a 403 error This request is not authorized to perform this operation using this permission. A better error handling would be benefited,

**Comment by jmhungdev** [comment] 2021-12-02 18:37
it needs list permission. or you try using azcopy login if your user already had those permissions.

**Comment by gapra-msft** [comment] 2022-11-22 17:29
Hi @ringoc the above suggestion is correct. You need list permissions in addition to read permissions to use azcopy bench. I will tag this as a documentation request. Thank you again for the feedback!

**Comment by gapra-msft** [comment] 2022-11-22 17:36
Ideally we should check the SAS permissions for at least read and list before starting the process

**Comment by gapra-msft** [comment] 2023-11-01 18:25
I just attempted to reproduce this issue and it looks like benchmark now fails with an error message that indicates lack of permissions. Closing this issue as a result.
 ./azcopy.exe bench "https://XXXXXX.blob.core.windows.net/test?sp=r&st=2023-11-01T18:21:52Z&se=2023-11-02T02:21:52Z&spr=https&sv=2022-11-02&sr=c&sig=Bf6k86Vl1YtLLtY8xKjbaYDZlgq%2BInjCsVbjHQpkj9A%3D"
INFO: Cannot auto-tune concurrency because it is fixed by environment variable AZCOPY_CONCURRENCY_VALUE
INFO: The benchmark feature is currently in Preview status.
INFO: Benchmarking uploads to https://XXXXX.blob.core.windows.net/test/benchmark-82be6f96-4838-b743-55ab-f50c80ba930b.
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 82be6f96-4838-b743-55ab-f50c80ba930b has started
Log file is located at: C:\Users\XXXXX\.azcopy\82be6f96-4838-b743-55ab-f50c80ba930b.log

INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PUT https://XXXXXX.blob.core.windows.net/test/benchmark-82be6f96-4838-b743-55ab-f50c80ba930b/22
--------------------------------------------------------------------------------
**RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
ERROR CODE: AuthorizationPermissionMismatch**
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:de5f09fa-601e-0066-3bf0-0c3efd000000
Time:2023-11-01T18:22:39.0785933Z</Message></Error>
--------------------------------------------------------------------------------

0.0 %, 0 Done, 0 Failed, 100 Pending, 0 Skipped, 100 Total, 2-sec Throughput (Mb/s): 17.3212p

**Closed by gapra-msft** 2023-11-01 18:25 UTC
Labels: enhancement, documentation update, usability and error messages, docs
