### ISSUE TITLE
Fixed Width File Problem

### ISSUE THREAD

**Issue by bcallandsi** [Azure/azure-storage-azcopy#963] opened 2020-04-15 15:33 UTC
### Which version of the AzCopy was used? 
10.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016 Datacenter
### What command did you run?
azcopy.exe copy "source details" "destination" --include-pattern "File.txt"
### What problem was encountered?
The local copy of the file does not include any line breaks. The file is a simple fixed width text file, but does not transfer properly on Windows Server. I can execute the same command from my development laptop (Windows 10) and retrieve the file without a problem.

**Comment by JohnRusk** [comment] 2020-04-15 23:54
AzCopy never looks at line breaks in files.  So it seems unlikely that line breaks would be the issue here. 

When you say it "does not transfer properly on Windows Server", can you provide some more details on what you mean?

**Comment by bcallandsi** [comment] 2020-04-16 13:34
Hi John,

I agree that it is a strange issue.
Here is what the file looks like when copied to the server (I have replaced the sensitive data):
[cid:4614a72c-0b48-4c3c-9371-0a912d1c19bb]
And here is what the file looks like when copied in any other environment:
[cid:3400556b-030b-4f54-a6c5-3d584a8e0ff1]
Any thoughts on what could be causing the difference? Maybe environment variables?

Thanks for any help you can provide.

Brad



.[cid:DSI20YearLogo_JPEG-01_9b308aa1-6f05-4d2b-9d1e-fee704062bcc.jpg]<https://www.dstrat.com/>

Brad Callan
Cloud Solution Architect - Data Visualization • Dimensional Strategies Inc.
phone: +1-647-317-4101
503 - 5450 Explorer Drive Mississauga, Ontario L4W 5N1


<http://www.dstrat.com/><http://www.dstrat.com/><https://ca.linkedin.com/company/dstrat>[cid:Untitled-6_e5fa7a55-e9d6-4e9b-8f0f-38e011287e3a.jpg]<http://www.dstrat.com/>[cid:npm_linkedin-icon_0e50cc74-649d-425d-a7c6-a8c44d3271fb.gif]<https://ca.linkedin.com/company/dstrat><http://www.dstrat.com/><http://www.dstrat.com/>
<https://conta.cc/31BgFhE><https://conta.cc/31BgFhE><https://conta.cc/31BgFhE><https://myemail.constantcontact.com/Register-Now-for-Microsoft-Power-BI-Workshops-offered-exclusively-by-DSI.html?soid=1117182617477&aid=LKwskFA-_sA>[cid:ForecastReadyEmailSignature-01_ec7c577f-9653-4715-bd15-974687e73714.jpg]<https://forecastready.com/>
.

________________________________

**Comment by JohnRusk** [comment] 2020-04-16 21:27
@bcallandsi The attachments don't seem to have come through. Looks like you emailed that comment. Can you try re-doing it through web UI rather than email?

BTW, how are you checking the content of the uploaded file? Just by clicking on it and opening it in a browser or something?  if so, I'd suggest downloading it to disk, and opening it with the exact same tool (e.g. text editor) that you open the original one with.  Just in case they are actually the _same_ and the issue is just related to either
(a) tooling or 
(b) the Content-Type that has been assigned to the file at the time of upload.

**Comment by bcallandsi** [comment] 2020-04-17 15:20
Hi John.

We have changed the process that was creating the text files to add windows line breaks explicitly. This has resolved the issue. If you know of a way for AZCopy to handle this issue without the extra scripting step I would like to know. If not, we are OK.

For background we were replacing a process that was using FTP with AZCopy. The tool I was using to check the files on each environment was Notepad after saving the file to disk. This is what made the error so strange. The server was hosting an ETL process and thus was failing as the source file was expected to be read in a fixed width format.

Thanks for looking into this.

Brad


.[cid:DSI20YearLogo_JPEG-01_9b308aa1-6f05-4d2b-9d1e-fee704062bcc.jpg]<https://www.dstrat.com/>

Brad Callan
Cloud Solution Architect - Data Visualization • Dimensional Strategies Inc.
phone: +1-647-317-4101
503 - 5450 Explorer Drive Mississauga, Ontario L4W 5N1


<http://www.dstrat.com/><http://www.dstrat.com/><https://ca.linkedin.com/company/dstrat>[cid:Untitled-6_e5fa7a55-e9d6-4e9b-8f0f-38e011287e3a.jpg]<http://www.dstrat.com/>[cid:npm_linkedin-icon_0e50cc74-649d-425d-a7c6-a8c44d3271fb.gif]<https://ca.linkedin.com/company/dstrat><http://www.dstrat.com/><http://www.dstrat.com/>
<https://conta.cc/31BgFhE><https://conta.cc/31BgFhE><https://conta.cc/31BgFhE><https://myemail.constantcontact.com/Register-Now-for-Microsoft-Power-BI-Workshops-offered-exclusively-by-DSI.html?soid=1117182617477&aid=LKwskFA-_sA>[cid:ForecastReadyEmailSignature-01_ec7c577f-9653-4715-bd15-974687e73714.jpg]<https://forecastready.com/>
.

**Closed** 2021-09-08 19:07 UTC
Labels: need more info
