### ISSUE TITLE
AzCopy sync, and log file 

### ISSUE THREAD

**Issue by dmitrychastikov** [Azure/azure-storage-azcopy#874] opened 2020-02-21 08:12 UTC
### Which version of the AzCopy was used? 
10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
c:\tools\azcopy\azcopy sync "$Source$SAS" "$Destination$SAS" --recursive=true

### What problem was encountered?
When started I can read the console output:
Job dffb263f-b714-214b-7a38-0db0f556378a has started
Log file is located at: C:\Users\Berta\AzCopyBackupData\Log_Concur1\dffb263f-b714-214b-7a38-0db0f556378a.log
But the log file does not exist there until after the comparison of source and destination is done.
When it appears (in my case the comparison takes 30 minutes) it show something like:
2020/02/21 06:13:11 AzcopyVersion  10.3.4
2020/02/21 06:13:11 OS-Environment  windows
...
2020/02/21 06:13:11 Max concurrent transfer initiation routines: 64 
....
2020/02/21 06:13:11 ERROR: No transfers were scheduled.
Notice the moment in time - it is the last second of the 30 minutes interval that the program was running.

The first line should correspond to the moment of start.
The log file should be immediately committed to disk so that it can be followed.
The last one ERROR: No transfers were scheduled. in this particular case is plain wrong, it must be INFO:  No transfers were scheduled. 
Console output shows at the end of scan: 995328 Files Scanned at Source, 995328 Files Scanned at Destination, 2-sec Throughput (Mb/s): 0
The source and destination are already in sync.

That's correct. But this valuable information does not go into the log.

### How can we reproduce the problem in the simplest way?
Just run c:\tools\azcopy\azcopy sync "$Source$SAS" "$Destination$SAS" --recursive=true on an an account with big enough amount of blobs

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment] 2020-02-23 21:48
Thanks for the info.  Originally AzCopy v10 was designed to be a two-part product, with a daemon-like transfer engine receiving jobs from a command-line front end.  That split still exists to some extent, and its the transfer engine that does the logging - which is why logging is not done earlier.  We agree that the side effect, of no logging at scan time, is undesirable and should be fixed.

**Comment by dmitrychastikov** [comment] 2020-02-25 11:06
@JohnRusk Please take into account that it's not the absence of the log at scan time is the biggest problem here. Rather, the plain wrong is logged is the time of writing into the log instead of the moment of the operation itself, And that the equality of containers (the absolute best possible for sync!) is reported as an error.

**Comment by gapra-msft** [comment] 2023-10-31 21:34
Hi @dmitrychastikov we intend to change this error log to a warning. I have a PR out for it, and it should be available in one of our upcoming releases. I will go ahead and close this issue once it is fixed in dev. Thank you again for reporting it.

**Comment by gapra-msft** [comment] 2023-11-09 02:52
Closing this since a PR has been merged. This will be resolved in our next release.

**Closed by gapra-msft** 2023-11-09 02:52 UTC
