### ISSUE TITLE
Where can I download a specific version of AzCopy v10?

### ISSUE THREAD

**Issue by mazong1123** [Azure/azure-storage-azcopy#233] opened 2019-02-22 19:11 UTC
Currently I only found a general link to download the latest version of azcopy: https://aka.ms/downloadazcopy-v10-windows

We'd like to use scripts to download and deploy the specific version of AzCopy instead of always deploying the latest one, which could introduce in-consistency across our environment. Is that possible to provide links to specific version of AzCopy v10? Thanks!

**Comment by zezha-msft** [comment] 2019-02-22 19:59
Hi @mazong1123, thanks for reaching out!

I apologize for the inconvenience. But we currently do not provide separate links because the project is still in preview, as we want users to always pick up the latest version with the fixes.

The address behind the aka.ms is https://azcopyvnext.azureedge.net/release20190128/azcopy_windows_amd64_10.0.7.zip. So you could pin to that instead.

**Comment by mnisb3537** [comment] 2019-04-24 05:34
Can you provide the address for azcopy_linux_amd64_10.0.9.tar.gz as well?

**Comment by JohnRusk** [comment] 2019-04-24 07:43
The official release (GA not preview) is now available with version number 10.1.0. Can you use that instead of the older 10.0.9 version? If so, that would be the recommended approach .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JohnRusk** [comment] 2019-10-11 08:19
@EvertEt there were some issues about - - include in complex cases. (in terms of understabdability and consistency between the various supported source types, eg local files, blobs). So it has been split into two separate parameters with new names. The main public documentation is about to be updated. In the meantime, to supplement the info that is already in the change log for the release, here's an informal description

--include-pattern and --exclude-pattern apply to filenames. (Just the name part, not the path). So for instance, if you wanted to copy all .txt files in a directory tree, you would use –recursive (to get the whole tree) and –include-pattern *.txt, to get all the text files.

--include-path and –exclude-path are just appended to the source directory. So for instance, if you are transferring d:\mydata and you use –include-path photos;documents\aaa.txt, then AzCopy will transfer d:\mydata\photos and d:\mydata\documents\aaa.txt. (BTW, if d:\mydata\photos is a directory, you also need –recursive, otherwise the files in it will not be copied).

**Comment by JohnRusk** [comment] 2019-10-11 08:54
The recommended procedure for downloading specific versions is documented here https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#use-azcopy-in-a-script

**Comment by bendavis78** [comment] 2021-09-03 14:48
How can I download an earlier minor version of azcopy 10? `10.11` is breaking for me, I need `10.10`.

**Comment by amishra-dev** [comment] 2021-09-03 19:59
@bendavis78 is this about https://github.com/Azure/azure-storage-azcopy/issues/1527?

**Closed by amishra-dev** 2021-09-03 19:59 UTC

**Comment by nshetty15** [comment] 2022-08-16 06:20
https://github.com/Azure/azure-storage-azcopy/releases
download links are mentioned here for older versions

**Comment by nshetty15** [comment] 2022-08-16 07:03
I came across a breaking change in the latest version. (we pull the binary in Dockerfile). Looks like azcopy older version download links are not provided anywhere.

Below is what typical download link looks like..
https://azcopyvnext.azureedge.net/release20220721/azcopy_linux_amd64_10.16.0.tar.gz

From this page I can see the release version and approx. release date: 
https://github.com/Azure/azure-storage-azcopy/releases

I just used this info to form the below URL (might have to try few dates around the release date):
https://azcopyvnext.azureedge.net/release20220511/azcopy_linux_amd64_10.15.0.tar.gz

**Comment by zezha-msft** [comment] 2022-08-16 22:29
Hi @nshetty15, which breaking change are you referring to?

Here is the link for 10.15: https://azcopyvnext.azureedge.net/release20220511/azcopy_linux_amd64_10.15.0.tar.gz

**Comment by nshetty15** [comment] 2022-08-17 02:52
@zezha-msft 
we were using https://aka.ms/downloadazcopy-v10-linux to download the azcopy binary in the dockerfile.
However since latest release(10.16.0), when running azcopy its trying to write something into $HOME and failing with permission denied error.
The earlier version, 10.15.0 does not write files to $HOME.

**Comment by zezha-msft** [comment] 2022-08-22 20:31
@nshetty15 that's surprising to hear, as the logs/plans are placed under $HOME/.azcopy by default, and this behavior has not changed since the beginning of the tool.

In general, it's better to pin to a specific static link for scripted workflows: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#obtain-a-static-download-link

**Comment by nshetty15** [comment] 2022-08-24 12:04
@zezha-msft  I was seeing this error even after setting below env variable.
export AZCOPY_LOG_LOCATION=/opt/myapp/azlogs
I assume, setting this env var means that azcopy would not write to $HOME dir.

**Comment by ValKiriann** [comment] 2022-10-19 09:05
Could you help us with the az Copy link for the 10.13.0 version? we have azure DevOps pipelines that use the az storage command and as of today, they are not working because they tried to download the binary and got a 409 error. 

I tried to download the latest and move it to the AzDevOps agent home, but the cli wants only that version, I don't know how to force him to use the last one so we cant perform any deploys at the moment.

**Comment by zezha-msft** [comment] 2022-10-19 17:58
Hi @ValKiriann, we did not change anything, maybe it was a transient issue on the CDN. Does it work now?

**Comment by ValKiriann** [comment] 2022-10-20 05:17
Hi @zezha-msft, I can confirm this is still happening when launching azure DevOps Pipelines with our own Linux agents. We have been not able to perform any deploy since yesterday. more than 24 hours now with the issue. I am a bit worried about this. we Also wrote an Azure case with no response.

**Comment by zezha-msft** [comment] 2022-10-20 17:54
@ValKiriann I tried the link and it's working fine from my home network. Could you please also try on your workstation?

**Comment by ValKiriann** [comment] 2022-10-20 20:07
It is still not working I'm afraid :(

we had to compile the 10.13 version based on your repository tag and placed it on our agents to be able to continue to work in our company. We were having a huge delay with our deployments and it was a high risk. You can find more people having the same problem in the issue I've opened yesterday: 

https://github.com/Azure/azure-storage-azcopy/issues/1933

which by the way it is still unassigned.
