### ISSUE TITLE
Cannot upload files that contain percent sign in name.

### ISSUE THREAD

**Issue by f1guru** [Azure/azure-storage-azcopy#2349] opened 2023-08-23 14:30 UTC
Version: Latest release (10.20.1)
Platform: Windows Server 2012 R2

azcopy sync "D:\LocalFolder\MoreFolders" "https://_mybloburl_.blob.core.windows.net/_blobcontainer/path/to/another/folder/_" --dry-run=true

Fails when a file containing a percent sign in the name is encountered (e.g. "Outlines Done - 50% Contrast.psd"):
```
...
DRYRUN: copy E:\Shared\\_Blob Storage Ready\_Test\0_Archive\Links\filename.psd to https://mybloburl.blob.core.windows.net/blobcontainer/path/to/another/folder/filename.psd
panic: invalid URL escape "%.p"

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
        D:/a/1/s/common/lifecyleMgr.go:696
github.com/Azure/azure-storage-azcopy/v10/cmd.(*copyTransferProcessor).scheduleCopyTransfer.func1(0x22cbc28?)
        D:/a/1/s/cmd/zc_processor.go:108 +0x8a9
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).Dryrun(0xc000384120, 0x6f?)
        D:/a/1/s/common/lifecyleMgr.go:327 +0x31
github.com/Azure/azure-storage-azcopy/v10/cmd.(*copyTransferProcessor).scheduleCopyTransfer(_, {{0xc0000be2c0, 0x3a}, 0x
0, {0x0, 0xebea1a770, 0x18df580}, {0x0, 0x0, 0x0}, ...})
        D:/a/1/s/cmd/zc_processor.go:101 +0x5df
github.com/Azure/azure-storage-azcopy/v10/cmd.processIfPassedFilters({_, _, _}, {{0xc0000be2c0, 0x3a}, 0x0, {0x0, 0xebea
1a770, 0x18df580}, {0x0, ...}, ...}, ...)
        D:/a/1/s/cmd/zc_enumerator.go:786 +0x9f
github.com/Azure/azure-storage-azcopy/v10/cmd.(*objectIndexer).traverse(0x0?, 0x0?, {0x1937838, 0x0, 0x0})
        D:/a/1/s/cmd/syncIndexer.go:67 +0x138
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedSyncCmdArgs).initEnumerator.func3()
        D:/a/1/s/cmd/syncEnumerator.go:166 +0x65
github.com/Azure/azure-storage-azcopy/v10/cmd.(*syncEnumerator).enumerate(0xc00006cb90)
        D:/a/1/s/cmd/zc_enumerator.go:695 +0xc3
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedSyncCmdArgs).process(0xc0002d4e00)
        D:/a/1/s/cmd/sync.go:714 +0x592
github.com/Azure/azure-storage-azcopy/v10/cmd.init.20.func2(0xc000412280?, {0xc000068c00?, 0x2?, 0x4?})
        D:/a/1/s/cmd/sync.go:750 +0x211
github.com/spf13/cobra.(*Command).execute(0xc000412280, {0xc000068bc0, 0x4, 0x4})
        C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x18d0360)
        C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc00002e5d0?, 0xc0000880e0?}, {0xc00002e690?, 0x104b544?}, 0x74?
, {0x2e6a7f0b, 0xbbfa, 0xac4d, {0x40, 0x87, ...}})
        D:/a/1/s/cmd/root.go:192 +0x106
main.main()
```
To reproduce, simply try to upload a folder containing files named with a percent sign.

I can find no way to workaround this.  No matter what order the percent is in (i.e. before or after space, before or after number before or after a-z, before or after a "/" or "." it causes the above error.  The worst part is...it doesn't even have the decency to tell you exactly what file it failed on.

This is all that is present in the log file:
```
2023/08/23 14:17:48 AzcopyVersion  10.20.1
2023/08/23 14:17:48 OS-Environment  windows
2023/08/23 14:17:48 OS-Architecture  amd64
2023/08/23 14:17:48 Log times are in UTC. Local time is 23 Aug 2023 10:17:48
2023/08/23 14:17:48 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2023-08-23T14:17:43Z or --include-after=2023-08-23T14:17:43Z
2023/08/23 14:17:48 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
```

The weird thing is, it looks like this was resolved 3 years ago via #1051 so maybe this is a reversion of the bug?

**Comment by f1guru** [comment] 2023-08-29 14:41
FYI, after some trial and error downloading older copies, this broke on version 10.16.0.  It works fine on 10.15.0.

**Comment by gapra-msft** [comment] 2024-01-16 20:37
Hi @f1guru I am unable to reproduce this in the latest version of AzCopy. Have you tried upgrading to the latest version?

**Comment by gapra-msft** [comment] 2024-01-22 21:56
Closing as this is not reproducible in latest versions of AzCopy.

**Closed as completed by gapra-msft** 2024-01-22 21:56 UTC
Labels: waiting for customer

**Comment by f1guru** [comment] 2024-01-23 13:01
Yes, I confirmed the latest 10.22.2 does not have this issue so it looks like somewhere along the line someone either intentionally or unintentionally reverted back the code the was breaking this.
