### ISSUE TITLE
azcopy tool is copying many files though there is single file in a directory

### ISSUE THREAD

**Issue by thiszparveen** [Azure/azure-storage-azcopy#1446] opened 2021-05-19 11:54 UTC
### Which version of the AzCopy was used? 
AzCopy 10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp "S:/Shared Documents/Stuff I Am Learning" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]" --recursive

### What problem was encountered?

The source folder (S:/Shared Documents/Stuff I Am Learning) contains only a single file, but still azcopy tool is calculating the size differently . See the below the number is keep on increasing, though we have couple of files to copy from the source folder.

0.0 %, 0 Done, 709 Failed, 19291 Pending, 0 Skipped, 20000 Total (scanning...),
0.0 %, 23 Done, 9043 Failed, 40934 Pending, 0 Skipped, 50000 Total (scanning...), 2-sec Throughput (Mb/s): 5.0014

### How can we reproduce the problem in the simplest way?
Sharepoint repository is mapped as network drive. And then i am using azcopy copy tool to transfer the data to Azureblob. This is happening only with sharepoint sites.

**Comment by nakulkar-msft** [comment] 2021-05-19 12:04
@thiszparveen Do you have hidden files in the directory? AzCopy would copy hidden files as well.

**Comment by thiszparveen** [comment] 2021-05-19 12:33
@nakulkar-msft  - No  hidden files. 
Also one more observation:

When I user "/*" and remove the "--recursive" then only that file is being copied. But folder structure is missing. When i use recursive, then same issue mentioned above.

azcopy cp "S:/Shared Documents/Stuff I Am Learning/*" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]"

**Comment by nakulkar-msft** [comment] 2021-05-19 14:16
@thiszparveen Sorry, I misread the command earlier. This is the expected behaviour. '*' will copy files in the given directory. With '--recursive' parameter, azcopy will scan sub-directories as well. Blob storage does not support directories, and unless there is a blob transferred in the sub-directories, the directory structure will be missing.

azcopy help shows below

```
Upload an entire directory by using a SAS token:

  - azcopy cp "/path/to/dir" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]" --recursive=true
or
  - azcopy cp "/path/to/dir" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]" --recursive=true --put-md5

Upload a set of files by using a SAS token and wildcard (*) characters:

  - azcopy cp "/path/*foo/*bar/*.pdf" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]"

Upload files and directories by using a SAS token and wildcard (*) characters:

  - azcopy cp "/path/*foo/*bar*" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]" --recursive=true

```

**Comment by thiszparveen** [comment] 2021-05-19 14:21
@nakulkar-msft  - I got the point that recursive will transfer sub directories as well, where as /* will transfer only content not the folders.

But in my case, i don't have any sub directories in the above specified source path. I just have a single file, no folders.
So when i copy this with /* it is showing that only 1 file, which is correct and transfer is very quick. Where as --recursive, keep on processing thousand of files, though i have only 1 file. This happening only incase of sharepoint connected drives. Other networkdrive transfer is working as expected.

**Comment by nakulkar-msft** [comment] 2021-05-19 14:23
Can you attach the log file here? All the secrets are redacted and you dont have to worry about that.

**Comment by thiszparveen** [comment] 2021-05-19 14:41
2021/05/19 14:34:10 AzcopyVersion  10.10.0
2021/05/19 14:34:10 OS-Environment  windows
2021/05/19 14:34:10 OS-Architecture  amd64
2021/05/19 14:34:10 Log times are in UTC. Local time is 19 May 2021 20:04:10
2021/05/19 14:34:10 Job-Command cp S:/Shared Documents/Stuff I Am Learning https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS] --recursive 
2021/05/19 14:34:10 Number of CPUs: 8
2021/05/19 14:34:10 Max file buffer RAM 4.000 GB
2021/05/19 14:34:10 Max concurrent network operations: 128 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2021/05/19 14:34:10 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2021/05/19 14:34:10 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2021/05/19 14:34:10 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2021/05/19 14:34:10 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2021/05/19 14:34:10 Max open files when downloading: 2147483119 (auto-computed)
2021/05/19 14:34:10 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2021-05-19T14:34:01Z or --include-after=2021-05-19T14:34:01Z
2021/05/19 14:34:10 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2021/05/19 14:34:10 JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, credential type: Anonymous
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=0, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=1, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=2, priority=0
2021/05/19 14:34:10 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 11
2021/05/19 14:34:10 0.0 %, 0 Done, 0 Failed, 10000 Pending, 0 Skipped, 10000 Total (scanning...), 
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=3, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=4, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=5, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=6, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=7, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=8, priority=0
2021/05/19 14:34:10 scheduling JobID=1d816626-f4cc-4649-4c46-84131e2c28f1, Part#=0, Transfer#=9, priority=0

**Comment by thiszparveen** [comment] 2021-05-19 14:47
> [](url)

**Comment by thiszparveen** [comment] 2021-05-19 15:37
@nakulkar-msft  
Could you please confirm if you received the log, as i am seeing the error "is not included in the list" while uploading

**Comment by nakulkar-msft** [comment] 2021-05-25 05:48
@thiszparveen Log file is incomplete. Can you mail the entire file? Email address is on my profile

**Comment by thiszparveen** [comment] 2021-05-27 14:32
@nakulkar-msft  - Below is the error message i am seeing log.
 2021/05/27 14:29:15 ERR: [P#0-T#46] UPLOADFAILED: %5C%5C?\Q:\Forms\template.dotx : 000 : cannot simultaneously send two files to same destination name

**Comment by gapra-msft** [comment] 2023-11-15 18:23
@thiszparveen are you still having difficulty with AzCopy? From the error log, it looks like you may have duplicate files that resolve to the same name.

**Closed** 2023-11-27 17:36 UTC
Labels: waiting for customer
