### ISSUE TITLE
Do we need to write logs to `~/.azcopy` directory?

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-storage-azcopy#221] opened 2019-02-20 17:25 UTC
### Which version of the AzCopy was used? 
/azcopy_linux_amd64_10.0.7/azcopy

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What problem was encountered?
Logs are written to `~/.azcopy` directory as per:

```
Log file is located at: /home/ppanyukov/.azcopy/99599e85-8ef6-d844-595e-ca9c12a8f762.log
```

I would say this is not what programs on Linux normally do. Certainly writing logs to a dot directory in user's home feels very unorthodox.

My preference would be to write to `stdout` and `stderr` as appropriate by default, with a possible option to specify `--log` parameter or similar to override this (not even sure this is necessary as I can easily redirect `stdout/stderr` to wherever if I need to).

What are people's thoughts on this?

----

Possible hacky workaround for this: run `azcopy` in a docker container, this will make sure logs don't get stored anywhere locally for a long time. On the other hand, if logs *are* required, this running in docker surfaces other issues.

**Comment by zezha-msft** [comment] 2019-02-20 23:15
Hi @ppanyukov, thanks for reaching out!

I understand and appreciate your perspective. However, we'd prefer to save the log as a file, since there could be a lot of useful information, if any transfer ever goes wrong. If we accepted a --log-file-location flag, what if the user doesn't provide one? One option would be to save the log file in the current directory, from where the user is running the command; but this is not a great practice either since the user could be in the directory were they are trying to upload data from, and putting the log file there is undesirable.

You could customize the log location. Please refer to `./azcopy env`.

**Comment by ppanyukov** [comment] 2019-02-21 01:14
Well, I'm sure this is done out of best intentions and I agree it's a good thing to have logs, but also programs for Linux should probably strive to fit into what is customary for Linux.  As I pointed out, I think it is more standard to write to `stdout/stderr` rather than in dot directories in user's home such as `~/.azcopy`.

Why not take `rsync` as a model for a tool that does pretty much the same kind of job and is well established?  That is not to say `rsync` is ideal, it's what people probably used and are likely to be familiar with.

BTW, I just discovered there is also `~/.azcopy/plans` directory which keeps growing.  Is this something that needs to be kept after the job finished?

Oh, and if we had `--log-file` parameter or env var `AZCOPY_LOG_FILE_LOCATION` (rather than directory), we could give it `/dev/stderr` and that might kinda solve this.

**Comment by zezha-msft** [comment] 2019-02-21 21:09
Hi @ppanyukov, thank you for the suggestions!

`~/.azcopy/plans` contains the state files that allow AzCopy to resume failed jobs. They also allow the user to list all the jobs that ran in the past and query their results with `./azcopy jobs list` and `./azcopy jobs show [job-ID]. We currently do not have a strategy to get rid of these files, as we don't know how long the user wants to keep records of their old jobs.

I understand your concern, but it may be challenging to change the logging to output on stdout/stderr, since we already have interactive outputs that give the user progress updates. Logs are critical in helping our customers to investigate issues, as they could be very verbose and offer loads of useful information.

We can certainly add some kind of `clean` command that gets rid of these logs and plan files. Would that be a reasonable solution for you?

**Comment by ppanyukov** [comment] 2019-02-27 18:53
So, if we run `sync` command every 2 minutes or so, there will be quite a few "plan" files left behind?

I appreciate there may be several design goals here, and logging in general is not an easy thing.

Adding `clean` command does not seem to achieve anything more than me running `rm -rf ~/.azcopy` after every run unless I'm mistaken?

Well anyway, I'm probably not super fussed about this issue right now, considering the `rm -rf` workaround and we are not using this tool anywhere near production or anything serious yet, although it's on the table as one of the options.

**Comment by zezha-msft** [comment] 2019-02-27 19:35
Hi @ppanyukov, thanks for your feedback! We'll look into improving this part of the user experience. 

The reason why I suggested `clean` is because the user could specify another location for logs through an environment variable. It'd be pretty convenient to just call azcopy to remove both the logs and plan files.

What if we provided a flag to indicate that we should delete the logs&plan files if the job succeeds without error? Would you prefer this behavior?

On a side note, we've worked on shrinking the size of the plan files, which will be out with the next release.

**Comment by arnobf** [comment] 2019-03-12 08:22
@zezha-msft for our use case, a flag to delete logs&plan files in case of success - as you mentioned - would be very welcome.

**Comment by jtmoree-kahalamgmt-com** [comment] 2019-05-22 18:48
+1 on not writing files to disk and expecting the user to figure out where they are and clean them up later.  

> we'd prefer to save the log as a file, since there could be a lot of useful information, if any transfer ever goes wrong. If we accepted a --log-file-location flag, what if the user doesn't provide one? 

If the user does not specify a log file location it's because the user doesn't want the log files filling up his disk.  Forcing the user to accept log files forces everyone to write extra code to handle a situation which should not exist in the first place.  We dont need to force every person using this utility to deal with files they don't need.   When the support call comes in we would tell the person to use the log option and send us the output.  This is standard practice for well written software.

Furthermore, the environment variable doesn't affect the plans folder and files.  They are still written to the users home folder which means using the env var increases the amount of work everyone has to do.  Now we have to delete files from two locations.

If we cannot stop the log and plans files in the short term a 'clean' option is the next best thing.

**Comment by JohnRusk** [comment] 2019-05-22 20:08
Thanks.  As noted in #259, we're aiming to provide a cleanup option and to make various other improvements.  Thanks for pointing out the issue with plan files not also moving.  I've added a specific tracking item for that to our backlog.

**Comment by kovas6** [comment] 2019-06-06 15:24
I have to copy 4TB small files between two storage accounts and having all that logging you force is absolute nightmare, I had to create extra disk for which I will be charged just in order to keep those logs I would never read

**Comment by adreed-msft** [comment] 2019-06-06 15:43
Hi, kovas6. We're trying to reduce the logging at the moment. If I catch some spare time, I'll look into adding a global flag into AzCopy to turn logs off.

**Comment by JohnRusk** [comment] 2019-06-06 22:03
@kovas6 (cc @adreed-msft). You can already turn the logs off.  Just put this on the command line:

`--log-level NONE`

(Although I recommend using --log-level ERROR instead.  That doesn't eliminate logs, but it does keep them very small).

**Comment by kovas6** [comment] 2019-06-07 06:30
`--log-level NONE`
is it documented anywhere?

**Comment by kovas6** [comment] 2019-06-07 11:27
another problem 30gb of PLANS folder and still it keeps growing while I am copying data between storage accounts. I am running out of disk space on C drive.
Any way we could disable those plans or at least move them to another folder/drive?

**Comment by jtmoree-kahalamgmt-com** [comment] 2019-06-07 14:03
> @kovas6 (cc @adreed-msft). You can already turn the logs off. Just put this on the command line:
> `--log-level NONE`

--log-level NONE and --log-level=NONE act exactly the same as log-level ERROR.  azcopy still outputs plan files and a log file including the same content as when ERROR is set as the level.  

Furthermore, using azcopy --help says nothing about the log-level option.  google finds nothing accurate about the log level options.  The README in the azcopy source code says nothing about log levels.

This page mentions log levels and does not list NONE but since it does not work that is a bit moot.  https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure

**Comment by JohnRusk** [comment] 2019-06-09 21:57
Oh, I'm surprised that NONE didn't work! Thanks for letting us know.

**Comment by JohnRusk** [comment] 2019-06-09 22:02
@kovas6 Yes, we're aware of the plans issue and it's on our list to make it moveable.

**Comment by jtmoree-kahalamgmt-com** [comment] 2019-06-10 14:38
> @kovas6 Yes, we're aware of the plans issue and it's on our list to make it moveable.

"make it movable" ?  does that mean that plans files will still be written even if the NONE issue is fixed?  Is there an issue/bug/item for it?

**Comment by jtmoree-kahalamgmt-com** [comment] 2019-06-10 14:42
> Oh, I'm surprised that NONE didn't work! Thanks for letting us know.

shall I open an issue for NONE?  

p.s.  if you didn't know it was broken then there must not be a test case for it.   I see some test code in the source.   Is the test suite maintained and run as part of development and release?  There is GO and PYTHON code.  is the testing spanning two different languages?

**Comment by JohnRusk** [comment] 2019-06-10 22:07
Yes, we do have two test suites: currently unit tests are in Go and integration tests are in Python.  It does appear that the NONE case was not tested for.  I think we'll track the NONE issue against this issue here, so no need to open another.

**Comment by JohnRusk** [comment] 2019-06-10 22:12
>does that mean that plans files will still be written even if the NONE issue is fixed? Is there an issue/bug/item for it?

There's no way to not write the plan files.  They're essential to the way AzCopy works.  At first glance, that may seem like a bad thing. However, counter-intuitively perhaps, I believe it's actually a good thing. Before joining the AzCopy team, I spent a couple of years on an experimental tool that did not use plan files - instead it stored the equivalent information only in memory.  I found that that caused more problems (e.g. around reliability, retries and restarts; and also around supporting high file counts with low memory).  So, plan files are the best known option.  But there are two things we do need to work on:
(a) making them moveable and
(b) better cleanup of the plan files from completed jobs.
We have work planned for both of those.

**Comment by adreed-msft** [comment] 2019-07-05 16:03
Hi there, while this doesn't totally fix up this issue, log-level none is now fixed and present in AzCopy v10.2.x. Work is still planned for moving plan files and having better cleanup options. Enjoy!

**Comment by JohnRusk** [comment] 2019-09-23 03:49
A settable plan file location, and azcopy commands to cleanup old files, are coming in version 10.3

**Comment by SteveBurkettNZ** [comment] 2019-10-03 21:46
[Docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#change-the-default-log-level) needs an update to reflect the NONE option?

Also noted the in-app help text (azcopy cp --help) doesn't mention the DEBUG or PANIC options that the documentation does.

**Comment by JohnRusk** [comment] 2019-10-03 21:50
@normesta Any chance of squeezing the addition on NONE into the docs? (If too late for this release, I think that's OK too).

**Comment by normesta** [comment] 2019-10-03 22:50
@JohnRusk - of course. Seems like a simple add to the docs. I assume NONE means no logging at all?

**Comment by JohnRusk** [comment] 2019-10-03 22:55
@normesta Correct.  But...

… the log-level parameter only controls the logging that we do to the AzCopy log file.  There is also lower-level logging, of network errors and slow network calls, to the Event Log (windows) and Syslog (Linux).  Maybe it would be worthwhile pointing out that _that_ logging happens regardless of the setting of the --log-level parameter.

**Comment by JohnRusk** [comment] 2019-10-10 04:38
BTW, Steve, I suspect that PANIC and FATAL might not actually work. (they come from a library we refer to, but I'm not sure AzCopy actually implements them.).  We should check, and correct the documentation if it is the doc which is in error.

**Comment by JohnRusk** [comment] 2019-10-11 00:48
>A settable plan file location, and azcopy commands to cleanup old files, are coming in version 10.3

Version 10.3 is now released.  Details are here: https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.3.0

**Comment by jtmoree-kahalamgmt-com** [comment] 2019-10-11 14:37
I disagree that this issue is resolved.  at the very least that the resolution is not better than the situation before.

Given that azcopy left plan files sitting around before version 10.3 I was already cleaning the files up myself by extracting job information from the output.  If I understand the new feature I will still have to extract the job ID from the output of azcopy and take extra steps to get the files cleaned up.

I cannot use jobs clean if I am running multiple jobs concurrently and because that would trash the other jobs?  Am I correct in my understanding of the situation?

I thought I recalled discussion of a switch to azcopy which would tell it to clean up all files when it was done with the current run.  That would be the cleanest way to handle the plan files.

**Comment by adreed-msft** [comment] 2019-10-15 21:36
We did have discussion of that (namely cleaning up all azcopy-created job-related files on a job success), and I'd implemented it a while back. If I recall correctly, we ended up deciding that we'd talk about how to tackle the job cleanup strategy in the future.

@zezha-msft and @JohnRusk, thoughts on re-implementing that cleanup strategy? It was an opt-in solution, rather than an opt-out solution, which means that if a user took issue with their transfer with the flag on, they could just re-run it with the flag off and we'd have debug info.

**Comment by jtmoree-kahalamgmt-com** [comment] 2019-10-15 22:02
Could you clarify for me?  What did you implement?  Is there a switch that will tell azcopy to clean up after itself for one job?  or are you referring to a feature which was never integrated?  or is this the current jobs clean feature?

**Comment by JohnRusk** [comment] 2019-10-16 05:13
It was not implemented. One of the reasons was that this, "if a user took issue with their transfer with the flag on, they could just re-run it with the flag off and we'd have debug info", doesn't really work for users with very long-running jobs. E.g. if you spent 6 hours running AzCopy, have a question about it (but it's cleaned up the log because it thought it succeeded) you're not going to want run the 6 hour job again to get a log. 

Even for short running jobs, we're concerned about what effect that model would have on users.  E.g. we get a number of performance-related support requests.  The job didn't necessarily fail, but just ran slowly. With automatic deletion on success status, those become very difficult to offer support for, because the log gets deleted.

We haven't totally ruled out some kind of automatic deletion in the future, but we want to make sure that we find ways to do it that don't compromise supportability. Therefore, in 10.3.x, we've added jobs clean (and jobs rm) but have not added automatic deletion.

**Comment by JohnRusk** [comment] 2019-10-16 05:19
I've created issue #693 to track discussion around automatic clean up.  Let's continue this comment thread there.

I'm going to close this issue, #221, now, because the original issue here was more about the location of the log files, rather than automatic cleanup.

**Comment by bbrummer** [comment] 2019-12-02 18:51
### ~/.azcopy/plans is an absolute train wreck.

I just got through fixing a crashed server because this folder filled with thousands of tiny files blew out all the inodes on the filesystem, effectively filling it (despite tons of free "space").

WHY are ALL Azure tools such a complete and total trainwreck?!  You don't have the most basic functionality working sanely...don't force magic misfeatures like "resume" down our throats especially if you don't know WTF you're doing (especially on Unix).

News Flash: CLI tools get used in cron scripts...that get run over and over and over and over.  Must we REALLY be forced to build a full Docker container to run azcopy inside of because it can't even be trusted to not crap all over itself?!

**Comment by zezha-msft** [comment] 2019-12-03 05:29
Hi @bbrummer, we are sorry to hear that you did not have a good experience.

To clarify, you can use `azcopy jobs clean` to remove the logs and plan files.

Please keep in mind that the tool supports many scenarios, including the ones where tons of data are transferred (imagine a million files at once), and it's very possible that a few transfers fail due to network conditions or other unpredictable reasons. Thus, it's actually essential to persist the job status and have the `resume` feature built in, so that in case of crashes, e.g. someone turned off the VM accidentally, the user can recover their progress.

That being said, we do realize that sometimes the plans/logs create a problem for people who run the tool over and over again. We have this item logged in our backlog, and will tackle it when priority permits.

Please kindly remain courteous so that we can have a productive conversation, and take your feedbacks into consideration in the future iterations of AzCopy.

**Comment by espentveit** [comment] 2019-12-17 18:03
Feedback: Wouldn't an easier solution to have a toggle that indicates if it's a long running job or not? Azcopy seems like it's supporting two workloads. "Large transfer/sync with report" and "curl". Indicating that the action is a "curl"-type job would turn off logging to disk, plans and show output of failed items directly to console. "Large transfer with report" would give all bells as whistles. Or maybe release a variant/alias like "azcp" for smaller jobs.

**Comment by JohnRusk** [comment] 2019-12-23 23:25
Thanks for the interesting and thoughtful feedback @espentveit.

**Comment by micktion** [comment] 2020-10-28 06:16
I've never seen a command line program that generates log files like this.  Output should be to standard output, if you want verbose logging there should be a switch for that.  If you want to create a log file you should simply redirect the standard output to a log file.

**Comment by perspark** [comment] 2021-05-26 08:57
I'm using a Microsoft hosted build agent with no access to the file system, hence I cannot se any logs from AzCopy. Extremely strange design decision to log to file 👎

**Comment by zezha-msft** [comment] 2021-05-27 07:31
Hi @perspark, you can customize where logs are stored. If you are referring to Azure DevOps build agents, you should have access to some location on the file system at least. 

And to clarify, the log is for verbose info to debug issues, the stdout is the concise info that shows progress and job status.

**Comment by dhirschfeld** [comment] 2021-07-14 05:50
My `azcopy` jobs run in an ephemeral container so any files created are destroyed along with the container. The stdout and stderr are logged but with the debug logs sent to a file it seems I have no opportunity to debug any failures?

**Comment by JohnRusk** [comment] 2021-07-14 06:24
@dhirschfeld Can you wrap the call to AzCopy in a little shell script, that just takes the log file and copies it to stdout or wherever you want. I'm not sure if you can predict it's _name_ (I don't work on AzCopy any more and my memory of log naming is hazy).  But, in an ephemeral container, it will be the _only_ file in the log directory.

**Comment by dhirschfeld** [comment] 2021-07-14 07:18
Yeah, that's basically what I've resorted to - cat'ing the log file after the process ends :/

The fact that there's an ugly workaround for a limitation of the tool shouldn't prevent the tool being fixed though.

I haven't seen any argument here why logging to stdout as an option shouldn't be supported. The main line of reasoning seems to be that the logs are needed for support however, in my situation this limitation actually prevents me from being able to send the logs to support. Logging to stdout doesn't need to be the default and if set `AzCopy` could print a warning saying the logs aren't being persisted for future support.

It's then the user's choice to choose where to send the logs, and if they choose to send to stdout without also tee'ing to a file then they'll simply have to re-run the job to capture the logs if they want support. If that takes them 6 hours, so be it - they were warned.

The tool's responsibility for preventing users from shooting themselves in the foot should stop with *warning* them about dangerous actions - it shouldn't prevent users who know what they're doing, from doing what they want (IMHO)

**Comment by JohnRusk** [comment] 2021-07-14 07:20
Glad to hear you have a workaround that works.  I'll leave wider consideration of the points you raise to the current members of the AzCopy team.

**Comment by zezha-msft** [comment] 2021-07-20 08:41
Hi @dhirschfeld, thanks for the feedbacks!

We have work planned to make the logs more concise and yet informational. Perhaps as part of that work item we can consider adding such a flag to pump the log into stdout. But it's tricky though, since we have regular progress updates that are supposed to go to stdout. We will evaluate the UX and make a decision.

**Comment by TomaszOledzki** [comment] 2021-07-21 12:59
I would like to highlight something here.

@JohnRusk @zezha-msft you're explaining how AzCopy handle logs and plans files is made for the sake of users and to comfort users.
AzCopy users are SysAdmins, IT Professionals and IT Stuff in general. Your users complains here, AzCopy behavior is bizarre and unexpected :).

**Comment by dreamflasher** [comment] 2022-04-26 07:16
3 years later: Still an open bug. Please reopen the ticket. azcopy is filling even a huge hd with log spam.

**Comment by debdude** [comment] 2022-04-26 16:29
👍 please reopen; current behavior is counter-intuitive in context of Unix-based systems

**Comment by zezha-msft** [comment] 2022-04-26 19:02
@dreamflasher @debdude thanks for reaching out. Could you please share with us what would the ideal behavior for the log file?

**Comment by micktion** [comment] 2022-04-27 04:40
@zezha-msft Hi, as per my comment from 17 months ago...

https://github.com/Azure/azure-storage-azcopy/issues/221#issuecomment-717724031

Disable diagnostic level logging by default, provide a switch to enable it.  Have informational level logging go to standard output.

**Comment by dreamflasher** [comment] 2022-04-27 21:35
Thanks a lot @zezha-msft - the core problem is that the log and plan files become huge and filling up too much disk space (I regularly have the issue that I can't even run a single azcopy task, sure it's several millions of files, but there's enough disk space for the files, just not for the log+plan files). 

The obvious solution is to provide an option to turn off writing plan and log files.

**Comment by mohsha-msft** [comment] 2022-04-28 04:03
You can specify env variable `AZCOPY_LOG_LOCATION`. It overrides where the log files are stored, to avoid filling up a disk.
Log files and plan files can be cleaned up to save disk space, using AzCopy's new `jobs rm` and `jobs clean` commands. For example: You can use `azcopy jobs clean --with-status=completed` to delete old azcopy jobs file.

Plan files are essential for AzCopy working and hance cannot be removed from the flow.

**Comment by dreamflasher** [comment] 2022-04-28 06:50
We are aware of this, but it does not solve the bug. Why are the plan files essential? Isn't it just noting which files have been downloaded? 
The problem is: A single azcopy run produces so much log and plan files that it fills any disk. So changing the location does not help, and cleaning afterwards neither.

**Comment by grahamoriley** [comment] 2022-05-03 17:58
I have the same issue as dreamflasher. Disk space is all used on log files.

**Comment by ppanyukov** [comment] 2022-05-04 16:50
For those facing the issue with file systems filling up, one possible workaround (in addition/alternative to Docker) is to use `nullfsvfs` -- a virtual sinkhole file system akin to `/dev/null` and set that as the directory for all logs and files `azcopy` produces. Anything written to this sinkhole goes to nowhere.

I haven't tried this myself bacause I no longer need `azcopy`, so don't know if this would work well.

Would be nice to hear back from someone who tries this out.

https://github.com/abbbi/nullfsvfs

**Comment by zezha-msft** [comment] 2022-05-07 07:32
To clarify, the plan files and the log files were a major requirement for the tool before it was even written, the reason being the need for reliability and supportability. 

Plan files provide the reliability as they are memory-mapped and allow the job to be resumed in case there is any crash, e.g. the VM got shut down by someone. The log file allows the user to reach out to the Azure support team in case anything goes wrong, since important data such as concise request/response traces are saved. It is important to save some amount of information by default, as otherwise there won't be anything for the user/support engineer to understand what happened.

I definitely understand the frustration that there are files taking up your disk space, and we've made efforts to make the logs/plans more concise. You could turn off logging with --log-level if you want, but I do not recommend it. If you find that your OS disk is too small, please consider mounting an additional disk on the VM.

**Comment by dreamflasher** [comment] 2022-05-07 07:36
And if I don't want to reach out to the support team and I don't want resume? There is no option to turn off writing plan files. And that's the simple request: Please provide an option to turn them off.

**Comment by zezha-msft** [comment] 2022-05-11 22:32
@dreamflasher in that case, I believe Azure CLI is a much better option for your scenario. Removing the reliability/retry-ability/supportability from AzCopy is a big task, and I'm not sure that it's the right approach.

Azure CLI offers the ability to upload/download files too, but it doesn't have plan files or log files. Please give it a try, thanks!

**Comment by dreamflasher** [comment] 2022-05-12 07:33
Azure CLI is a lot slower.

**Comment by zezha-msft** [comment] 2022-05-17 00:59
Thank you @debdude, for the compelling argument. I think you are right that the tool didn't consider the Linux server scenario enough, and there should be improvements.

I'll schedule some time for the team to evaluate the scale of this change (no log file, nor plan file). It may not be trivial since they are deeply engrained in the tool, and we may have to take multiple steps to ultimately arrive at the desired experience.

**Comment by shchukax** [comment] 2022-05-19 15:31
There's one one problem with writing logs into ~/.azcopy - disk space.  I recently had to use azcopy to migrate an entire azure storage account from one region to another.  azcopy aborted after several hours when it ran out of disk space to write logs.  The log file was over 100 GB in size.  Most home directories on linux servers simply don't have that much disk space.  There are other large devices that sometimes may be used - but sometimes I may want to send it to /dev/null if I don't care about these logs, and don't need the ability to revisit/review/restart the job.

**Comment by dreamflasher** [comment] 2022-05-19 15:39
Thank you @shchukax that's the problem I have been trying to report couple of times now, but so far I didn't manage them recognizing this as an issue.

**Comment by foxmeyson** [comment] 2022-07-07 19:53
The tool is good, but the solution with logs s*cks. We copied block blob storages whose size = 1TB, and logs occupied hundreds of gigabytes. VM for copyed had several denials of service (DoS). The disk spaces is over. Log level had = ERROR.
Until we figured out what's wrong! I suggest adding an explicit warning about this to the documentation page until the full solution

**Comment by foxmeyson** [comment] 2022-07-08 09:15
There is an important addition - in version 10.15.0, when running multiple times, the --log-level option is ignored and DEBUG is always written.
In 10.14.1 - this is not reproduced.
Im create issue: 
https://github.com/Azure/azure-storage-azcopy/issues/1845

**Comment by zezha-msft** [comment] 2022-07-08 21:03
Sorry @foxmeyson, this is a known bug, it will be addressed in the upcoming release. We are sorry for the inconvenience.

**Comment by sizhky** [comment] 2022-08-21 12:36
I have softlinked `/my/large/directory` to `~/.azcopy` 
That was the fastest (dirty) workaround I could do with.

**Comment by dreamflasher** [comment] 2022-08-21 16:43
Unfortunately, this doesn't work for me as a workaround, because with the number of files I need to transfer in one run the logs amount to >1TB of data, which I simply don't have idling around in any cloud machine.

**Comment by marc-hb** [comment] 2022-11-24 01:10
"Logging is hard. So we looked at the small number of solutions the entire world has converged to, then we invented something totally new and different from everyone else" -- The azcopy team.

**Comment by marc-hb** [comment] 2022-11-24 01:59
Trying to be more constructive, some of the problems with the current design:

- Some issues are reported in `$HOME/.azcopy/` while others are reported on stdout. For instance authentication issues are reported in `.azcopy/` while a broken symlink is (poorly) reported on stdout (#1974). This requires looking at two different places and correlate timestamps when something goes wrong. While others try hard to solve  _timestamp correlation_ problems (e.g. https://www.kernel.org/doc/html/v5.16/trace/sys-t.html), azcopy creates a timestamp correlation problem out of thin air!


- Simply way too verbose by default. Every developer of every piece of software wants detailed logs when something goes wrong. However most software demonstrates restrain and does not fill up hard drives by default and requests users to increase the log level only when something goes wrong. Being very verbose by default shows a lack of confidence IMHO.


- When azcopy is regularly started by some cron job, very hard to look at all the logs _in chronological sequence_. 

- Hardcoded destination. Do we still need to explain why hardcoding is bad in 2022? At the very least it should be possible to override the default directory and point it at some location under `logrotate` control.

- Actually, the "one log file per instance" is probably incompatible with `logrotate` anyway... I understand it's great for running multiple azcopy instances concurrently but regular cron jobs don't care about that. 

- Hard to `logrotate` as already discussed in many comments above. Maybe `azcopy jobs clean` could be more flexible and accept some "older than" or "bigger than" parameters similar to all other log rotate solutions?



And of course last but not least:
- all the confusion caused by and time spent adjusting to something different from everything else.

**Comment by micktion** [comment] 2022-11-24 02:33
I'll put it out there a third time...

https://github.com/Azure/azure-storage-azcopy/issues/221#issuecomment-717724031

As I said back in 2020....

All output should go to standard output.  If you want verbose logging there should be a switch for that.  If you want to create a log file you should simply redirect the standard output to a log file.  I think nearly everyone is confused by why this is so needlessly complicated.

**Comment by marc-hb** [comment] 2022-11-24 17:12
> All output should go to standard output[/stderr]. If you want verbose logging there should be a switch for that. If you want to create a log file you should simply redirect the standard output to a log file.

It's too late to have this _by default_ for obvious backwards compatibility reasons: cannot break existing users who already adjusted to the current design.

However there should certainly be an `--log-file=-` option to do that and while it may require a fair amount of code changes it really does not sound like "rocket science".

In July 2021:
> Perhaps as part of that work item we can consider adding such a flag to pump the log into stdout. But it's tricky though, since we have regular progress updates that are supposed to go to stdout. 

Progress updates can be disabled or altered when logs are explicitly directed to stdout/stderr.

> We will evaluate the UX and make a decision.

Have you?

**Comment by micktion** [comment] 2022-11-24 23:44
Funny... you had absolutely no issues totally breaking compatibility with the previous versions of Azcopy...

**Comment by maxburke** [comment] 2023-01-30 16:02
I'm trying to do a job with `azcopy` that I just can't do with `azcli` before the heat death of the universe -- setting the storage tier of some 50 million blobs -- but I can't complete the job without running out of drive space.

There's a bit of irony in that the current mechanism for managing these plan files was introduced for "reliability, retries, and restarts", but the only way I can resume these jobs is to delete all the accumulated plan files and start from scratch.

Can these plans be generated in a more space efficient manner, or cleaned up as they are processed?

**Comment by TomaszOledzki** [comment] 2023-01-30 16:14
> I'm trying to do a job with `azcopy` that I just can't do with `azcli` before the heat death of the universe -- setting the storage tier of some 50 million blobs -- but I can't complete the job without running out of drive space.
> 
> There's a bit of irony in that the current mechanism for managing these plan files was introduced for "reliability, retries, and restarts", but the only way I can resume these jobs is to delete all the accumulated plan files and start from scratch.
> 
> Can these plans be generated in a more space efficient manner, or cleaned up as they are processed?

Forget about azcopy as it's completely useless for moving lots of data, as the issue is known for so many years and no signs of fix in near future.

I couldn't wait for proper azcopy so I've written my own solution for copying and moving data using Azure Blob Storage REST API (https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api). Yes, quite a bit of effort but it does what is should do, it's reliable, not clogging disk anymore with state data and is using syslog on GNU/Linux for logging as azcopy should from day one. I advice you to do same thing.

**Comment by dreamflasher** [comment] 2023-01-30 17:02
Wow, thank you @TomaszOledzki ! I agree with you that it doesn't make sense to hope for Microsoft in this matter. Thank you for putting in the effort and writing something better! I ended up writing something myself as well, but unfortunately I couldn't match the speed of azcopy. I don't know what azcopy does, but apart from the design flaws and bugs around the plans, it's the fastest solution out there.

**Comment by JohnRusk** [comment] 2023-01-30 20:14
Hi Max, Thomasz and dreamflasher.  Do I understand correctly that your issues with disk space usage are primarily around the plan files (not the log files)?  If so, I'd suggest making a new issue (or finding an existing one) specifically about the disk space required by plan files, because the title of this one is about logs.

BTW, I've been working in a different team for a few years now, and so can no longer speak on behalf of the AzCopy team. For what it's worth, before working on AzCopy I wrote an older, experimental, Microsoft data transfer program which stored its "plan" data in memory.  That came with it's own set of problems!

**Comment by dreamflasher** [comment] 2023-01-30 20:23
@JohnRusk Thank you for chiming in. It's indeed both, both the log files and the plan files are getting too huge and render a transfer of many files impossible. So yeah, opening another issue for that would make sense, but from the reactions here there seems no understanding or willingness to understand that this is indeed an issue.

**Comment by shchukax** [comment] 2023-01-30 20:30
The latest version of azcopy accepts parameter --log-level, which you can
use to minimise the log file size, e.g. --log-level ERROR would only print
errors in the log. With that level, my copy operation on a container with
about 5 million files only produced about 10 KB log file. The plan is still
huge though.

**Comment by dreamflasher** [comment] 2023-01-30 20:38
@shchukax Hallelujah! Thank you, that's the biggest improvement of azcopy in years!

**Comment by Sysa** [comment] 2023-02-02 10:53
For anyone who is looking for ways of reading latest log file into your console, in the end of your script:
```
#where `/home/AzDevOps/.azcopy/` is your directory, change it appropriately

LOG_FILE_NAME=$(ls -t /home/AzDevOps/.azcopy/ | head -n1) \
&& cat /home/AzDevOps/.azcopy/${LOG_FILE_NAME}
```

**Comment by marc-hb** [comment] 2023-02-03 00:10
http://mywiki.wooledge.org/ParsingLs
http://mywiki.wooledge.org/BashFAQ/099
https://www.shellcheck.net/wiki/SC2045

**Comment by slagelwa** [comment] 2023-10-12 23:22
> The latest version of azcopy accepts parameter --log-level, which you can use to minimise the log file size, e.g. --log-level ERROR would only print errors in the log. 

That's good news.  Any chance of getting an additional level `REALLY_I_MEAN_NONE` which doesn't create any log file or plan? 😄

**Comment by rvandegrift** [comment] 2023-11-08 23:58
I'm also puzzled about these features.  But at least the cleanup is easily handled with systemd-tmpfiles.

First create `~/.config/user-tmpfiles.d/azcopy.conf` to cleanup anything older than 1 day (fix for your homedir and username):
```
d /home/rvandegrift/.azcopy 0755 rvandegrift rvandegrift 1d
```
See `tmpfiles.d(5)` for details on the syntax.

Second, enable systemd-tmpfiles on your user session:
```
$ systemctl --user enable --now systemd-tmpfiles-setup.service systemd-tmpfiles-clean.timer
Created symlink /home/rvandegrift/.config/systemd/user/basic.target.wants/systemd-tmpfiles-setup.service → /usr/lib/systemd/user/systemd-tmpfiles-setup.service.
Created symlink /home/rvandegrift/.config/systemd/user/timers.target.wants/systemd-tmpfiles-clean.timer → /usr/lib/systemd/user/systemd-tmpfiles-clean.timer.
```

**Comment by vibhansa-msft** [comment] 2023-12-20 16:06
Log level and log file path are configurable parameters in latest version. In addition we have also added logic to split and rotate the log file so that it does not grow in size beyond a certain point. Closing this report, feel free to create a new one if you still face some issues with the logging part.

**Closed by vibhansa-msft** 2023-12-20 16:06 UTC
Labels: enhancement
