### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ezra-at-lumedic** [Azure/azure-storage-azcopy#877] opened 2020-02-27 05:24 UTC
### Which version of the AzCopy was used? 

azcopy version 10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

azcopy ls https://ourblobname.dfs.core.windows.net/container/path/folder

### What problem was encountered?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x461274b]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.(*blobFSTraverser).traverse(0xc00019a080, 0x0, 0xc00000f3e0, 0x0, 0x0, 0x0, 0x0, 0x1)
	/Users/runner/runners/2.164.6/work/1/s/cmd/zc_traverser_blobfs.go:140 +0x77b
github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand(0x7ffeefbffab2, 0x60, 0x5, 0x0, 0x47917bc)
	/Users/runner/runners/2.164.6/work/1/s/cmd/list.go:157 +0x43c
github.com/Azure/azure-storage-azcopy/cmd.init.11.func2(0xc00025b680, 0xc0000c2b70, 0x1, 0x1)
	/Users/runner/runners/2.164.6/work/1/s/cmd/list.go:65 +0x72
github.com/spf13/cobra.(*Command).execute(0xc00025b680, 0xc0000c2b30, 0x1, 0x1, 0xc00025b680, 0xc0000c2b30)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x4d85700, 0xc00019bdd8, 0x0, 0xffffffffffffffff)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc000022980, 0x13, 0xc000022980, 0x13, 0xc0000c00e0, 0x19, 0x100)
	/Users/runner/runners/2.164.6/work/1/s/cmd/root.go:110 +0xcf
main.main()
	/Users/runner/runners/2.164.6/work/1/s/main.go:82 +0x3dd

### How can we reproduce the problem in the simplest way?

only a subset of the files in the folder are listed and then we get the above panic abort.

the storage account is secured and we're on a VPN.  All the needed creds etc are in the environment.  

the location is currently being written to as well - not that that should matter, but it seems to impact Azure blob storage adversely.  Az Blob storage seems to only poorly support simultaneous reads and writes.

### Have you found a mitigation/solution?

Noop.

**Comment by JohnRusk** [comment] 2020-02-27 05:50
Thanks for logging this @ezra-at-lumedic 

@adreed-msft  knows that part of the code best, so I'll leave it to her to answer this tomorrow.

As far as I can tell from the callstack you posted, this is entirely an AzCopy bug.  This:
>Az Blob storage seems to only poorly support simultaneous reads and writes.
is definitely not correct. (Although I'd be interested to hear about any other situations, other than AzCopy list, where you are seeing issues that seem to be related to simultaneous reads and writes.  In some cases things like blob leases are useful and I can share some links to those if needed).

**Comment by ezra-at-lumedic** [comment] 2020-02-27 19:00
Thanks @JohnRusk for the prompt response.

Yes, this is not the first time we've encountered such issues.  Last month we had two outages.  The first lasted for several days and was finally tracked down as a "bug / configuration issue" amongst components and (apparently) resolved, with no further details given as to root cause.  The second lasted over 12 hours and showed a failure in being able to read only from the blob that was being written to.  This one eventually resolved - seemingly on its own - with no response ever received from the ticket we opened.  At less than 90% availability it's a far, far cry from the published SLA.

**Comment by ezra-at-lumedic** [comment] 2020-02-27 19:05
Worse, the first proposal for resolving issues was that we change the naming scheme of our files in order to improve performance.  Needless to say that raised eyebrows and caused us to question the underlying architecture that would require such things.

Equally troubling was that the suggestions for improving read performance - naming things in sequence and lexicographically close together - was the opposite to the suggestion for improving write performance, which was to space things out.  But, since the reason we're writing data in the first place is to then be able to read it later, this suggestion seemed to come from folks that had either a different use case in mind or didn't understand why folks use storage in the first place.

"Examine the naming convention you use for accounts, containers, blobs, tables, and queues. Consider prefixing account, container, or blob names with a three-digit hash using a hashing function that best suits your needs."
-- [https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist)

**Comment by ezra-at-lumedic** [comment] 2020-02-27 19:07
Quote from [Performance and scalability checklist for Blob storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist) at greater length:
<<
If you organize your data using timestamps or numerical identifiers, make sure that you are not using an append-only (or prepend-only) traffic pattern. These patterns are not suitable for a range-based partitioning system. These patterns may lead to all traffic going to a single partition and limiting the system from effectively load balancing.

For example, if you have daily operations that use a blob with a timestamp such as yyyymmdd, then all traffic for that daily operation is directed to a single blob, which is served by a single partition server. Consider whether the per-blob limits and per-partition limits meet your needs, and consider breaking this operation into multiple blobs if needed. Similarly, if you store time series data in your tables, all traffic may be directed to the last part of the key namespace. If you are using numerical IDs, prefix the ID with a three-digit hash. If you are using timestamps, prefix the timestamp with the seconds value, for example, ssyyyymmdd. If your application routinely performs listing and querying operations, choose a hashing function that will limit your number of queries. In some cases, a random prefix may be sufficient.
>>

which again begs the question of what kinds of ideas are implemented that require the users to change the names of objects their storing in order to use the system.

**Comment by JohnRusk** [comment] 2020-02-27 19:47
Yeah, those two incidents you mention are not great.  I suspect the latter may have been mostly a failure of the support process.  I've never heard of any platform issue that would produce the symptoms you mentioned.

As for the performance advice: if your blobs are bigger than 4MB then you can mostly ignore that old advice, since with the introduction of High Throughput Block Blobs, naming no longer affects performance in the way it used to.  If your blobs are smaller than 4MB, then its worth looking at Premium Block Blobs. I know it costs more (in most cases), but it's specifically designed to support smaller blobs better than other account types.

**Comment by ezra-at-lumedic** [comment] 2020-02-27 20:09
Yes, the support and triage processes are so spotty (actually shoddy TBH) that we almost never even bother with opening tickets unless we're truly stuck.  The Blob outage was more than 24 hours old before we even opened the ticket.  For everything else we generally just find work-arounds, shrug and move on.  Occasionally (rarely) we find the GitHub page for a tool and then open an issue, but mostly we just assume that's how the dogfood is being made over there and roll with it as best we can.

Since you'd not heard of this but sound interested, do you want the ticket number for follow up?  I for one would love to get a proper RCA on it - we requested this but got no further color other than what I wrote above.

**Comment by ezra-at-lumedic** [comment] 2020-02-27 20:13
> As for the performance advice: if your blobs are bigger than 4MB then you can mostly ignore that old advice, since with the introduction of High Throughput Block Blobs, naming no longer affects performance in the way it used to. ...

Our small blobs are generally over 500MB.  But we'll keep the advice in mind.  Someone may want to alert the docs folks about updating that page.

**Comment by JohnRusk** [comment] 2020-02-27 20:19
Please email me the support ticket number. (I'm very busy right now on AzCopy v10.4 work, so can't promised any "SLA" on when I might follow up.  But would like to know).

Thanks also for suggesting the update to that perf page.  @normesta, would you know how to follow up to get that fixed? (Or at least a clear link to HTBB added?)

**Comment by JohnRusk** [comment] 2020-02-27 20:20
My email address is in my profile page.

**Comment by ezra-at-lumedic** [comment] 2020-02-27 21:16
> My email address is in my profile page.

Sent.

**Comment by ezra-at-lumedic** [comment] 2020-03-02 19:26
@adreed-msft any word on this?

**Comment by ezra-at-lumedic** [comment] 2020-03-10 20:32
@adreed-msft any word on this?

**Comment by JohnRusk** [comment] 2020-03-10 21:15
Thanks for the followup @ezra-at-lumedic.  I've pinged @adreed-msft directly in case she did get the earlier notifications from GitHub.  The AzCopy core team is a little stretched this month, so maybe I should have asked her before I originally "volunteered" her to look at this ;-)

**Comment by adreed-msft** [comment] 2020-03-10 21:47
Seems like we're trying to dereference the content length here.

Why we're not getting back a content length when we know it's a file and not a directory is beyond me.

@JohnRusk I'm of two minds here.

1. It'd make sense to default to 0 as the content length, since, it's not like there's any content there if we didn't get a content length back.

or

2. it'd make sense to error out here, since we should be getting a content length back.

**Comment by JohnRusk** [comment] 2020-03-10 21:53
Thanks @adreed-msft . I haven't fully understood the above yet. Let's discuss at our meeting later today.

**Comment by ezra-at-lumedic** [comment] 2020-03-10 21:56
Maybe the file is in the process of being uploaded.
Regardless, seems like a check prior to the dereference is needed.

Sent from my mobile, please expect typos.
________________________________

**Comment by adreed-msft** [comment] 2020-03-10 21:58
Interesting thought. I'm not certain it'd show up until data is committed, though @ezra-at-lumedic.

I'll have to try with a sizeable object.

**Comment by ezra-at-lumedic** [comment] 2020-03-10 22:00
I've only encountered the error when listing (rather when trying to list) the contents of a path/folder that's in the process of having blobs written at the same time.

Sent from my mobile, please expect typos.
________________________________

**Comment by ezra-at-lumedic** [comment] 2020-03-10 22:03
And one more point.
Defaulting to -1 in this case is preferred since a valid empty blob has size 0. Using a different, impossible value makes it clear that there's currently no size information available for that blob.

Sent from my mobile, please expect typos.
________________________________

**Comment by adreed-msft** [comment] 2020-03-10 22:05
Just tried while actively uploading a file and wasn't able to reproduce.

**Comment by ezra-at-lumedic** [comment] 2020-03-10 22:52
Try actively uploading 601 100+MB files all to the same path and then see ;-)

On Mar 10, 2020, at 3:05 PM, adreed-msft <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tried while actively uploading a file and wasn't able to reproduce.

**Comment by JohnRusk** [comment] 2020-03-11 00:50
FYI, Adele and I are trying to track down a root cause, for why we're getting a nil pointer instead of a pointer to (presumably) zero.

**Comment by JohnRusk** [comment] 2020-03-12 06:56
@ezra-at-lumedic I just realised there's a bug in our code that may incorrectly think that a folder is a file.  And then try to get its content-length (even tho it won't have one).  We've actually already fixed this for the 10.4 release.  So if that is indeed the cause of this problem, then we've already fixed it.  But just haven't released the fix yet.

I propose to leave this issue open until 10.4 is released, and you can retest then.   (The date for 10.4 is not announced yet.)  Sorry we don't have anything more immediate for you.

**Comment by ezra-at-lumedic** [comment] 2020-03-12 15:45
Sounds good to me.

Sent from my mobile, please expect typos.
________________________________

**Comment by ezra-at-lumedic** [comment] 2020-03-18 19:34
Do you have an ETA for when 10.4.0 will be released.  I'm running in to this again - this time when nothing is being written - and it's a big blocker for our work.  The so-called tools offered are literally unusable.

**Comment by JohnRusk** [comment] 2020-03-18 19:51
Answered offline.

**Comment by JohnRusk** [comment] 2020-03-18 19:52
Oh, one question @ezra-at-lumedic :  you wrote "this time when nothing is being written".  Can you share some more details on that? It sounds like it might be a different problem from the one at the top of this thread.

**Comment by ezra-at-lumedic** [comment] 2020-03-18 19:57
Running:
`$ azcopy ls https://REDACTED.dfs.core.windows.net/REDACT/ED > raw_tables.txt`
and get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x461274b]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.(*blobFSTraverser).traverse(0xc0000f2080, 0x0, 0xc00000ed60, 0x0, 0x0, 0x0, 0x0, 0x1)
	/Users/runner/runners/2.164.6/work/1/s/cmd/zc_traverser_blobfs.go:140 +0x77b
github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand(0x7ffeefbffac2, 0x4f, 0x5, 0x0, 0x47917bc)
	/Users/runner/runners/2.164.6/work/1/s/cmd/list.go:157 +0x43c
github.com/Azure/azure-storage-azcopy/cmd.init.11.func2(0xc000279680, 0xc0000bcb70, 0x1, 0x1)
	/Users/runner/runners/2.164.6/work/1/s/cmd/list.go:65 +0x72
github.com/spf13/cobra.(*Command).execute(0xc000279680, 0xc0000bcb30, 0x1, 0x1, 0xc000279680, 0xc0000bcb30)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x4d85700, 0xc0001b3dd8, 0x0, 0xffffffffffffffff)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0001108a0, 0x13, 0xc0001108a0, 0x13, 0xc0000c80e0, 0x19, 0x100)
	/Users/runner/runners/2.164.6/work/1/s/cmd/root.go:110 +0xcf
main.main()
	/Users/runner/runners/2.164.6/work/1/s/main.go:82 +0x3dd

```

**Comment by ezra-at-lumedic** [comment] 2020-03-18 19:58
It leaves the impressions that a) the Azure Blob storage REST API is poorly reflected in the provided command-line tool (no folder listing option, for example) and b) the code is of very low quality indeed, with basic, basic engineering practices - like try/catch blocks - not being implemented.

**Comment by JohnRusk** [comment] 2020-03-18 20:21
Thanks Ezra.  Re reflecting the REST API, we've had to make some harsh prioritization calls with AzCopy v10.  So for instance, the copy and sync functions have to get more investment of time than the ls one, because copy and sync are the primary goals of the tool.  I feel your pain. Just letting you know why ls is less polished.

Re engineering practices:  AzCopy v10 is written in Go. We believe our error handling is in line with best practice in Go (which does not have catch blocks in the traditional sense, but does have a "recover" mechanism which is appropriate for non-fatal errors.  But neither a catch block or "recover" can help with a non-recoverable error message - all they could to is make the failure message look better on screen. We are aware that certain non-recoverable errors currently look very ugly, as your example shows ;-)

**Comment by ezra-at-lumedic** [comment] 2020-03-18 22:55
Makes sense.  There are several features that are more involved to implement.  Others, however, really amount to adding a command-line param and passing the value along to the Rest API.  e.g., a delimiter.  Those look - and there are several - look like minimal effort for pretty big returns.

On Mar 18, 2020, at 1:21 PM, John Rusk [MSFT] <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks Ezra. Re reflecting the REST API, we've had to make some harsh prioritization calls with AzCopy v10. So for instance, the copy and sync functions have to get more investment of time than the ls one, because copy and sync are the primary goals of the tool. I feel your pain. Just letting you know why ls is less polished.

Re engineering practices: AzCopy v10 is written in Go. We believe our error handling is in line with best practice in Go (which does not have catch blocks in the traditional sense, but does have a "recover" mechanism which is appropriate for non-fatal errors. But neither a catch block or "recover" can help with a non-recoverable error message - all they could to is make the failure message look better on screen. We are aware that certain non-recoverable errors currently look very ugly, as your example shows ;-)

**Comment by BrydenOliver** [comment] 2020-04-05 21:50
Is there any word on a date a fix for this will be available?
I can consistently hit this on one of our storage accounts, whether data is being written or not.
I can't see any difference between this account and any of the other similar ones we have either.
I'm seeing this on PC, but the callstack looks the same.

**Comment by JohnRusk** [comment] 2020-04-05 22:32
Nothing to announce publicly yet.  Make sure you're subscribed to release notifications (hit the Watch button at the top of this page, and choose the relevant option).

**Comment by adreed-msft** [comment] 2020-04-10 19:14
10.4 has been released. Could you please test on the latest release @ezra-at-lumedic

**Comment by ezra-at-lumedic** [comment] 2020-04-13 16:25
It does not resolve the issues.

On Apr 10, 2020, at 12:14 PM, adreed-msft <notifications@github.com<mailto:notifications@github.com>> wrote:



10.4 has been released. Could you please test on the latest release @ezra-at-lumedic<https://github.com/ezra-at-lumedic>

**Comment by ezra-at-lumedic** [comment] 2020-04-13 16:26
Ezras-MacBook-Pro:tmp ezra$ azcopy ls "https://readacted.dfs.core.windows.net/also/redacted/" > full_list_13_apr_2020.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4626ed7]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd<http://github.com/Azure/azure-storage-azcopy/cmd>.(*blobFSTraverser).traverse(0xc00019c0c0, 0x0, 0xc00000ee00, 0x0, 0x0, 0x0, 0x5, 0xc00006a8a0)
/Users/runner/runners/2.165.2/work/1/s/cmd/zc_traverser_blobfs.go:169 +0x997
github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand<http://github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand>(0x7ffeefbffa72, 0x50, 0x5, 0xc000251300, 0x0)
/Users/runner/runners/2.165.2/work/1/s/cmd/list.go:159 +0x43d
github.com/Azure/azure-storage-azcopy/cmd.init.11.func2<http://github.com/Azure/azure-storage-azcopy/cmd.init.11.func2>(0xc00026f900, 0xc00010f6a0, 0x1, 0x1)
/Users/runner/runners/2.165.2/work/1/s/cmd/list.go:65 +0x72
github.com/spf13/cobra<http://github.com/spf13/cobra>.(*Command).execute(0xc00026f900, 0xc00010f660, 0x1, 0x1, 0xc00026f900, 0xc00010f660)
/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766<http://github.com/spf13/cobra@v0.0.3/command.go:766> +0x2aa
github.com/spf13/cobra<http://github.com/spf13/cobra>.(*Command).ExecuteC(0x4dcea80, 0xc00019ddd8, 0x0, 0xffffffffffffffff)
/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852<http://github.com/spf13/cobra@v0.0.3/command.go:852> +0x2ea
github.com/spf13/cobra<http://github.com/spf13/cobra>.(*Command).Execute(...)
/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800<http://github.com/spf13/cobra@v0.0.3/command.go:800>
github.com/Azure/azure-storage-azcopy/cmd.Execute<http://github.com/Azure/azure-storage-azcopy/cmd.Execute>(0xc0000fa8a0, 0x13, 0xc0000fa8a0, 0x13, 0xc0000fa900, 0x19, 0x100)
/Users/runner/runners/2.165.2/work/1/s/cmd/root.go:117 +0xcf
main.main()
/Users/runner/runners/2.165.2/work/1/s/main.go:82 +0x3dd
Ezras-MacBook-Pro:tmp ezra$


On Apr 10, 2020, at 12:14 PM, adreed-msft <notifications@github.com<mailto:notifications@github.com>> wrote:



10.4 has been released. Could you please test on the latest release @ezra-at-lumedic<https://github.com/ezra-at-lumedic>

**Comment by ezra-at-lumedic** [comment] 2020-04-13 16:30
Ezras-MacBook-Pro:tmp ezra$ azcopy ls "https://readacted.dfs.core.windows.net/also/redacted/" > full_list_13_apr_2020.txt
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4626ed7]

	goroutine 1 [running]:
	github.com/Azure/azure-storage-azcopy/cmd<http://github.com/Azure/azure-storage-azcopy/cmd>.(*blobFSTraverser).traverse(0xc00019c0c0, 0x0, 0xc00000ee00, 0x0, 0x0, 0x0, 0x5, 0xc00006a8a0)
	/Users/runner/runners/2.165.2/work/1/s/cmd/zc_traverser_blobfs.go:169 +0x997
	github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand<http://github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand>(0x7ffeefbffa72, 0x50, 0x5, 0xc000251300, 0x0)
	/Users/runner/runners/2.165.2/work/1/s/cmd/list.go:159 +0x43d
	github.com/Azure/azure-storage-azcopy/cmd.init.11.func2<http://github.com/Azure/azure-storage-azcopy/cmd.init.11.func2>(0xc00026f900, 0xc00010f6a0, 0x1, 0x1)
	/Users/runner/runners/2.165.2/work/1/s/cmd/list.go:65 +0x72
	github.com/spf13/cobra<http://github.com/spf13/cobra>.(*Command).execute(0xc00026f900, 0xc00010f660, 0x1, 0x1, 0xc00026f900, 0xc00010f660)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766<http://github.com/spf13/cobra@v0.0.3/command.go:766> +0x2aa
	github.com/spf13/cobra<http://github.com/spf13/cobra>.(*Command).ExecuteC(0x4dcea80, 0xc00019ddd8, 0x0, 0xffffffffffffffff)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852<http://github.com/spf13/cobra@v0.0.3/command.go:852> +0x2ea
	github.com/spf13/cobra<http://github.com/spf13/cobra>.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800<http://github.com/spf13/cobra@v0.0.3/command.go:800>
	github.com/Azure/azure-storage-azcopy/cmd.Execute<http://github.com/Azure/azure-storage-azcopy/cmd.Execute>(0xc0000fa8a0, 0x13, 0xc0000fa8a0, 0x13, 0xc0000fa900, 0x19, 0x100)
	/Users/runner/runners/2.165.2/work/1/s/cmd/root.go:117 +0xcf
	main.main()
	/Users/runner/runners/2.165.2/work/1/s/main.go:82 +0x3dd
	Ezras-MacBook-Pro:tmp ezra$

**Comment by JohnRusk** [comment] 2020-04-13 23:16
Sorry to hear its still failing.  @adreed-msft can you see if this latest failure at zc_traverser_blobfs.go:169 is the same as the original one which was at zc_traverser_blobfs.go:140. (Could be same, if additions earlier in the file have resulted in change to line number).

**Comment by adreed-msft** [comment] 2020-04-14 19:48
Yup, same place we're failing.

The solution to this feels like #813 and checking for missing info.

If we're missing information about an item, my gut feeling is that we should likely error out that item.

**Comment by ezra-at-lumedic** [comment] 2020-04-14 19:55
How about just send the information you Do have to output.
And then have a way of indicating "N/A" for the others. For example, Apache logs use a "-" to indicate "N/A".
If the API doesn't error out, the command line tool should not error out. It should make best effort. This is not a library where "fail fast" applies. This is a command line tool where: "do something reasonable/useful" applies. Since list is a non destructive command theta no good reason too just fail (aka, error out).

Sent from my mobile, please expect typos.
________________________________

**Comment by adreed-msft** [comment] 2020-04-14 20:00
It wouldn't fail the entire job-- Just the individual transfer.

The reason I feel _uncomfortable_ about transferring a file with an unknown content length is because if we treat it as a 0-length file, there's a nonzero chance we _will_ lose data.

So, my gut feeling is that I'd rather not transfer this particular file, which we cannot be too sure about, and to fail the single file, so it shows up as an error in the logs, the final stdout output, etc.

**Comment by ezra-at-lumedic** [comment] 2020-04-14 20:57
There is no transfer taking place.

The error I’m seeing is occurring in the midst of an “ls” command (listing contents under a path prefix).

If the same code is used for transferring it sounds like either a conditional needs to be threaded down through the code as context so it can behave differently when used for “ls” vs for “cp” or similar, or some other refactoring may be needed.

Again, there is no transfer taking place.  I think we’re not seeing the same thing.  I’m encountering failures with simple, non-change, non-destructive ls and that command should not fail.

On Apr 14, 2020, at 1:01 PM, adreed-msft <notifications@github.com<mailto:notifications@github.com>> wrote:



It wouldn't fail the entire job-- Just the individual transfer.

The reason I feel uncomfortable about transferring a file with an unknown content length is because if we treat it as a 0-length file, there's a nonzero chance we will lose data.

So, my gut feeling is that I'd rather not transfer this particular file, which we cannot be too sure about, and to fail the single file, so it shows up as an error in the logs, the final stdout output, etc.

**Comment by adreed-msft** [comment] 2020-04-14 21:30
>Again, there is no transfer taking place.  I think we’re not seeing the same thing.  I’m encountering failures with simple, non-change, non-destructive ls and that command should not fail.

Understood, but it's the same piece of code. You're right though, ls should be adapted for this kind of a thing.

**Comment by JohnRusk** [comment] 2020-04-23 23:15
I'm also unable to reproduce this, even in 10.3.4.  Let me follow up with our Mac expert, since it originally happened on Mac

**Comment by JohnRusk** [comment] 2020-04-23 23:20
@ezra-at-lumedic One question: you mentioned this happens when something is writing to the same place that you are listing.  Do you know what API that writer is using: e.g. is it using the ADLS Gen 2 REST API, the Blob REST API, or the ABFS driver in the likes of Azure HDInsight, Azure Databricks, and SQL Data Warehouse?   I'm just wondering if our failure to reproduce it may relate to how we are writing to it....

**Comment by ezra-at-lumedic** [comment] 2020-04-24 00:04
The writer is a self-hosted Azure Data Factory Integration Runtime using the Azure Blob Storage connector over a VPN.  I *think*, given the name of the connector type, that it’s using the Blob REST API, but I am not sure how to confirm that.

Currently, without concurrent writes to the blob store the listing function is working well.  But with writes it still errors out.

Hypothesizing here:

1) Could it be that under some conditions the Azure Blob Storage Service does not return a size for a blob if that blob is in the process of being updated or if there’s an open PUT connection but the data hasn’t been pushed down the channel?

2) Regardless of the “why”, clearly the API service does sometimes return a response body that does not have size info.  The list function should handle that gracefully and not crap out as it currently does.  The fact that the exact same code is used during an “copy” as during a “list” operation, speaks to me of the need for some kind of refactoring.

Thanks for being open to my 2cs.

/Ezra

On Apr 23, 2020, at 4:20 PM, John Rusk [MSFT] <notifications@github.com<mailto:notifications@github.com>> wrote:



@ezra-at-lumedic<https://github.com/ezra-at-lumedic> One question: you mentioned this happens when something is writing to the same place that you are listing. Do you know what API that writer is using: e.g. is it using the ADLS Gen 2 REST API, the Blob REST API, or the ABFS driver in the likes of Azure HDInsight, Azure Databricks, and SQL Data Warehouse? I'm just wondering if our failure to reproduce it may relate to how we are writing to it....

**Comment by JohnRusk** [comment] 2020-04-24 00:10
Thanks. That's helpful.  I had been assuming it was a nil value for a directory (since there was indeed a bug in that respect prior to 10.4.0) but your point about maybe it not getting size for a file is an interesting one.

>The list function should handle that gracefully and not crap out as it currently does.  

True

>The fact that the exact same code is used during an “copy” as during a “list” operation, speaks to me of the need for some kind of refactoring.

I'm not sure I've understood this. I would have thought it was a good thing for them to both use the same code (without the nil ref bug, of course!), but if I read your comment correctly you're indicating there might be reason why the should not use the same code.  Have I understood correctly?

**Comment by ezra-at-lumedic** [comment] 2020-04-24 02:46
Yes.  Thank you for the close reading.

Based on your colleagues view that during a copy operation the behavior when no size is available is to fail that particular blob, vs the case with a list when this should not be treated as a failure. I wrote lengthier explanation already and hopefully that's in the issue's history.
Shared code would still be fine, just needs to have a context indicator threaded down into it if the decision is made to implement different behaviors depending on whether a copy is in progress or just a list is.
Does that clarify the point I was trying to make?

Sent from my mobile, please expect typos.
________________________________

**Comment by JohnRusk** [comment] 2020-04-24 02:53
I understand now. Thanks.

**Comment by adreed-msft** [comment] 2022-11-07 19:01
Closing due to longevity. Feel free to re-open if the issue still persists in the latest version of the software.

**Closed by adreed-msft** 2022-11-07 19:01 UTC
