### ISSUE TITLE
Azcopy leaks memory and crashes when copying a large number of files

### ISSUE THREAD

**Issue by grzeg1** [Azure/azure-storage-azcopy#498] opened 2019-07-12 14:44 UTC
### Which version of the AzCopy was used? 
10.2.1.
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
```
azcopy copy "monitor" "https://container?SAS" --overwrite=false --recursive --include "*/2019-*"
```
### What problem was encountered?
Azcopy starts, goes on for some time, starts to leak memory, slows down to a stop, eats more and more memory, crashes.
Machine's memory size is 16GB
The almost-stop is at:
```
392 Done, 2 Failed, 31798 Pending, 178338 Skipped, 210530 Total, 2-sec Throughput (Mb/s): 2.5495
```
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                 
27310 root      20   0 5308436 2,902g  53432 S   9,2 18,6  10:18.43 azcopy    

```
### How can we reproduce the problem in the simplest way?
Try to copy ca. 200000 files, from big directory structure

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment] 2019-07-15 04:03
I have a hunch about the cause, but need to set up a way to reproduce it...

**Comment by JohnRusk** [comment] 2019-07-22 09:09
Just a quick note, to record progress and thoughts so far: I initially wondered if it was about mapping AzCopy's plan files into memory, but I don't think that should be the problem. Another theory is that, in certain cases particularly with very small files on Windows, issues in connection dialing were causing much more load on the system than they should #511 . That load was primarily in thread count, but could also affect RAM.  Since the dial issue may be Windows-only, it also doesn't explain this issue (which is from Linux.)  So, we still don't know for sure what's causing this issue here. We need to do a bit more investigation.

**Comment by JohnRusk** [comment] 2019-07-29 00:22
Just checking Greg: was this build from the public download links? (Those are all 64-bit, but I'm just wondering if there's any way you could have had a 32-bit version - e.g. by building it yourself or (maybe) from a build bundled with another tool)

**Comment by schybbkoh** [comment] 2019-07-29 08:59
I'm experiencing what is possibly the same issue. I'm running `AzCopy 10.1.2` on `Ubuntu 16.04.5 LTS` and trying to copy a 1TB, 750 files directory to blob storage. Azcopy crashes with the following stacktrace: 

```fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb351cb, 0x16)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc0fc000000, 0x4000000, 0x1178418)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x115fec0, 0x800000, 0x115fed0, 0x400)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x115fec0, 0x400, 0x0)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/mheap.go:1232 +0x42
runtime.(*mheap).allocSpanLocked(0x115fec0, 0x400, 0x1178428, 0xd13780)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/mheap.go:1150 +0x3a7
runtime.(*mheap).alloc_m(0x115fec0, 0x400, 0x101, 0x7fc314ff8e28)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x115fec0, 0x400, 0x7fc314010101, 0xc000751980)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x800000, 0x101, 0x0)
        /opt/hostedtoolcache/go/1.12.0/x64/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
```

What's curious, copying the same data *from* blob storage on a similar, although not identical environment (`Ubuntu 18.04.2 LTS`, `AzCopy 10.1.2`) does not cause any crashes.

**Comment by JohnRusk** [comment] 2019-07-29 10:06
@schybbkoh can you tell us a bit about the machine you're using : number of CPU s and amount of Ram in particular

**Comment by schybbkoh** [comment] 2019-07-29 10:07
Sure - it's `Standard DS14 v2 (16 vcpus, 112 GiB memory)`.

**Comment by JohnRusk** [comment] 2019-08-06 05:41
@schybbkoh I see from the other issue you logged that you have other programs (databases etc) running on the same VM.  As far as I can tell, the most likely cause of the memory issue that you've seen is as follows:
(a) On a 16 CPU machine AzCopy will use up to 8GB for its data buffers. (0.5 GB per CPU).  Sometimes there's a little overhead about that. E.g. in trying to replicate your scenario, I'm seeing about 7 GB in my upload test, but I saw a little more, 9 GB in my download tests. But in both cases the usage stabilized, and in fact slightly decreased sometimes aftre the first 10 mins or so.
(b) If your other processes were using an lot of RAM, that may explain the out of memory behavior that you saw (i.e. AzCopy tried to use about 8 GB, but there weren't 8 available)

**Comment by JohnRusk** [comment] 2019-08-06 05:47
@grzeg1 I've done a bunch of tests. I can't see anything out of the ordinary in my tests. Usage always stablizes at around the expected level.  And in fact the memory usage that you mention above, of 2.9 GB, is within the bounds of normal behaviour. E.g. on a 4-core machine, AzCopy will allocate up to 2 GB for its buffers, and with some overhead for the rest of the app's memory usage, that will take it up to the 2.9 that you see.)

I think that the most likely cause of the issue you are seeing is that somehow, the default memory usage of AzCopy is too much for your machine.  I.e. AzCopy isn't actually _leaking_, because its using 2.9 GB on purpose, and its memory growth will eventually stop.  But... in your case, the amount that its trying to use is just too much. Maybe you have other processes running on the machine, or some other reason why its default usage of 0.5 GB per CPU is too much.

In version 10.3, we are going to introduce a new environment variable called AZCOPY_BUFFER_GB.  In cases such as yours, you can set it to a lower figure than the default. E.g. set it to 1 or even 0.5 in your case.  I believe that will solve the problem that you have reported.  Please let us know what you think of that solution.

We will leave this issue open until 10.3 is released.

**Comment by JohnRusk** [comment] 2019-08-06 05:50
PS. There may be very slow increases in usage above the "stable" figure as each new job-part-plan-file is accessed (there's one for every 10,000 files).  But that usage is typically only a few MB for every 10,000 files, which works out to a few 10s of MB for all the plan files needed for @grzeg1's test case.  So while accessing the plan files may show very small RAM usage increases, the core of the issue is probably as above - i.e. AzCopy trying to allocate too much for its buffers.

**Comment by schybbkoh** [comment] 2019-08-06 07:30
`AzCopy tried to use about 8 GB, but there weren't 8 available)`
This obviously sound like the easiest and most plausible explanation, however chances are that it's true only under condition that this `On a 16 CPU machine AzCopy will use up to 8GB for its data buffers. (0.5 GB per CPU)` is true for `azcopy v10` and not true for `acopy v7`. 
What I mean is that the problem occured consistently for a few days in a row in my environment when using `azcopy v10` and was gone immediately after I switched to `azcopy v7`. So the question would be what's the memory management policy for `azcopy v7`?

**Comment by JohnRusk** [comment] 2019-08-06 07:50
I don't know what the memory management policy is for v7. I've never really worked on that codebase, but I strongly suspect it uses less buffering between disk and network, and therefore less memory.  In which case, that would explain your observations.

**Comment by driftavalli** [comment] 2019-09-23 17:21
Could you tell me which branch this has been fixed on so I can build that? I have been running the version available on "https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10" website (10.2.1) and it's been crashing consistently.
Could it be any one of these?

```
remotes/origin/jr-temp-test
remotes/origin/jrusk-experimental-tuning
remotes/origin/jrusk-sequential-read
```

**Comment by grzeg1** [comment] 2019-09-25 16:34
What was interesting, minutes before the crash it would slow almost to a point of stopping.
I will probably have more large directories files to copy in the near future. Do we have any updated versions I could test?

**Comment by JohnRusk** [comment] 2019-09-25 19:55
No updated version just yet, sorry.  The AZCOPY_BUFFER_GB setting is coming in version 10.3, which will be the next one to come out, and is due fairly soon.

**Comment by JohnRusk** [comment] 2019-10-11 00:12
Version 10.3 is out now, with the AZCOPY_BUFFER_GB environment variable.

**Closed by JohnRusk** 2019-10-11 00:12 UTC
Labels: fixed/pending release

**Comment by AlexG7796** [comment] 2019-10-29 16:17
Hello  @JohnRusk. That's another thing what I'm trying to tune in my uploads.
The documentation about AZCOPY_BUFFER_GB feature is very short and completely straightforward. But I can't understand why RAM limitation does not work after implementing it on the server. Could you please clarify?
![05](https://user-images.githubusercontent.com/57005342/67786683-5af0d000-fa80-11e9-8687-a93fb873ded6.jpg)

I event thought that messed with command:
![06](https://user-images.githubusercontent.com/57005342/67786882-aacf9700-fa80-11e9-88c5-fb813fe0211d.jpg)

**Comment by JohnRusk** [comment] 2019-10-29 19:36
Alex, to start with, can you check the start of the AzCopy log file. The name and location of that file is output on screen when the job starts.  You'll need to look at about the 7th line. It should say something like this:

```
2019/10/25 03:19:36 Max file buffer RAM 8.000 GB
```

Can you see if the amount of file buffer RAM there matches what you set.

Also, a few other other questions, that will help:
1. Which version of AzCopy are you using? (Should be on 10.3.1, since that's the latest)
2. Roughly how many files are you copying?
3. Are you using `sync` or `copy`?
4. If `copy` are you setting the overwrite parameter?

(There's a known RAM usage issue with very high numbers of skipped files when overwrite=false.)

**Comment by AlexG7796** [comment] 2019-10-30 12:37
John, here are details:

> 2019/10/30 08:01:26 Number of CPUs: 16
> 2019/10/30 08:01:26 Max file buffer RAM 8.000 GB

1) Version of AzCopy is 10.3. We implemented it in multiple enviroments and did not have a chance to roll to 10.3.1 because started to dig into different issues with it.
I can see from log file that new buffer value was not applied. Probably we really need to upgrade to 10.3.1, I'll try to test it later today on some server.
2) I'm using 'sync' command.
3) Every run of AzCopy  checks 1862 files in total on this particular server, but uploads only 38 new files every hour.

**Comment by JohnRusk** [comment] 2019-10-30 22:43
Thanks. That's informative @AlexG7796 .  At the file counts that you are working with, AzCopy should have a relatively modest overhead above the AZCOPY_BUFFER_GB setting.  And there are no changes to the way that setting is handled between 10.3 and 10.3.1. So I think your problem is entirely that its not seeing the environment variable. 

So, somewhere, you have a "simple" issue with AzCopy not seeing your environment variable change. Are you running AzCopy from the same command window where you set the environment variable?  If you're not, then it won't see it.

Also, you can check whether it is seeing the variable by setting the variable to a value, then running `azcopy env`
That will display all the environment variables, include the current values for those that have a value. E.g. set it to 0.5 and it should display as having the value 0.5 when you run `azcopy env`. That gives you a quick-ish way to test, until you figure out why its not seeing the value that you set.

**Comment by AlexG7796** [comment] 2019-10-31 11:05
> So, somewhere, you have a "simple" issue with AzCopy not seeing your environment variable change. Are you running AzCopy from the same command window where you set the environment variable? If you're not, then it won't see it.

That's it. I've set value from CMD and then ran prepared uploading script from Powershell. So, I have to set buffer value for each upload session, i.e. - put it into my script.
Sorry for that, I have too little experience with azCopy. Thank you for help, John!

**Comment by JohnRusk** [comment] 2019-10-31 19:14
FYI, there are some rules at Operating System level about how environment variables work.  IIRC the rules are basically that you can have some global ones (do  web search if you want to see how to set those up) and then others that you set non-globally propagate to child processes (usually?).  So you can look up those rules if you need to. They're just standard environment variable behaviour, nothing special relating to AzCopy.

BTW, when setting env vars in PowerShell, the syntax looks like:
`$env:AZCOPY_BUFFER_GB=1.5`

**Comment by dd8** [comment] 2019-12-27 15:37
Had very similar problems with AzCopy 10.3.3 on Windows running out of memory - with the following exception output:  

```
.\azcopy.exe : runtime: VirtualAlloc of 8192 bytes failed with errno=1455
At line:1 char:1
+ .\azcopy.exe copy 'redacted....
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (runtime: Virtua...with errno=1455:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

My transfer had around 4 million small files. They'd uploaded to Azure storage using 10.3.3 with no problems - the issue happened when downloading from storage to a VM.

The amount of VM used by AzCopy kept increasing until it hit the size of the page file and the above exception occurred.

I noticed this in the log:

```
2019/12/27 14:57:08 Max open files when downloading: 2147483311 (auto-computed)
```

Setting  AZCOPY_CONCURRENT_FILES=50 (default is 2**31) and AZCOPY_CONCURRENCY_VALUE=4 seemed to fix the problem

In my case I think the issue stemmed from a very large number of pending files - the rate new files were found by scanning was much higher than the download rate. Even with these settings there were an unusually high number of handles opened by AzCopy (around 35,000)

**Comment by JohnRusk** [comment] 2020-01-05 23:39
Thanks @dd8 for the detailed info.  I don't know why you see so many file handles. My hopeful guess is that there's actually some kind of time lag in what you're seeing in Task Manager - e.g. there were 35,000 opened in the last x seconds, even though not that many of them are actually open _right now_.  I'll make a note to take a closer look at this one day.

**Comment by MarkCranness** [comment] 2024-11-17 10:32
This same problem happened to me with 10.27.1 and 10.27.0

"azcopy copy" ran on an Azure "Standard D8ls v5 (8 vcpus, 16 GiB memory)", copying from local drive into Blob container, with $env:AZCOPY_CONCURRENCY_VALUE=256

Nothing much running on the VM, and 2.8 GB/16 GB used when idle (before the azcopy).
~1,6 M files being copied.

VM memory climbs to near 16 GB (99-100%(, then PowerShell ISE crashed and restarted, leaving azcopy.exe process still running.
(When azcopy run in PowerShell, eventually multiple stack dumps output.)

![Image](https://github.com/user-attachments/assets/db1b9203-1fbc-4428-ad86-ad1411afe8e9)

Using dd8's hint, eventually ran it with:
$env:AZCOPY_BUFFER_GB = '0.5'
$env:AZCOPY_CONCURRENCY_VALUE=8
$env:AZCOPY_CONCURRENT_FILES=50

... memory still climbed to 99-100% for many minutes, then dropped to 11.5/16, but the copy did finish.

**Comment by MarkCranness** [comment] 2024-11-17 10:59
Of note might be:
When azcopy used all memory and crashed, "--overwrite=ifSourceNewer" was set.

Re-running with "--overwrite=true", and the memory used does not (has not so far) risen above 5.7/16 (from a base of 2.8/16).
