### ISSUE TITLE
Copying a directory from a File Share snapshot doesn't copy its contents

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1510] opened 2021-08-06 22:02 UTC
### Which version of the AzCopy was used? 
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
mac

### What command did you run?
./azcopy copy "https://acct.file.core.windows.net/f01/directory/*?SAS&sharesnapshot=snapshot_id" "https://acct.file.core.windows.net/f01/directory?SAS" --overwrite=prompt --preserve-smb-info=true --recursive --log-level=INFO;

or 

./azcopy copy "https://acct.file.core.windows.net/f01/directory/?SAS&sharesnapshot=snapshot_id" "https://acct.file.core.windows.net/f01/?SAS" --overwrite=prompt --preserve-smb-info=true --recursive --log-level=INFO;

### What problem was encountered?
AzCopy 

### How can we reproduce the problem in the simplest way?
Run a similar command given above.

### Have you found a mitigation/solution?
Go into the directory and copy files manually.

**Comment by gapra-msft** [comment] 2022-11-17 18:30
Hi @JasonYeMSFT are you still experiencing this issue with the latest version of AzCopy? I was unable to reproduce this issue with v10.16.2 Here is the command I ran 

.\azcopy.exe copy "https://gaprauswest2.file.core.windows.net/azcopytest/dir/?sharesnapshot=XXX&sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2022-11-29T02:25:17Z&st=2022-11-17T18:25:17Z&spr=https,http&sig=XXXXX" "https://gaprauswest2.file.core.windows.net/azcopytest/destination/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2022-11-29T02:25:17Z&st=2022-11-17T18:25:17Z&spr=https,http&sig=XXXX" --overwrite=prompt --preserve-smb-info=true --recursive --log-level=DEBUG

I will go ahead and close this issue since it is not reproducible on the latest version. Please feel free to open a new issue if you experience this again.

**Closed by gapra-msft** 2022-11-17 18:30 UTC

**Comment by JasonYeMSFT** [comment] 2022-11-17 21:34
The bug is fixed for me with 10.16.2.
