### ISSUE TITLE
Downloading an empty ADLS Gen2 folder never ends

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#412] opened 2019-05-23 18:07 UTC
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac and Windows

### What command did you run?
`./azcopy copy "https://REDACTED.dfs.core.windows.net/REDACTED/New%20Folder/" "/Users/me/Downloads" --overwrite=false --recursive --from-to=BlobFSLocal --check-md5 "FailIfDifferent"`

(was using OAuth for auth)

### What problem was encountered?
The job never finished.

### How can we reproduce the problem in the simplest way?
Create an empty folder in an ADLS Gen2 container and try to download it with a similar command.

### Have you found a mitigation/solution?
Check if the folder is empty prior to using AzCopy.

**Comment by JohnRusk** [comment] 2019-05-24 03:51
Will add this to our backlog. Can't offer a firm ETA right now, so there's likely to a period of time when you need to use the workaround, I'm sorry.

**Comment by MRayermannMSFT** [comment] 2019-05-24 05:08
Sounds good. Thanks John!

**Comment by adreed-msft** [comment] 2019-05-29 17:33
I actually just discovered the cause of this incidentally. For some odd reason, we infer this is a blob URL. Not sure why this behavior occurs, but I'll note it on the backlog item.

**Comment by adreed-msft** [comment] 2019-05-29 17:43
Uh. Correction, I need to investigate this more.

**Comment by adreed-msft** [comment] 2019-07-12 16:46
This one's dead simple. We missed a length check for directories. Container copies do `if len(e.Transfers) == 0` and exit if the length is 0. To keep things DRY, I'll move this check to `copyDownloadBlobFSEnumerator.dispatchFinalPart`.

**Comment by adreed-msft** [comment] 2019-07-12 17:08
Though, considering we are about to enter a point where we refactor our copy enumerators, I'll hold off on making this change for now.

**Comment by JohnRusk** [comment] 2019-09-23 03:31
TODO: see if we fixed this in the enumeration work. I suspect we did.

**Comment by adreed-msft** [comment] 2019-09-25 22:34
Yup, this one is fixed in the enumeration work @JohnRusk. This got fixed due to our changes in STE where a transfer will error out if nothing is scheduled.

**Comment by adreed-msft** [comment] 2019-10-15 19:16
This has been fixed in the latest release-- This was caused by us not questioning the number of transfers (both in the FE and in the STE).

Enjoy!

**Closed by adreed-msft** 2019-10-15 19:16 UTC
Labels: fixed/pending release
